// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             v7.36.1
// source: api.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationApiAllApi = "/api.admin.v1.Api/AllApi"
const OperationApiCreateApi = "/api.admin.v1.Api/CreateApi"
const OperationApiDeleteApi = "/api.admin.v1.Api/DeleteApi"
const OperationApiFindApi = "/api.admin.v1.Api/FindApi"
const OperationApiListApi = "/api.admin.v1.Api/ListApi"
const OperationApiQueryPolicyPathByRoleKey = "/api.admin.v1.Api/QueryPolicyPathByRoleKey"
const OperationApiUpdateApi = "/api.admin.v1.Api/UpdateApi"

type ApiHTTPServer interface {
	// AllApi 获取所有api
	AllApi(context.Context, *AllApiRequest) (*AllApiReply, error)
	// CreateApi 创建api
	CreateApi(context.Context, *CreateApiRequest) (*CreateApiReply, error)
	// DeleteApi 删除api
	DeleteApi(context.Context, *DeleteApiRequest) (*DeleteApiReply, error)
	// FindApi 获取api
	FindApi(context.Context, *FindApiRequest) (*FindApiReply, error)
	// ListApi api列表
	ListApi(context.Context, *ListApiRequest) (*ListApiReply, error)
	// QueryPolicyPathByRoleKey 获取角色拥有的api权限
	QueryPolicyPathByRoleKey(context.Context, *QueryPolicyPathByRoleKeyRequest) (*QueryPolicyPathByRoleKeyReply, error)
	// UpdateApi 更新api
	UpdateApi(context.Context, *UpdateApiRequest) (*UpdateApiReply, error)
}

func RegisterApiHTTPServer(s *http.Server, srv ApiHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/system/api/list", _Api_ListApi0_HTTP_Handler(srv))
	r.Handle("GET", "/system/api/all", _Api_AllApi0_HTTP_Handler(srv))
	r.Handle("POST", "/system/api", _Api_CreateApi0_HTTP_Handler(srv))
	r.Handle("PUT", "/system/api", _Api_UpdateApi0_HTTP_Handler(srv))
	r.Handle("GET", "/system/api/getPolicyPathByRoleId", _Api_QueryPolicyPathByRoleKey0_HTTP_Handler(srv))
	r.Handle("GET", "/system/api/{id}", _Api_FindApi0_HTTP_Handler(srv))
	r.Handle("DELETE", "/system/api/{id}", _Api_DeleteApi0_HTTP_Handler(srv))
}

func _Api_ListApi0_HTTP_Handler(srv ApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListApiRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationApiListApi)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListApi(ctx, req.(*ListApiRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListApiReply)
		return ctx.Result(200, reply)
	}
}

func _Api_AllApi0_HTTP_Handler(srv ApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AllApiRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationApiAllApi)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AllApi(ctx, req.(*AllApiRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AllApiReply)
		return ctx.Result(200, reply)
	}
}

func _Api_CreateApi0_HTTP_Handler(srv ApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateApiRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationApiCreateApi)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateApi(ctx, req.(*CreateApiRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateApiReply)
		return ctx.Result(200, reply)
	}
}

func _Api_UpdateApi0_HTTP_Handler(srv ApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateApiRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationApiUpdateApi)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateApi(ctx, req.(*UpdateApiRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateApiReply)
		return ctx.Result(200, reply)
	}
}

func _Api_QueryPolicyPathByRoleKey0_HTTP_Handler(srv ApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in QueryPolicyPathByRoleKeyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationApiQueryPolicyPathByRoleKey)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.QueryPolicyPathByRoleKey(ctx, req.(*QueryPolicyPathByRoleKeyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*QueryPolicyPathByRoleKeyReply)
		return ctx.Result(200, reply)
	}
}

func _Api_FindApi0_HTTP_Handler(srv ApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FindApiRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationApiFindApi)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FindApi(ctx, req.(*FindApiRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FindApiReply)
		return ctx.Result(200, reply)
	}
}

func _Api_DeleteApi0_HTTP_Handler(srv ApiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteApiRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationApiDeleteApi)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteApi(ctx, req.(*DeleteApiRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteApiReply)
		return ctx.Result(200, reply)
	}
}

type ApiHTTPClient interface {
	// AllApi 获取所有api
	AllApi(ctx context.Context, req *AllApiRequest, opts ...http.CallOption) (rsp *AllApiReply, err error)
	// CreateApi 创建api
	CreateApi(ctx context.Context, req *CreateApiRequest, opts ...http.CallOption) (rsp *CreateApiReply, err error)
	// DeleteApi 删除api
	DeleteApi(ctx context.Context, req *DeleteApiRequest, opts ...http.CallOption) (rsp *DeleteApiReply, err error)
	// FindApi 获取api
	FindApi(ctx context.Context, req *FindApiRequest, opts ...http.CallOption) (rsp *FindApiReply, err error)
	// ListApi api列表
	ListApi(ctx context.Context, req *ListApiRequest, opts ...http.CallOption) (rsp *ListApiReply, err error)
	// QueryPolicyPathByRoleKey 获取角色拥有的api权限
	QueryPolicyPathByRoleKey(ctx context.Context, req *QueryPolicyPathByRoleKeyRequest, opts ...http.CallOption) (rsp *QueryPolicyPathByRoleKeyReply, err error)
	// UpdateApi 更新api
	UpdateApi(ctx context.Context, req *UpdateApiRequest, opts ...http.CallOption) (rsp *UpdateApiReply, err error)
}

type ApiHTTPClientImpl struct {
	cc *http.Client
}

func NewApiHTTPClient(client *http.Client) ApiHTTPClient {
	return &ApiHTTPClientImpl{client}
}

// AllApi 获取所有api
func (c *ApiHTTPClientImpl) AllApi(ctx context.Context, in *AllApiRequest, opts ...http.CallOption) (*AllApiReply, error) {
	var out AllApiReply
	pattern := "/system/api/all"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationApiAllApi),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateApi 创建api
func (c *ApiHTTPClientImpl) CreateApi(ctx context.Context, in *CreateApiRequest, opts ...http.CallOption) (*CreateApiReply, error) {
	var out CreateApiReply
	pattern := "/system/api"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationApiCreateApi),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteApi 删除api
func (c *ApiHTTPClientImpl) DeleteApi(ctx context.Context, in *DeleteApiRequest, opts ...http.CallOption) (*DeleteApiReply, error) {
	var out DeleteApiReply
	pattern := "/system/api/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationApiDeleteApi),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// FindApi 获取api
func (c *ApiHTTPClientImpl) FindApi(ctx context.Context, in *FindApiRequest, opts ...http.CallOption) (*FindApiReply, error) {
	var out FindApiReply
	pattern := "/system/api/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationApiFindApi),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListApi api列表
func (c *ApiHTTPClientImpl) ListApi(ctx context.Context, in *ListApiRequest, opts ...http.CallOption) (*ListApiReply, error) {
	var out ListApiReply
	pattern := "/system/api/list"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationApiListApi),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// QueryPolicyPathByRoleKey 获取角色拥有的api权限
func (c *ApiHTTPClientImpl) QueryPolicyPathByRoleKey(ctx context.Context, in *QueryPolicyPathByRoleKeyRequest, opts ...http.CallOption) (*QueryPolicyPathByRoleKeyReply, error) {
	var out QueryPolicyPathByRoleKeyReply
	pattern := "/system/api/getPolicyPathByRoleId"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationApiQueryPolicyPathByRoleKey),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateApi 更新api
func (c *ApiHTTPClientImpl) UpdateApi(ctx context.Context, in *UpdateApiRequest, opts ...http.CallOption) (*UpdateApiReply, error) {
	var out UpdateApiReply
	pattern := "/system/api"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationApiUpdateApi),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
