// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.14.0
// source: base.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiBase) Reset() {
	*x = ApiBase{}
	mi := &file_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiBase) ProtoMessage() {}

func (x *ApiBase) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiBase.ProtoReflect.Descriptor instead.
func (*ApiBase) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{0}
}

func (x *ApiBase) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ApiBase) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type DeptTree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeptId        int64                  `protobuf:"varint,1,opt,name=deptId,proto3" json:"deptId,omitempty"`
	ParentId      int64                  `protobuf:"varint,3,opt,name=parentId,proto3" json:"parentId,omitempty"`
	DeptPath      string                 `protobuf:"bytes,4,opt,name=deptPath,proto3" json:"deptPath,omitempty"`
	DeptName      string                 `protobuf:"bytes,5,opt,name=deptName,proto3" json:"deptName,omitempty"`
	Sort          int32                  `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	Leader        string                 `protobuf:"bytes,7,opt,name=leader,proto3" json:"leader,omitempty"`
	Phone         string                 `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,9,opt,name=email,proto3" json:"email,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	CreateBy      string                 `protobuf:"bytes,11,opt,name=createBy,proto3" json:"createBy,omitempty"`
	UpdateBy      string                 `protobuf:"bytes,12,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
	Children      []*DeptTree            `protobuf:"bytes,13,rep,name=children,proto3" json:"children,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeptTree) Reset() {
	*x = DeptTree{}
	mi := &file_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeptTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptTree) ProtoMessage() {}

func (x *DeptTree) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptTree.ProtoReflect.Descriptor instead.
func (*DeptTree) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{1}
}

func (x *DeptTree) GetDeptId() int64 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

func (x *DeptTree) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *DeptTree) GetDeptPath() string {
	if x != nil {
		return x.DeptPath
	}
	return ""
}

func (x *DeptTree) GetDeptName() string {
	if x != nil {
		return x.DeptName
	}
	return ""
}

func (x *DeptTree) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *DeptTree) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

func (x *DeptTree) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *DeptTree) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DeptTree) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeptTree) GetCreateBy() string {
	if x != nil {
		return x.CreateBy
	}
	return ""
}

func (x *DeptTree) GetUpdateBy() string {
	if x != nil {
		return x.UpdateBy
	}
	return ""
}

func (x *DeptTree) GetChildren() []*DeptTree {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *DeptTree) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *DeptTree) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type RoleData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	RoleName      string                 `protobuf:"bytes,2,opt,name=roleName,proto3" json:"roleName,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	RoleKey       string                 `protobuf:"bytes,4,opt,name=roleKey,proto3" json:"roleKey,omitempty"`
	RoleSort      int32                  `protobuf:"varint,5,opt,name=roleSort,proto3" json:"roleSort,omitempty"`
	DataScope     int64                  `protobuf:"varint,6,opt,name=dataScope,proto3" json:"dataScope,omitempty"`
	CreateBy      string                 `protobuf:"bytes,7,opt,name=createBy,proto3" json:"createBy,omitempty"`
	UpdateBy      string                 `protobuf:"bytes,8,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
	Remark        string                 `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`
	MenuIds       []int32                `protobuf:"varint,10,rep,packed,name=menuIds,proto3" json:"menuIds,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleData) Reset() {
	*x = RoleData{}
	mi := &file_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleData) ProtoMessage() {}

func (x *RoleData) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleData.ProtoReflect.Descriptor instead.
func (*RoleData) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{2}
}

func (x *RoleData) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RoleData) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RoleData) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RoleData) GetRoleKey() string {
	if x != nil {
		return x.RoleKey
	}
	return ""
}

func (x *RoleData) GetRoleSort() int32 {
	if x != nil {
		return x.RoleSort
	}
	return 0
}

func (x *RoleData) GetDataScope() int64 {
	if x != nil {
		return x.DataScope
	}
	return 0
}

func (x *RoleData) GetCreateBy() string {
	if x != nil {
		return x.CreateBy
	}
	return ""
}

func (x *RoleData) GetUpdateBy() string {
	if x != nil {
		return x.UpdateBy
	}
	return ""
}

func (x *RoleData) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *RoleData) GetMenuIds() []int32 {
	if x != nil {
		return x.MenuIds
	}
	return nil
}

func (x *RoleData) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *RoleData) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type ApiData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ApiGroup      string                 `protobuf:"bytes,4,opt,name=apiGroup,proto3" json:"apiGroup,omitempty"`
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiData) Reset() {
	*x = ApiData{}
	mi := &file_base_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiData) ProtoMessage() {}

func (x *ApiData) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiData.ProtoReflect.Descriptor instead.
func (*ApiData) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{3}
}

func (x *ApiData) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ApiData) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ApiData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ApiData) GetApiGroup() string {
	if x != nil {
		return x.ApiGroup
	}
	return ""
}

func (x *ApiData) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ApiData) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *ApiData) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type MenuTreeAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Redirect      string                 `protobuf:"bytes,3,opt,name=redirect,proto3" json:"redirect,omitempty"`
	Component     string                 `protobuf:"bytes,4,opt,name=component,proto3" json:"component,omitempty"`
	Meta          *MenuTreeMeta          `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	Children      []*MenuTreeAuth        `protobuf:"bytes,6,rep,name=children,proto3" json:"children,omitempty"`
	ParentId      int64                  `protobuf:"varint,7,opt,name=parentId,proto3" json:"parentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuTreeAuth) Reset() {
	*x = MenuTreeAuth{}
	mi := &file_base_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuTreeAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuTreeAuth) ProtoMessage() {}

func (x *MenuTreeAuth) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuTreeAuth.ProtoReflect.Descriptor instead.
func (*MenuTreeAuth) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{4}
}

func (x *MenuTreeAuth) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuTreeAuth) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MenuTreeAuth) GetRedirect() string {
	if x != nil {
		return x.Redirect
	}
	return ""
}

func (x *MenuTreeAuth) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *MenuTreeAuth) GetMeta() *MenuTreeMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *MenuTreeAuth) GetChildren() []*MenuTreeAuth {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *MenuTreeAuth) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type MenuTreeMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	IsLink        bool                   `protobuf:"varint,2,opt,name=isLink,proto3" json:"isLink,omitempty"`
	IsHide        bool                   `protobuf:"varint,3,opt,name=isHide,proto3" json:"isHide,omitempty"`
	IsKeepAlive   bool                   `protobuf:"varint,4,opt,name=isKeepAlive,proto3" json:"isKeepAlive,omitempty"`
	IsAffix       bool                   `protobuf:"varint,5,opt,name=isAffix,proto3" json:"isAffix,omitempty"`
	IsIframe      bool                   `protobuf:"varint,6,opt,name=isIframe,proto3" json:"isIframe,omitempty"`
	Auth          []string               `protobuf:"bytes,7,rep,name=auth,proto3" json:"auth,omitempty"`
	Icon          string                 `protobuf:"bytes,8,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuTreeMeta) Reset() {
	*x = MenuTreeMeta{}
	mi := &file_base_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuTreeMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuTreeMeta) ProtoMessage() {}

func (x *MenuTreeMeta) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuTreeMeta.ProtoReflect.Descriptor instead.
func (*MenuTreeMeta) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{5}
}

func (x *MenuTreeMeta) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MenuTreeMeta) GetIsLink() bool {
	if x != nil {
		return x.IsLink
	}
	return false
}

func (x *MenuTreeMeta) GetIsHide() bool {
	if x != nil {
		return x.IsHide
	}
	return false
}

func (x *MenuTreeMeta) GetIsKeepAlive() bool {
	if x != nil {
		return x.IsKeepAlive
	}
	return false
}

func (x *MenuTreeMeta) GetIsAffix() bool {
	if x != nil {
		return x.IsAffix
	}
	return false
}

func (x *MenuTreeMeta) GetIsIframe() bool {
	if x != nil {
		return x.IsIframe
	}
	return false
}

func (x *MenuTreeMeta) GetAuth() []string {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *MenuTreeMeta) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type MenuTree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuId        int64                  `protobuf:"varint,1,opt,name=menuId,proto3" json:"menuId,omitempty"`
	MenuName      string                 `protobuf:"bytes,2,opt,name=menuName,proto3" json:"menuName,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	ParentId      int64                  `protobuf:"varint,4,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Sort          int32                  `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`
	Icon          string                 `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty"`
	Path          string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	Component     string                 `protobuf:"bytes,8,opt,name=component,proto3" json:"component,omitempty"`
	IsIframe      int32                  `protobuf:"varint,9,opt,name=isIframe,proto3" json:"isIframe,omitempty"`
	IsLink        string                 `protobuf:"bytes,10,opt,name=isLink,proto3" json:"isLink,omitempty"`
	MenuType      string                 `protobuf:"bytes,11,opt,name=menuType,proto3" json:"menuType,omitempty"`
	IsHide        int32                  `protobuf:"varint,12,opt,name=isHide,proto3" json:"isHide,omitempty"`
	IsKeepAlive   int32                  `protobuf:"varint,13,opt,name=isKeepAlive,proto3" json:"isKeepAlive,omitempty"`
	IsAffix       int32                  `protobuf:"varint,14,opt,name=isAffix,proto3" json:"isAffix,omitempty"`
	Permission    string                 `protobuf:"bytes,15,opt,name=permission,proto3" json:"permission,omitempty"`
	Status        int32                  `protobuf:"varint,16,opt,name=status,proto3" json:"status,omitempty"`
	CreateBy      string                 `protobuf:"bytes,17,opt,name=createBy,proto3" json:"createBy,omitempty"`
	UpdateBy      string                 `protobuf:"bytes,18,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
	Remark        string                 `protobuf:"bytes,19,opt,name=remark,proto3" json:"remark,omitempty"`
	Children      []*MenuTree            `protobuf:"bytes,20,rep,name=children,proto3" json:"children,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuTree) Reset() {
	*x = MenuTree{}
	mi := &file_base_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuTree) ProtoMessage() {}

func (x *MenuTree) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuTree.ProtoReflect.Descriptor instead.
func (*MenuTree) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{6}
}

func (x *MenuTree) GetMenuId() int64 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

func (x *MenuTree) GetMenuName() string {
	if x != nil {
		return x.MenuName
	}
	return ""
}

func (x *MenuTree) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MenuTree) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *MenuTree) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *MenuTree) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *MenuTree) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MenuTree) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *MenuTree) GetIsIframe() int32 {
	if x != nil {
		return x.IsIframe
	}
	return 0
}

func (x *MenuTree) GetIsLink() string {
	if x != nil {
		return x.IsLink
	}
	return ""
}

func (x *MenuTree) GetMenuType() string {
	if x != nil {
		return x.MenuType
	}
	return ""
}

func (x *MenuTree) GetIsHide() int32 {
	if x != nil {
		return x.IsHide
	}
	return 0
}

func (x *MenuTree) GetIsKeepAlive() int32 {
	if x != nil {
		return x.IsKeepAlive
	}
	return 0
}

func (x *MenuTree) GetIsAffix() int32 {
	if x != nil {
		return x.IsAffix
	}
	return 0
}

func (x *MenuTree) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *MenuTree) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MenuTree) GetCreateBy() string {
	if x != nil {
		return x.CreateBy
	}
	return ""
}

func (x *MenuTree) GetUpdateBy() string {
	if x != nil {
		return x.UpdateBy
	}
	return ""
}

func (x *MenuTree) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *MenuTree) GetChildren() []*MenuTree {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *MenuTree) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *MenuTree) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type SimpleMenu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuId        int64                  `protobuf:"varint,1,opt,name=menuId,proto3" json:"menuId,omitempty"`
	MenuName      string                 `protobuf:"bytes,2,opt,name=menuName,proto3" json:"menuName,omitempty"`
	Children      []*SimpleMenu          `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleMenu) Reset() {
	*x = SimpleMenu{}
	mi := &file_base_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleMenu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleMenu) ProtoMessage() {}

func (x *SimpleMenu) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleMenu.ProtoReflect.Descriptor instead.
func (*SimpleMenu) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{7}
}

func (x *SimpleMenu) GetMenuId() int64 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

func (x *SimpleMenu) GetMenuName() string {
	if x != nil {
		return x.MenuName
	}
	return ""
}

func (x *SimpleMenu) GetChildren() []*SimpleMenu {
	if x != nil {
		return x.Children
	}
	return nil
}

type UserData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	NickName      string                 `protobuf:"bytes,3,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	RoleId        int32                  `protobuf:"varint,5,opt,name=roleId,proto3" json:"roleId,omitempty"`
	Salt          string                 `protobuf:"bytes,6,opt,name=salt,proto3" json:"salt,omitempty"`
	Avatar        string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Sex           int64                  `protobuf:"varint,8,opt,name=sex,proto3" json:"sex,omitempty"`
	Email         string                 `protobuf:"bytes,9,opt,name=email,proto3" json:"email,omitempty"`
	DeptId        int32                  `protobuf:"varint,10,opt,name=deptId,proto3" json:"deptId,omitempty"`
	PostId        int32                  `protobuf:"varint,11,opt,name=postId,proto3" json:"postId,omitempty"`
	RoleIds       string                 `protobuf:"bytes,12,opt,name=roleIds,proto3" json:"roleIds,omitempty"`
	PostIds       string                 `protobuf:"bytes,13,opt,name=postIds,proto3" json:"postIds,omitempty"`
	CreateBy      string                 `protobuf:"bytes,14,opt,name=createBy,proto3" json:"createBy,omitempty"`
	UpdateBy      string                 `protobuf:"bytes,15,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
	Remark        string                 `protobuf:"bytes,16,opt,name=remark,proto3" json:"remark,omitempty"`
	Status        int32                  `protobuf:"varint,17,opt,name=status,proto3" json:"status,omitempty"`
	Username      string                 `protobuf:"bytes,18,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,19,opt,name=password,proto3" json:"password,omitempty"`
	RoleName      string                 `protobuf:"bytes,20,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	DeptName      string                 `protobuf:"bytes,21,opt,name=dept_name,json=deptName,proto3" json:"dept_name,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,23,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	Secret        string                 `protobuf:"bytes,24,opt,name=secret,proto3" json:"secret,omitempty"`
	Qrcode        string                 `protobuf:"bytes,25,opt,name=qrcode,proto3" json:"qrcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserData) Reset() {
	*x = UserData{}
	mi := &file_base_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{8}
}

func (x *UserData) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserData) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *UserData) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserData) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *UserData) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

func (x *UserData) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserData) GetSex() int64 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *UserData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserData) GetDeptId() int32 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

func (x *UserData) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *UserData) GetRoleIds() string {
	if x != nil {
		return x.RoleIds
	}
	return ""
}

func (x *UserData) GetPostIds() string {
	if x != nil {
		return x.PostIds
	}
	return ""
}

func (x *UserData) GetCreateBy() string {
	if x != nil {
		return x.CreateBy
	}
	return ""
}

func (x *UserData) GetUpdateBy() string {
	if x != nil {
		return x.UpdateBy
	}
	return ""
}

func (x *UserData) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *UserData) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserData) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserData) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *UserData) GetDeptName() string {
	if x != nil {
		return x.DeptName
	}
	return ""
}

func (x *UserData) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *UserData) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *UserData) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *UserData) GetQrcode() string {
	if x != nil {
		return x.Qrcode
	}
	return ""
}

type PostData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	PostName      string                 `protobuf:"bytes,3,opt,name=postName,proto3" json:"postName,omitempty"`
	PostCode      string                 `protobuf:"bytes,4,opt,name=postCode,proto3" json:"postCode,omitempty"`
	Sort          int32                  `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Remark        string                 `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	CreateBy      string                 `protobuf:"bytes,8,opt,name=createBy,proto3" json:"createBy,omitempty"`
	UpdateBy      string                 `protobuf:"bytes,9,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostData) Reset() {
	*x = PostData{}
	mi := &file_base_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostData) ProtoMessage() {}

func (x *PostData) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostData.ProtoReflect.Descriptor instead.
func (*PostData) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{9}
}

func (x *PostData) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PostData) GetPostName() string {
	if x != nil {
		return x.PostName
	}
	return ""
}

func (x *PostData) GetPostCode() string {
	if x != nil {
		return x.PostCode
	}
	return ""
}

func (x *PostData) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *PostData) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PostData) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *PostData) GetCreateBy() string {
	if x != nil {
		return x.CreateBy
	}
	return ""
}

func (x *PostData) GetUpdateBy() string {
	if x != nil {
		return x.UpdateBy
	}
	return ""
}

func (x *PostData) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *PostData) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type DeptData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Children      []*DeptData            `protobuf:"bytes,1,rep,name=children,proto3" json:"children,omitempty"`
	DeptId        int64                  `protobuf:"varint,2,opt,name=deptId,proto3" json:"deptId,omitempty"`
	DeptName      string                 `protobuf:"bytes,3,opt,name=deptName,proto3" json:"deptName,omitempty"`
	DeptPath      string                 `protobuf:"bytes,4,opt,name=deptPath,proto3" json:"deptPath,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Leader        string                 `protobuf:"bytes,6,opt,name=leader,proto3" json:"leader,omitempty"`
	ParentId      int64                  `protobuf:"varint,7,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Phone         string                 `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`
	Short         int32                  `protobuf:"varint,9,opt,name=short,proto3" json:"short,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	CreateBy      string                 `protobuf:"bytes,11,opt,name=createBy,proto3" json:"createBy,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeptData) Reset() {
	*x = DeptData{}
	mi := &file_base_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeptData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptData) ProtoMessage() {}

func (x *DeptData) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptData.ProtoReflect.Descriptor instead.
func (*DeptData) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{10}
}

func (x *DeptData) GetChildren() []*DeptData {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *DeptData) GetDeptId() int64 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

func (x *DeptData) GetDeptName() string {
	if x != nil {
		return x.DeptName
	}
	return ""
}

func (x *DeptData) GetDeptPath() string {
	if x != nil {
		return x.DeptPath
	}
	return ""
}

func (x *DeptData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DeptData) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

func (x *DeptData) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *DeptData) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *DeptData) GetShort() int32 {
	if x != nil {
		return x.Short
	}
	return 0
}

func (x *DeptData) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeptData) GetCreateBy() string {
	if x != nil {
		return x.CreateBy
	}
	return ""
}

func (x *DeptData) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *DeptData) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// 敏感词信息
type SensitiveInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Word          string                 `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensitiveInfo) Reset() {
	*x = SensitiveInfo{}
	mi := &file_base_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensitiveInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensitiveInfo) ProtoMessage() {}

func (x *SensitiveInfo) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensitiveInfo.ProtoReflect.Descriptor instead.
func (*SensitiveInfo) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{11}
}

func (x *SensitiveInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SensitiveInfo) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *SensitiveInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SensitiveInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UserInfo struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	UserID           string                      `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Nickname         string                      `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	FaceURL          string                      `protobuf:"bytes,3,opt,name=faceURL,proto3" json:"faceURL,omitempty"`
	Gender           int32                       `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`
	PhoneNumber      string                      `protobuf:"bytes,5,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Email            string                      `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Motto            string                      `protobuf:"bytes,8,opt,name=motto,proto3" json:"motto,omitempty"`
	Platform         uint32                      `protobuf:"varint,9,opt,name=platform,proto3" json:"platform,omitempty"`
	Birth            *timestamppb.Timestamp      `protobuf:"bytes,10,opt,name=birth,proto3" json:"birth,omitempty"`
	CreateTime       *timestamppb.Timestamp      `protobuf:"bytes,11,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Account          string                      `protobuf:"bytes,12,opt,name=account,proto3" json:"account,omitempty"`
	Level            int32                       `protobuf:"varint,13,opt,name=level,proto3" json:"level,omitempty"`
	LastLoginIp      string                      `protobuf:"bytes,14,opt,name=lastLoginIp,proto3" json:"lastLoginIp,omitempty"`
	FriendCount      int32                       `protobuf:"varint,15,opt,name=friendCount,proto3" json:"friendCount,omitempty"`
	GroupCount       int32                       `protobuf:"varint,16,opt,name=groupCount,proto3" json:"groupCount,omitempty"`
	Status           int32                       `protobuf:"varint,17,opt,name=status,proto3" json:"status,omitempty"`
	LastLoginTime    *timestamppb.Timestamp      `protobuf:"bytes,18,opt,name=lastLoginTime,proto3" json:"lastLoginTime,omitempty"`
	FunctionStatus   *UserInfoFunctionStatusList `protobuf:"bytes,20,opt,name=functionStatus,proto3" json:"functionStatus,omitempty"`
	IpList           *UserInfoIpItemSet          `protobuf:"bytes,21,opt,name=ipList,proto3" json:"ipList,omitempty"`
	AllowAddFriend   int32                       `protobuf:"varint,22,opt,name=allowAddFriend,proto3" json:"allowAddFriend,omitempty"`
	AllowCreateGroup int32                       `protobuf:"varint,23,opt,name=allowCreateGroup,proto3" json:"allowCreateGroup,omitempty"`
	GroupMute        int32                       `protobuf:"varint,24,opt,name=groupMute,proto3" json:"groupMute,omitempty"`
	FriendMute       int32                       `protobuf:"varint,25,opt,name=friendMute,proto3" json:"friendMute,omitempty"`
	IsInIpWhiteList  int32                       `protobuf:"varint,26,opt,name=isInIpWhiteList,proto3" json:"isInIpWhiteList,omitempty"`
	FreezeAt         *timestamppb.Timestamp      `protobuf:"bytes,27,opt,name=freezeAt,proto3" json:"freezeAt,omitempty"`
	FreezeBy         string                      `protobuf:"bytes,28,opt,name=freezeBy,proto3" json:"freezeBy,omitempty"`
	FreezeRemark     string                      `protobuf:"bytes,29,opt,name=freezeRemark,proto3" json:"freezeRemark,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_base_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{12}
}

func (x *UserInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetFaceURL() string {
	if x != nil {
		return x.FaceURL
	}
	return ""
}

func (x *UserInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserInfo) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetMotto() string {
	if x != nil {
		return x.Motto
	}
	return ""
}

func (x *UserInfo) GetPlatform() uint32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *UserInfo) GetBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.Birth
	}
	return nil
}

func (x *UserInfo) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *UserInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *UserInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserInfo) GetLastLoginIp() string {
	if x != nil {
		return x.LastLoginIp
	}
	return ""
}

func (x *UserInfo) GetFriendCount() int32 {
	if x != nil {
		return x.FriendCount
	}
	return 0
}

func (x *UserInfo) GetGroupCount() int32 {
	if x != nil {
		return x.GroupCount
	}
	return 0
}

func (x *UserInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserInfo) GetLastLoginTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoginTime
	}
	return nil
}

func (x *UserInfo) GetFunctionStatus() *UserInfoFunctionStatusList {
	if x != nil {
		return x.FunctionStatus
	}
	return nil
}

func (x *UserInfo) GetIpList() *UserInfoIpItemSet {
	if x != nil {
		return x.IpList
	}
	return nil
}

func (x *UserInfo) GetAllowAddFriend() int32 {
	if x != nil {
		return x.AllowAddFriend
	}
	return 0
}

func (x *UserInfo) GetAllowCreateGroup() int32 {
	if x != nil {
		return x.AllowCreateGroup
	}
	return 0
}

func (x *UserInfo) GetGroupMute() int32 {
	if x != nil {
		return x.GroupMute
	}
	return 0
}

func (x *UserInfo) GetFriendMute() int32 {
	if x != nil {
		return x.FriendMute
	}
	return 0
}

func (x *UserInfo) GetIsInIpWhiteList() int32 {
	if x != nil {
		return x.IsInIpWhiteList
	}
	return 0
}

func (x *UserInfo) GetFreezeAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FreezeAt
	}
	return nil
}

func (x *UserInfo) GetFreezeBy() string {
	if x != nil {
		return x.FreezeBy
	}
	return ""
}

func (x *UserInfo) GetFreezeRemark() string {
	if x != nil {
		return x.FreezeRemark
	}
	return ""
}

type UserInfoFunctionStatusList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupMute     int32                  `protobuf:"varint,1,opt,name=groupMute,proto3" json:"groupMute,omitempty"`         //群组禁言
	FriendMute    int32                  `protobuf:"varint,2,opt,name=friendMute,proto3" json:"friendMute,omitempty"`       //私聊禁言
	CreateGroup   int32                  `protobuf:"varint,3,opt,name=createGroup,proto3" json:"createGroup,omitempty"`     //禁止创建群聊
	AddFriend     int32                  `protobuf:"varint,4,opt,name=addFriend,proto3" json:"addFriend,omitempty"`         //禁止添加好友
	FreezeAccount int32                  `protobuf:"varint,5,opt,name=freezeAccount,proto3" json:"freezeAccount,omitempty"` //冻结帐户
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoFunctionStatusList) Reset() {
	*x = UserInfoFunctionStatusList{}
	mi := &file_base_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoFunctionStatusList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoFunctionStatusList) ProtoMessage() {}

func (x *UserInfoFunctionStatusList) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoFunctionStatusList.ProtoReflect.Descriptor instead.
func (*UserInfoFunctionStatusList) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{12, 0}
}

func (x *UserInfoFunctionStatusList) GetGroupMute() int32 {
	if x != nil {
		return x.GroupMute
	}
	return 0
}

func (x *UserInfoFunctionStatusList) GetFriendMute() int32 {
	if x != nil {
		return x.FriendMute
	}
	return 0
}

func (x *UserInfoFunctionStatusList) GetCreateGroup() int32 {
	if x != nil {
		return x.CreateGroup
	}
	return 0
}

func (x *UserInfoFunctionStatusList) GetAddFriend() int32 {
	if x != nil {
		return x.AddFriend
	}
	return 0
}

func (x *UserInfoFunctionStatusList) GetFreezeAccount() int32 {
	if x != nil {
		return x.FreezeAccount
	}
	return 0
}

type UserInfoIpItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`                      //ip
	IsProhibited  int32                  `protobuf:"varint,2,opt,name=isProhibited,proto3" json:"isProhibited,omitempty"` //是否已封禁
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoIpItem) Reset() {
	*x = UserInfoIpItem{}
	mi := &file_base_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoIpItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoIpItem) ProtoMessage() {}

func (x *UserInfoIpItem) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoIpItem.ProtoReflect.Descriptor instead.
func (*UserInfoIpItem) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{12, 1}
}

func (x *UserInfoIpItem) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *UserInfoIpItem) GetIsProhibited() int32 {
	if x != nil {
		return x.IsProhibited
	}
	return 0
}

type UserInfoIpItemSet struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	IpItem               []*UserInfoIpItem      `protobuf:"bytes,1,rep,name=ipItem,proto3" json:"ipItem,omitempty"`
	IsMultiTerminalLogin int32                  `protobuf:"varint,2,opt,name=isMultiTerminalLogin,proto3" json:"isMultiTerminalLogin,omitempty"` //是否多端登录
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UserInfoIpItemSet) Reset() {
	*x = UserInfoIpItemSet{}
	mi := &file_base_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoIpItemSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoIpItemSet) ProtoMessage() {}

func (x *UserInfoIpItemSet) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoIpItemSet.ProtoReflect.Descriptor instead.
func (*UserInfoIpItemSet) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{12, 2}
}

func (x *UserInfoIpItemSet) GetIpItem() []*UserInfoIpItem {
	if x != nil {
		return x.IpItem
	}
	return nil
}

func (x *UserInfoIpItemSet) GetIsMultiTerminalLogin() int32 {
	if x != nil {
		return x.IsMultiTerminalLogin
	}
	return 0
}

var File_base_proto protoreflect.FileDescriptor

const file_base_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"base.proto\x12\fapi.admin.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"5\n" +
	"\aApiBase\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\"\xca\x03\n" +
	"\bDeptTree\x12\x16\n" +
	"\x06deptId\x18\x01 \x01(\x03R\x06deptId\x12\x1a\n" +
	"\bparentId\x18\x03 \x01(\x03R\bparentId\x12\x1a\n" +
	"\bdeptPath\x18\x04 \x01(\tR\bdeptPath\x12\x1a\n" +
	"\bdeptName\x18\x05 \x01(\tR\bdeptName\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\x05R\x04sort\x12\x16\n" +
	"\x06leader\x18\a \x01(\tR\x06leader\x12\x14\n" +
	"\x05phone\x18\b \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\t \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12\x1a\n" +
	"\bcreateBy\x18\v \x01(\tR\bcreateBy\x12\x1a\n" +
	"\bupdateBy\x18\f \x01(\tR\bupdateBy\x122\n" +
	"\bchildren\x18\r \x03(\v2\x16.api.admin.v1.DeptTreeR\bchildren\x12:\n" +
	"\n" +
	"createTime\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12:\n" +
	"\n" +
	"updateTime\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"\x8c\x03\n" +
	"\bRoleData\x12\x16\n" +
	"\x06roleId\x18\x01 \x01(\x03R\x06roleId\x12\x1a\n" +
	"\broleName\x18\x02 \x01(\tR\broleName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x18\n" +
	"\aroleKey\x18\x04 \x01(\tR\aroleKey\x12\x1a\n" +
	"\broleSort\x18\x05 \x01(\x05R\broleSort\x12\x1c\n" +
	"\tdataScope\x18\x06 \x01(\x03R\tdataScope\x12\x1a\n" +
	"\bcreateBy\x18\a \x01(\tR\bcreateBy\x12\x1a\n" +
	"\bupdateBy\x18\b \x01(\tR\bupdateBy\x12\x16\n" +
	"\x06remark\x18\t \x01(\tR\x06remark\x12\x18\n" +
	"\amenuIds\x18\n" +
	" \x03(\x05R\amenuIds\x12:\n" +
	"\n" +
	"createTime\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12:\n" +
	"\n" +
	"updateTime\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"\xfb\x01\n" +
	"\aApiData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bapiGroup\x18\x04 \x01(\tR\bapiGroup\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12:\n" +
	"\n" +
	"createTime\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12:\n" +
	"\n" +
	"updateTime\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"\xf4\x01\n" +
	"\fMenuTreeAuth\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1a\n" +
	"\bredirect\x18\x03 \x01(\tR\bredirect\x12\x1c\n" +
	"\tcomponent\x18\x04 \x01(\tR\tcomponent\x12.\n" +
	"\x04meta\x18\x05 \x01(\v2\x1a.api.admin.v1.MenuTreeMetaR\x04meta\x126\n" +
	"\bchildren\x18\x06 \x03(\v2\x1a.api.admin.v1.MenuTreeAuthR\bchildren\x12\x1a\n" +
	"\bparentId\x18\a \x01(\x03R\bparentId\"\xd4\x01\n" +
	"\fMenuTreeMeta\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06isLink\x18\x02 \x01(\bR\x06isLink\x12\x16\n" +
	"\x06isHide\x18\x03 \x01(\bR\x06isHide\x12 \n" +
	"\visKeepAlive\x18\x04 \x01(\bR\visKeepAlive\x12\x18\n" +
	"\aisAffix\x18\x05 \x01(\bR\aisAffix\x12\x1a\n" +
	"\bisIframe\x18\x06 \x01(\bR\bisIframe\x12\x12\n" +
	"\x04auth\x18\a \x03(\tR\x04auth\x12\x12\n" +
	"\x04icon\x18\b \x01(\tR\x04icon\"\xa2\x05\n" +
	"\bMenuTree\x12\x16\n" +
	"\x06menuId\x18\x01 \x01(\x03R\x06menuId\x12\x1a\n" +
	"\bmenuName\x18\x02 \x01(\tR\bmenuName\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bparentId\x18\x04 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\x05R\x04sort\x12\x12\n" +
	"\x04icon\x18\x06 \x01(\tR\x04icon\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x12\x1c\n" +
	"\tcomponent\x18\b \x01(\tR\tcomponent\x12\x1a\n" +
	"\bisIframe\x18\t \x01(\x05R\bisIframe\x12\x16\n" +
	"\x06isLink\x18\n" +
	" \x01(\tR\x06isLink\x12\x1a\n" +
	"\bmenuType\x18\v \x01(\tR\bmenuType\x12\x16\n" +
	"\x06isHide\x18\f \x01(\x05R\x06isHide\x12 \n" +
	"\visKeepAlive\x18\r \x01(\x05R\visKeepAlive\x12\x18\n" +
	"\aisAffix\x18\x0e \x01(\x05R\aisAffix\x12\x1e\n" +
	"\n" +
	"permission\x18\x0f \x01(\tR\n" +
	"permission\x12\x16\n" +
	"\x06status\x18\x10 \x01(\x05R\x06status\x12\x1a\n" +
	"\bcreateBy\x18\x11 \x01(\tR\bcreateBy\x12\x1a\n" +
	"\bupdateBy\x18\x12 \x01(\tR\bupdateBy\x12\x16\n" +
	"\x06remark\x18\x13 \x01(\tR\x06remark\x122\n" +
	"\bchildren\x18\x14 \x03(\v2\x16.api.admin.v1.MenuTreeR\bchildren\x12:\n" +
	"\n" +
	"createTime\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12:\n" +
	"\n" +
	"updateTime\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"v\n" +
	"\n" +
	"SimpleMenu\x12\x16\n" +
	"\x06menuId\x18\x01 \x01(\x03R\x06menuId\x12\x1a\n" +
	"\bmenuName\x18\x02 \x01(\tR\bmenuName\x124\n" +
	"\bchildren\x18\x03 \x03(\v2\x18.api.admin.v1.SimpleMenuR\bchildren\"\xa6\x05\n" +
	"\bUserData\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickName\x18\x03 \x01(\tR\bnickName\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x16\n" +
	"\x06roleId\x18\x05 \x01(\x05R\x06roleId\x12\x12\n" +
	"\x04salt\x18\x06 \x01(\tR\x04salt\x12\x16\n" +
	"\x06avatar\x18\a \x01(\tR\x06avatar\x12\x10\n" +
	"\x03sex\x18\b \x01(\x03R\x03sex\x12\x14\n" +
	"\x05email\x18\t \x01(\tR\x05email\x12\x16\n" +
	"\x06deptId\x18\n" +
	" \x01(\x05R\x06deptId\x12\x16\n" +
	"\x06postId\x18\v \x01(\x05R\x06postId\x12\x18\n" +
	"\aroleIds\x18\f \x01(\tR\aroleIds\x12\x18\n" +
	"\apostIds\x18\r \x01(\tR\apostIds\x12\x1a\n" +
	"\bcreateBy\x18\x0e \x01(\tR\bcreateBy\x12\x1a\n" +
	"\bupdateBy\x18\x0f \x01(\tR\bupdateBy\x12\x16\n" +
	"\x06remark\x18\x10 \x01(\tR\x06remark\x12\x16\n" +
	"\x06status\x18\x11 \x01(\x05R\x06status\x12\x1a\n" +
	"\busername\x18\x12 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x13 \x01(\tR\bpassword\x12\x1b\n" +
	"\trole_name\x18\x14 \x01(\tR\broleName\x12\x1b\n" +
	"\tdept_name\x18\x15 \x01(\tR\bdeptName\x12:\n" +
	"\n" +
	"createTime\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12:\n" +
	"\n" +
	"updateTime\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12\x16\n" +
	"\x06secret\x18\x18 \x01(\tR\x06secret\x12\x16\n" +
	"\x06qrcode\x18\x19 \x01(\tR\x06qrcode\"\xce\x02\n" +
	"\bPostData\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x03R\x06postId\x12\x1a\n" +
	"\bpostName\x18\x03 \x01(\tR\bpostName\x12\x1a\n" +
	"\bpostCode\x18\x04 \x01(\tR\bpostCode\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\x05R\x04sort\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x16\n" +
	"\x06remark\x18\a \x01(\tR\x06remark\x12\x1a\n" +
	"\bcreateBy\x18\b \x01(\tR\bcreateBy\x12\x1a\n" +
	"\bupdateBy\x18\t \x01(\tR\bupdateBy\x12:\n" +
	"\n" +
	"createTime\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12:\n" +
	"\n" +
	"updateTime\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"\xb0\x03\n" +
	"\bDeptData\x122\n" +
	"\bchildren\x18\x01 \x03(\v2\x16.api.admin.v1.DeptDataR\bchildren\x12\x16\n" +
	"\x06deptId\x18\x02 \x01(\x03R\x06deptId\x12\x1a\n" +
	"\bdeptName\x18\x03 \x01(\tR\bdeptName\x12\x1a\n" +
	"\bdeptPath\x18\x04 \x01(\tR\bdeptPath\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x16\n" +
	"\x06leader\x18\x06 \x01(\tR\x06leader\x12\x1a\n" +
	"\bparentId\x18\a \x01(\x03R\bparentId\x12\x14\n" +
	"\x05phone\x18\b \x01(\tR\x05phone\x12\x14\n" +
	"\x05short\x18\t \x01(\x05R\x05short\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12\x1a\n" +
	"\bcreateBy\x18\v \x01(\tR\bcreateBy\x12:\n" +
	"\n" +
	"createTime\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12:\n" +
	"\n" +
	"updateTime\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"\x85\x01\n" +
	"\rSensitiveInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04word\x18\x02 \x01(\tR\x04word\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x128\n" +
	"\tcreatedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xe8\n" +
	"\n" +
	"\bUserInfo\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x18\n" +
	"\afaceURL\x18\x03 \x01(\tR\afaceURL\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\x05R\x06gender\x12 \n" +
	"\vphoneNumber\x18\x05 \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x14\n" +
	"\x05motto\x18\b \x01(\tR\x05motto\x12\x1a\n" +
	"\bplatform\x18\t \x01(\rR\bplatform\x120\n" +
	"\x05birth\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x05birth\x12:\n" +
	"\n" +
	"createTime\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12\x18\n" +
	"\aaccount\x18\f \x01(\tR\aaccount\x12\x14\n" +
	"\x05level\x18\r \x01(\x05R\x05level\x12 \n" +
	"\vlastLoginIp\x18\x0e \x01(\tR\vlastLoginIp\x12 \n" +
	"\vfriendCount\x18\x0f \x01(\x05R\vfriendCount\x12\x1e\n" +
	"\n" +
	"groupCount\x18\x10 \x01(\x05R\n" +
	"groupCount\x12\x16\n" +
	"\x06status\x18\x11 \x01(\x05R\x06status\x12@\n" +
	"\rlastLoginTime\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\rlastLoginTime\x12Q\n" +
	"\x0efunctionStatus\x18\x14 \x01(\v2).api.admin.v1.UserInfo.functionStatusListR\x0efunctionStatus\x128\n" +
	"\x06ipList\x18\x15 \x01(\v2 .api.admin.v1.UserInfo.ipItemSetR\x06ipList\x12&\n" +
	"\x0eallowAddFriend\x18\x16 \x01(\x05R\x0eallowAddFriend\x12*\n" +
	"\x10allowCreateGroup\x18\x17 \x01(\x05R\x10allowCreateGroup\x12\x1c\n" +
	"\tgroupMute\x18\x18 \x01(\x05R\tgroupMute\x12\x1e\n" +
	"\n" +
	"friendMute\x18\x19 \x01(\x05R\n" +
	"friendMute\x12(\n" +
	"\x0fisInIpWhiteList\x18\x1a \x01(\x05R\x0fisInIpWhiteList\x126\n" +
	"\bfreezeAt\x18\x1b \x01(\v2\x1a.google.protobuf.TimestampR\bfreezeAt\x12\x1a\n" +
	"\bfreezeBy\x18\x1c \x01(\tR\bfreezeBy\x12\"\n" +
	"\ffreezeRemark\x18\x1d \x01(\tR\ffreezeRemark\x1a\xb8\x01\n" +
	"\x12functionStatusList\x12\x1c\n" +
	"\tgroupMute\x18\x01 \x01(\x05R\tgroupMute\x12\x1e\n" +
	"\n" +
	"friendMute\x18\x02 \x01(\x05R\n" +
	"friendMute\x12 \n" +
	"\vcreateGroup\x18\x03 \x01(\x05R\vcreateGroup\x12\x1c\n" +
	"\taddFriend\x18\x04 \x01(\x05R\taddFriend\x12$\n" +
	"\rfreezeAccount\x18\x05 \x01(\x05R\rfreezeAccount\x1a<\n" +
	"\x06ipItem\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\"\n" +
	"\fisProhibited\x18\x02 \x01(\x05R\fisProhibited\x1av\n" +
	"\tipItemSet\x125\n" +
	"\x06ipItem\x18\x01 \x03(\v2\x1d.api.admin.v1.UserInfo.ipItemR\x06ipItem\x122\n" +
	"\x14isMultiTerminalLogin\x18\x02 \x01(\x05R\x14isMultiTerminalLoginB>Z<https://github.com/swordkee/kratos-vue-admin/api/admin/v1;v1b\x06proto3"

var (
	file_base_proto_rawDescOnce sync.Once
	file_base_proto_rawDescData []byte
)

func file_base_proto_rawDescGZIP() []byte {
	file_base_proto_rawDescOnce.Do(func() {
		file_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_proto_rawDesc), len(file_base_proto_rawDesc)))
	})
	return file_base_proto_rawDescData
}

var file_base_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_base_proto_goTypes = []any{
	(*ApiBase)(nil),                    // 0: api.admin.v1.ApiBase
	(*DeptTree)(nil),                   // 1: api.admin.v1.DeptTree
	(*RoleData)(nil),                   // 2: api.admin.v1.RoleData
	(*ApiData)(nil),                    // 3: api.admin.v1.ApiData
	(*MenuTreeAuth)(nil),               // 4: api.admin.v1.MenuTreeAuth
	(*MenuTreeMeta)(nil),               // 5: api.admin.v1.MenuTreeMeta
	(*MenuTree)(nil),                   // 6: api.admin.v1.MenuTree
	(*SimpleMenu)(nil),                 // 7: api.admin.v1.SimpleMenu
	(*UserData)(nil),                   // 8: api.admin.v1.UserData
	(*PostData)(nil),                   // 9: api.admin.v1.PostData
	(*DeptData)(nil),                   // 10: api.admin.v1.DeptData
	(*SensitiveInfo)(nil),              // 11: api.admin.v1.SensitiveInfo
	(*UserInfo)(nil),                   // 12: api.admin.v1.UserInfo
	(*UserInfoFunctionStatusList)(nil), // 13: api.admin.v1.UserInfo.functionStatusList
	(*UserInfoIpItem)(nil),             // 14: api.admin.v1.UserInfo.ipItem
	(*UserInfoIpItemSet)(nil),          // 15: api.admin.v1.UserInfo.ipItemSet
	(*timestamppb.Timestamp)(nil),      // 16: google.protobuf.Timestamp
}
var file_base_proto_depIdxs = []int32{
	1,  // 0: api.admin.v1.DeptTree.children:type_name -> api.admin.v1.DeptTree
	16, // 1: api.admin.v1.DeptTree.createTime:type_name -> google.protobuf.Timestamp
	16, // 2: api.admin.v1.DeptTree.updateTime:type_name -> google.protobuf.Timestamp
	16, // 3: api.admin.v1.RoleData.createTime:type_name -> google.protobuf.Timestamp
	16, // 4: api.admin.v1.RoleData.updateTime:type_name -> google.protobuf.Timestamp
	16, // 5: api.admin.v1.ApiData.createTime:type_name -> google.protobuf.Timestamp
	16, // 6: api.admin.v1.ApiData.updateTime:type_name -> google.protobuf.Timestamp
	5,  // 7: api.admin.v1.MenuTreeAuth.meta:type_name -> api.admin.v1.MenuTreeMeta
	4,  // 8: api.admin.v1.MenuTreeAuth.children:type_name -> api.admin.v1.MenuTreeAuth
	6,  // 9: api.admin.v1.MenuTree.children:type_name -> api.admin.v1.MenuTree
	16, // 10: api.admin.v1.MenuTree.createTime:type_name -> google.protobuf.Timestamp
	16, // 11: api.admin.v1.MenuTree.updateTime:type_name -> google.protobuf.Timestamp
	7,  // 12: api.admin.v1.SimpleMenu.children:type_name -> api.admin.v1.SimpleMenu
	16, // 13: api.admin.v1.UserData.createTime:type_name -> google.protobuf.Timestamp
	16, // 14: api.admin.v1.UserData.updateTime:type_name -> google.protobuf.Timestamp
	16, // 15: api.admin.v1.PostData.createTime:type_name -> google.protobuf.Timestamp
	16, // 16: api.admin.v1.PostData.updateTime:type_name -> google.protobuf.Timestamp
	10, // 17: api.admin.v1.DeptData.children:type_name -> api.admin.v1.DeptData
	16, // 18: api.admin.v1.DeptData.createTime:type_name -> google.protobuf.Timestamp
	16, // 19: api.admin.v1.DeptData.updateTime:type_name -> google.protobuf.Timestamp
	16, // 20: api.admin.v1.SensitiveInfo.createdAt:type_name -> google.protobuf.Timestamp
	16, // 21: api.admin.v1.UserInfo.birth:type_name -> google.protobuf.Timestamp
	16, // 22: api.admin.v1.UserInfo.createTime:type_name -> google.protobuf.Timestamp
	16, // 23: api.admin.v1.UserInfo.lastLoginTime:type_name -> google.protobuf.Timestamp
	13, // 24: api.admin.v1.UserInfo.functionStatus:type_name -> api.admin.v1.UserInfo.functionStatusList
	15, // 25: api.admin.v1.UserInfo.ipList:type_name -> api.admin.v1.UserInfo.ipItemSet
	16, // 26: api.admin.v1.UserInfo.freezeAt:type_name -> google.protobuf.Timestamp
	14, // 27: api.admin.v1.UserInfo.ipItemSet.ipItem:type_name -> api.admin.v1.UserInfo.ipItem
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_base_proto_init() }
func file_base_proto_init() {
	if File_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_proto_rawDesc), len(file_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_proto_goTypes,
		DependencyIndexes: file_base_proto_depIdxs,
		MessageInfos:      file_base_proto_msgTypes,
	}.Build()
	File_base_proto = out.File
	file_base_proto_goTypes = nil
	file_base_proto_depIdxs = nil
}
