// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.14.0
// source: dicttype.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDictTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictName      string                 `protobuf:"bytes,1,opt,name=dictName,proto3" json:"dictName,omitempty"`
	DictType      string                 `protobuf:"bytes,2,opt,name=dictType,proto3" json:"dictType,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Remark        string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDictTypeRequest) Reset() {
	*x = CreateDictTypeRequest{}
	mi := &file_dicttype_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDictTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDictTypeRequest) ProtoMessage() {}

func (x *CreateDictTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dicttype_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDictTypeRequest.ProtoReflect.Descriptor instead.
func (*CreateDictTypeRequest) Descriptor() ([]byte, []int) {
	return file_dicttype_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDictTypeRequest) GetDictName() string {
	if x != nil {
		return x.DictName
	}
	return ""
}

func (x *CreateDictTypeRequest) GetDictType() string {
	if x != nil {
		return x.DictType
	}
	return ""
}

func (x *CreateDictTypeRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateDictTypeRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type CreateDictTypeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDictTypeReply) Reset() {
	*x = CreateDictTypeReply{}
	mi := &file_dicttype_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDictTypeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDictTypeReply) ProtoMessage() {}

func (x *CreateDictTypeReply) ProtoReflect() protoreflect.Message {
	mi := &file_dicttype_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDictTypeReply.ProtoReflect.Descriptor instead.
func (*CreateDictTypeReply) Descriptor() ([]byte, []int) {
	return file_dicttype_proto_rawDescGZIP(), []int{1}
}

type UpdateDictTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictId        uint32                 `protobuf:"varint,1,opt,name=dictId,proto3" json:"dictId,omitempty"`
	DictName      string                 `protobuf:"bytes,2,opt,name=dictName,proto3" json:"dictName,omitempty"`
	DictType      string                 `protobuf:"bytes,3,opt,name=dictType,proto3" json:"dictType,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	CreateBy      string                 `protobuf:"bytes,5,opt,name=createBy,proto3" json:"createBy,omitempty"`
	UpdateBy      string                 `protobuf:"bytes,6,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
	Remark        string                 `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDictTypeRequest) Reset() {
	*x = UpdateDictTypeRequest{}
	mi := &file_dicttype_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDictTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDictTypeRequest) ProtoMessage() {}

func (x *UpdateDictTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dicttype_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDictTypeRequest.ProtoReflect.Descriptor instead.
func (*UpdateDictTypeRequest) Descriptor() ([]byte, []int) {
	return file_dicttype_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateDictTypeRequest) GetDictId() uint32 {
	if x != nil {
		return x.DictId
	}
	return 0
}

func (x *UpdateDictTypeRequest) GetDictName() string {
	if x != nil {
		return x.DictName
	}
	return ""
}

func (x *UpdateDictTypeRequest) GetDictType() string {
	if x != nil {
		return x.DictType
	}
	return ""
}

func (x *UpdateDictTypeRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateDictTypeRequest) GetCreateBy() string {
	if x != nil {
		return x.CreateBy
	}
	return ""
}

func (x *UpdateDictTypeRequest) GetUpdateBy() string {
	if x != nil {
		return x.UpdateBy
	}
	return ""
}

func (x *UpdateDictTypeRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *UpdateDictTypeRequest) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *UpdateDictTypeRequest) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type UpdateDictTypeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictId        int64                  `protobuf:"varint,1,opt,name=dictId,proto3" json:"dictId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDictTypeReply) Reset() {
	*x = UpdateDictTypeReply{}
	mi := &file_dicttype_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDictTypeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDictTypeReply) ProtoMessage() {}

func (x *UpdateDictTypeReply) ProtoReflect() protoreflect.Message {
	mi := &file_dicttype_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDictTypeReply.ProtoReflect.Descriptor instead.
func (*UpdateDictTypeReply) Descriptor() ([]byte, []int) {
	return file_dicttype_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDictTypeReply) GetDictId() int64 {
	if x != nil {
		return x.DictId
	}
	return 0
}

type DeleteDictTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictId        int64                  `protobuf:"varint,1,opt,name=dictId,proto3" json:"dictId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDictTypeRequest) Reset() {
	*x = DeleteDictTypeRequest{}
	mi := &file_dicttype_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDictTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDictTypeRequest) ProtoMessage() {}

func (x *DeleteDictTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dicttype_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDictTypeRequest.ProtoReflect.Descriptor instead.
func (*DeleteDictTypeRequest) Descriptor() ([]byte, []int) {
	return file_dicttype_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteDictTypeRequest) GetDictId() int64 {
	if x != nil {
		return x.DictId
	}
	return 0
}

type DeleteDictTypeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictId        int64                  `protobuf:"varint,1,opt,name=dictId,proto3" json:"dictId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDictTypeReply) Reset() {
	*x = DeleteDictTypeReply{}
	mi := &file_dicttype_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDictTypeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDictTypeReply) ProtoMessage() {}

func (x *DeleteDictTypeReply) ProtoReflect() protoreflect.Message {
	mi := &file_dicttype_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDictTypeReply.ProtoReflect.Descriptor instead.
func (*DeleteDictTypeReply) Descriptor() ([]byte, []int) {
	return file_dicttype_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDictTypeReply) GetDictId() int64 {
	if x != nil {
		return x.DictId
	}
	return 0
}

type GetDictTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictId        int64                  `protobuf:"varint,1,opt,name=dictId,proto3" json:"dictId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDictTypeRequest) Reset() {
	*x = GetDictTypeRequest{}
	mi := &file_dicttype_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDictTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDictTypeRequest) ProtoMessage() {}

func (x *GetDictTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dicttype_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDictTypeRequest.ProtoReflect.Descriptor instead.
func (*GetDictTypeRequest) Descriptor() ([]byte, []int) {
	return file_dicttype_proto_rawDescGZIP(), []int{6}
}

func (x *GetDictTypeRequest) GetDictId() int64 {
	if x != nil {
		return x.DictId
	}
	return 0
}

type GetDictTypeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictId        int64                  `protobuf:"varint,1,opt,name=dictId,proto3" json:"dictId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDictTypeReply) Reset() {
	*x = GetDictTypeReply{}
	mi := &file_dicttype_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDictTypeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDictTypeReply) ProtoMessage() {}

func (x *GetDictTypeReply) ProtoReflect() protoreflect.Message {
	mi := &file_dicttype_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDictTypeReply.ProtoReflect.Descriptor instead.
func (*GetDictTypeReply) Descriptor() ([]byte, []int) {
	return file_dicttype_proto_rawDescGZIP(), []int{7}
}

func (x *GetDictTypeReply) GetDictId() int64 {
	if x != nil {
		return x.DictId
	}
	return 0
}

type ListDictTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictName      string                 `protobuf:"bytes,1,opt,name=dictName,proto3" json:"dictName,omitempty"`
	DictType      string                 `protobuf:"bytes,2,opt,name=dictType,proto3" json:"dictType,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	PageNum       int32                  `protobuf:"varint,4,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDictTypeRequest) Reset() {
	*x = ListDictTypeRequest{}
	mi := &file_dicttype_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDictTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictTypeRequest) ProtoMessage() {}

func (x *ListDictTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dicttype_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictTypeRequest.ProtoReflect.Descriptor instead.
func (*ListDictTypeRequest) Descriptor() ([]byte, []int) {
	return file_dicttype_proto_rawDescGZIP(), []int{8}
}

func (x *ListDictTypeRequest) GetDictName() string {
	if x != nil {
		return x.DictName
	}
	return ""
}

func (x *ListDictTypeRequest) GetDictType() string {
	if x != nil {
		return x.DictType
	}
	return ""
}

func (x *ListDictTypeRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListDictTypeRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListDictTypeRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListDictTypeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	PageNum       int32                  `protobuf:"varint,2,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Data          []*DictTypeContent     `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDictTypeReply) Reset() {
	*x = ListDictTypeReply{}
	mi := &file_dicttype_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDictTypeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictTypeReply) ProtoMessage() {}

func (x *ListDictTypeReply) ProtoReflect() protoreflect.Message {
	mi := &file_dicttype_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictTypeReply.ProtoReflect.Descriptor instead.
func (*ListDictTypeReply) Descriptor() ([]byte, []int) {
	return file_dicttype_proto_rawDescGZIP(), []int{9}
}

func (x *ListDictTypeReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListDictTypeReply) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListDictTypeReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDictTypeReply) GetData() []*DictTypeContent {
	if x != nil {
		return x.Data
	}
	return nil
}

type DictTypeContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictId        uint32                 `protobuf:"varint,1,opt,name=dictId,proto3" json:"dictId,omitempty"`
	DictName      string                 `protobuf:"bytes,2,opt,name=dictName,proto3" json:"dictName,omitempty"`
	DictType      string                 `protobuf:"bytes,3,opt,name=dictType,proto3" json:"dictType,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	CreateBy      string                 `protobuf:"bytes,5,opt,name=createBy,proto3" json:"createBy,omitempty"`
	UpdateBy      string                 `protobuf:"bytes,6,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
	Remark        string                 `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictTypeContent) Reset() {
	*x = DictTypeContent{}
	mi := &file_dicttype_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictTypeContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictTypeContent) ProtoMessage() {}

func (x *DictTypeContent) ProtoReflect() protoreflect.Message {
	mi := &file_dicttype_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictTypeContent.ProtoReflect.Descriptor instead.
func (*DictTypeContent) Descriptor() ([]byte, []int) {
	return file_dicttype_proto_rawDescGZIP(), []int{10}
}

func (x *DictTypeContent) GetDictId() uint32 {
	if x != nil {
		return x.DictId
	}
	return 0
}

func (x *DictTypeContent) GetDictName() string {
	if x != nil {
		return x.DictName
	}
	return ""
}

func (x *DictTypeContent) GetDictType() string {
	if x != nil {
		return x.DictType
	}
	return ""
}

func (x *DictTypeContent) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DictTypeContent) GetCreateBy() string {
	if x != nil {
		return x.CreateBy
	}
	return ""
}

func (x *DictTypeContent) GetUpdateBy() string {
	if x != nil {
		return x.UpdateBy
	}
	return ""
}

func (x *DictTypeContent) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *DictTypeContent) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *DictTypeContent) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type GetDesignateDictTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictIDs       []string               `protobuf:"bytes,1,rep,name=dictIDs,proto3" json:"dictIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDesignateDictTypesRequest) Reset() {
	*x = GetDesignateDictTypesRequest{}
	mi := &file_dicttype_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDesignateDictTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDesignateDictTypesRequest) ProtoMessage() {}

func (x *GetDesignateDictTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dicttype_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDesignateDictTypesRequest.ProtoReflect.Descriptor instead.
func (*GetDesignateDictTypesRequest) Descriptor() ([]byte, []int) {
	return file_dicttype_proto_rawDescGZIP(), []int{11}
}

func (x *GetDesignateDictTypesRequest) GetDictIDs() []string {
	if x != nil {
		return x.DictIDs
	}
	return nil
}

type GetDesignateDictTypesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDesignateDictTypesReply) Reset() {
	*x = GetDesignateDictTypesReply{}
	mi := &file_dicttype_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDesignateDictTypesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDesignateDictTypesReply) ProtoMessage() {}

func (x *GetDesignateDictTypesReply) ProtoReflect() protoreflect.Message {
	mi := &file_dicttype_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDesignateDictTypesReply.ProtoReflect.Descriptor instead.
func (*GetDesignateDictTypesReply) Descriptor() ([]byte, []int) {
	return file_dicttype_proto_rawDescGZIP(), []int{12}
}

var File_dicttype_proto protoreflect.FileDescriptor

const file_dicttype_proto_rawDesc = "" +
	"\n" +
	"\x0edicttype.proto\x12\fapi.admin.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x7f\n" +
	"\x15CreateDictTypeRequest\x12\x1a\n" +
	"\bdictName\x18\x01 \x01(\tR\bdictName\x12\x1a\n" +
	"\bdictType\x18\x02 \x01(\tR\bdictType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\"\x15\n" +
	"\x13CreateDictTypeReply\"\xc7\x02\n" +
	"\x15UpdateDictTypeRequest\x12\x16\n" +
	"\x06dictId\x18\x01 \x01(\rR\x06dictId\x12\x1a\n" +
	"\bdictName\x18\x02 \x01(\tR\bdictName\x12\x1a\n" +
	"\bdictType\x18\x03 \x01(\tR\bdictType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1a\n" +
	"\bcreateBy\x18\x05 \x01(\tR\bcreateBy\x12\x1a\n" +
	"\bupdateBy\x18\x06 \x01(\tR\bupdateBy\x12\x16\n" +
	"\x06remark\x18\a \x01(\tR\x06remark\x12:\n" +
	"\n" +
	"createTime\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12:\n" +
	"\n" +
	"updateTime\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"-\n" +
	"\x13UpdateDictTypeReply\x12\x16\n" +
	"\x06dictId\x18\x01 \x01(\x03R\x06dictId\"/\n" +
	"\x15DeleteDictTypeRequest\x12\x16\n" +
	"\x06dictId\x18\x01 \x01(\x03R\x06dictId\"-\n" +
	"\x13DeleteDictTypeReply\x12\x16\n" +
	"\x06dictId\x18\x01 \x01(\x03R\x06dictId\",\n" +
	"\x12GetDictTypeRequest\x12\x16\n" +
	"\x06dictId\x18\x01 \x01(\x03R\x06dictId\"*\n" +
	"\x10GetDictTypeReply\x12\x16\n" +
	"\x06dictId\x18\x01 \x01(\x03R\x06dictId\"\x9b\x01\n" +
	"\x13ListDictTypeRequest\x12\x1a\n" +
	"\bdictName\x18\x01 \x01(\tR\bdictName\x12\x1a\n" +
	"\bdictType\x18\x02 \x01(\tR\bdictType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x18\n" +
	"\apageNum\x18\x04 \x01(\x05R\apageNum\x12\x1a\n" +
	"\bpageSize\x18\x05 \x01(\x05R\bpageSize\"\x92\x01\n" +
	"\x11ListDictTypeReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x18\n" +
	"\apageNum\x18\x02 \x01(\x05R\apageNum\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize\x121\n" +
	"\x04data\x18\x04 \x03(\v2\x1d.api.admin.v1.DictTypeContentR\x04data\"\xc1\x02\n" +
	"\x0fDictTypeContent\x12\x16\n" +
	"\x06dictId\x18\x01 \x01(\rR\x06dictId\x12\x1a\n" +
	"\bdictName\x18\x02 \x01(\tR\bdictName\x12\x1a\n" +
	"\bdictType\x18\x03 \x01(\tR\bdictType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1a\n" +
	"\bcreateBy\x18\x05 \x01(\tR\bcreateBy\x12\x1a\n" +
	"\bupdateBy\x18\x06 \x01(\tR\bupdateBy\x12\x16\n" +
	"\x06remark\x18\a \x01(\tR\x06remark\x12:\n" +
	"\n" +
	"createTime\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12:\n" +
	"\n" +
	"updateTime\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"8\n" +
	"\x1cGetDesignateDictTypesRequest\x12\x18\n" +
	"\adictIDs\x18\x01 \x03(\tR\adictIDs\"\x1c\n" +
	"\x1aGetDesignateDictTypesReply2\xe1\x04\n" +
	"\bDictType\x12r\n" +
	"\fListDictType\x12!.api.admin.v1.ListDictTypeRequest\x1a\x1f.api.admin.v1.ListDictTypeReply\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/system/dict/type/list\x12v\n" +
	"\x0eCreateDictType\x12#.api.admin.v1.CreateDictTypeRequest\x1a!.api.admin.v1.CreateDictTypeReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/system/dict/type\x12v\n" +
	"\x0eUpdateDictType\x12#.api.admin.v1.UpdateDictTypeRequest\x1a!.api.admin.v1.UpdateDictTypeReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/system/dict/type\x12|\n" +
	"\x0eDeleteDictType\x12#.api.admin.v1.DeleteDictTypeRequest\x1a!.api.admin.v1.DeleteDictTypeReply\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/system/dict/type/{dictId}\x12s\n" +
	"\vGetDictType\x12 .api.admin.v1.GetDictTypeRequest\x1a\x1e.api.admin.v1.GetDictTypeReply\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/system/dict/type/{dictId}B>Z<https://github.com/swordkee/kratos-vue-admin/api/admin/v1;v1b\x06proto3"

var (
	file_dicttype_proto_rawDescOnce sync.Once
	file_dicttype_proto_rawDescData []byte
)

func file_dicttype_proto_rawDescGZIP() []byte {
	file_dicttype_proto_rawDescOnce.Do(func() {
		file_dicttype_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dicttype_proto_rawDesc), len(file_dicttype_proto_rawDesc)))
	})
	return file_dicttype_proto_rawDescData
}

var file_dicttype_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_dicttype_proto_goTypes = []any{
	(*CreateDictTypeRequest)(nil),        // 0: api.admin.v1.CreateDictTypeRequest
	(*CreateDictTypeReply)(nil),          // 1: api.admin.v1.CreateDictTypeReply
	(*UpdateDictTypeRequest)(nil),        // 2: api.admin.v1.UpdateDictTypeRequest
	(*UpdateDictTypeReply)(nil),          // 3: api.admin.v1.UpdateDictTypeReply
	(*DeleteDictTypeRequest)(nil),        // 4: api.admin.v1.DeleteDictTypeRequest
	(*DeleteDictTypeReply)(nil),          // 5: api.admin.v1.DeleteDictTypeReply
	(*GetDictTypeRequest)(nil),           // 6: api.admin.v1.GetDictTypeRequest
	(*GetDictTypeReply)(nil),             // 7: api.admin.v1.GetDictTypeReply
	(*ListDictTypeRequest)(nil),          // 8: api.admin.v1.ListDictTypeRequest
	(*ListDictTypeReply)(nil),            // 9: api.admin.v1.ListDictTypeReply
	(*DictTypeContent)(nil),              // 10: api.admin.v1.DictTypeContent
	(*GetDesignateDictTypesRequest)(nil), // 11: api.admin.v1.GetDesignateDictTypesRequest
	(*GetDesignateDictTypesReply)(nil),   // 12: api.admin.v1.GetDesignateDictTypesReply
	(*timestamppb.Timestamp)(nil),        // 13: google.protobuf.Timestamp
}
var file_dicttype_proto_depIdxs = []int32{
	13, // 0: api.admin.v1.UpdateDictTypeRequest.createTime:type_name -> google.protobuf.Timestamp
	13, // 1: api.admin.v1.UpdateDictTypeRequest.updateTime:type_name -> google.protobuf.Timestamp
	10, // 2: api.admin.v1.ListDictTypeReply.data:type_name -> api.admin.v1.DictTypeContent
	13, // 3: api.admin.v1.DictTypeContent.createTime:type_name -> google.protobuf.Timestamp
	13, // 4: api.admin.v1.DictTypeContent.updateTime:type_name -> google.protobuf.Timestamp
	8,  // 5: api.admin.v1.DictType.ListDictType:input_type -> api.admin.v1.ListDictTypeRequest
	0,  // 6: api.admin.v1.DictType.CreateDictType:input_type -> api.admin.v1.CreateDictTypeRequest
	2,  // 7: api.admin.v1.DictType.UpdateDictType:input_type -> api.admin.v1.UpdateDictTypeRequest
	4,  // 8: api.admin.v1.DictType.DeleteDictType:input_type -> api.admin.v1.DeleteDictTypeRequest
	6,  // 9: api.admin.v1.DictType.GetDictType:input_type -> api.admin.v1.GetDictTypeRequest
	9,  // 10: api.admin.v1.DictType.ListDictType:output_type -> api.admin.v1.ListDictTypeReply
	1,  // 11: api.admin.v1.DictType.CreateDictType:output_type -> api.admin.v1.CreateDictTypeReply
	3,  // 12: api.admin.v1.DictType.UpdateDictType:output_type -> api.admin.v1.UpdateDictTypeReply
	5,  // 13: api.admin.v1.DictType.DeleteDictType:output_type -> api.admin.v1.DeleteDictTypeReply
	7,  // 14: api.admin.v1.DictType.GetDictType:output_type -> api.admin.v1.GetDictTypeReply
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_dicttype_proto_init() }
func file_dicttype_proto_init() {
	if File_dicttype_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dicttype_proto_rawDesc), len(file_dicttype_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dicttype_proto_goTypes,
		DependencyIndexes: file_dicttype_proto_depIdxs,
		MessageInfos:      file_dicttype_proto_msgTypes,
	}.Build()
	File_dicttype_proto = out.File
	file_dicttype_proto_goTypes = nil
	file_dicttype_proto_depIdxs = nil
}
