// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.14.0
// source: dictdata.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDictDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictType      string                 `protobuf:"bytes,1,opt,name=dictType,proto3" json:"dictType,omitempty"`
	DictLabel     string                 `protobuf:"bytes,2,opt,name=dictLabel,proto3" json:"dictLabel,omitempty"`
	DictValue     string                 `protobuf:"bytes,3,opt,name=dictValue,proto3" json:"dictValue,omitempty"`
	DictSort      uint32                 `protobuf:"varint,4,opt,name=dictSort,proto3" json:"dictSort,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Remark        string                 `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDictDataRequest) Reset() {
	*x = CreateDictDataRequest{}
	mi := &file_dictdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDictDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDictDataRequest) ProtoMessage() {}

func (x *CreateDictDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dictdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDictDataRequest.ProtoReflect.Descriptor instead.
func (*CreateDictDataRequest) Descriptor() ([]byte, []int) {
	return file_dictdata_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDictDataRequest) GetDictType() string {
	if x != nil {
		return x.DictType
	}
	return ""
}

func (x *CreateDictDataRequest) GetDictLabel() string {
	if x != nil {
		return x.DictLabel
	}
	return ""
}

func (x *CreateDictDataRequest) GetDictValue() string {
	if x != nil {
		return x.DictValue
	}
	return ""
}

func (x *CreateDictDataRequest) GetDictSort() uint32 {
	if x != nil {
		return x.DictSort
	}
	return 0
}

func (x *CreateDictDataRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateDictDataRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type CreateDictDataReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDictDataReply) Reset() {
	*x = CreateDictDataReply{}
	mi := &file_dictdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDictDataReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDictDataReply) ProtoMessage() {}

func (x *CreateDictDataReply) ProtoReflect() protoreflect.Message {
	mi := &file_dictdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDictDataReply.ProtoReflect.Descriptor instead.
func (*CreateDictDataReply) Descriptor() ([]byte, []int) {
	return file_dictdata_proto_rawDescGZIP(), []int{1}
}

type UpdateDictDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictCode      int64                  `protobuf:"varint,1,opt,name=dictCode,proto3" json:"dictCode,omitempty"`
	DictSort      int32                  `protobuf:"varint,2,opt,name=dictSort,proto3" json:"dictSort,omitempty"`
	DictLabel     string                 `protobuf:"bytes,3,opt,name=dictLabel,proto3" json:"dictLabel,omitempty"`
	DictValue     string                 `protobuf:"bytes,4,opt,name=dictValue,proto3" json:"dictValue,omitempty"`
	DictType      string                 `protobuf:"bytes,5,opt,name=dictType,proto3" json:"dictType,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	CssClass      string                 `protobuf:"bytes,7,opt,name=cssClass,proto3" json:"cssClass,omitempty"`
	ListClass     string                 `protobuf:"bytes,8,opt,name=listClass,proto3" json:"listClass,omitempty"`
	IsDefault     string                 `protobuf:"bytes,9,opt,name=isDefault,proto3" json:"isDefault,omitempty"`
	CreateBy      string                 `protobuf:"bytes,10,opt,name=createBy,proto3" json:"createBy,omitempty"`
	UpdateBy      string                 `protobuf:"bytes,11,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
	Remark        string                 `protobuf:"bytes,12,opt,name=remark,proto3" json:"remark,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDictDataRequest) Reset() {
	*x = UpdateDictDataRequest{}
	mi := &file_dictdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDictDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDictDataRequest) ProtoMessage() {}

func (x *UpdateDictDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dictdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDictDataRequest.ProtoReflect.Descriptor instead.
func (*UpdateDictDataRequest) Descriptor() ([]byte, []int) {
	return file_dictdata_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateDictDataRequest) GetDictCode() int64 {
	if x != nil {
		return x.DictCode
	}
	return 0
}

func (x *UpdateDictDataRequest) GetDictSort() int32 {
	if x != nil {
		return x.DictSort
	}
	return 0
}

func (x *UpdateDictDataRequest) GetDictLabel() string {
	if x != nil {
		return x.DictLabel
	}
	return ""
}

func (x *UpdateDictDataRequest) GetDictValue() string {
	if x != nil {
		return x.DictValue
	}
	return ""
}

func (x *UpdateDictDataRequest) GetDictType() string {
	if x != nil {
		return x.DictType
	}
	return ""
}

func (x *UpdateDictDataRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateDictDataRequest) GetCssClass() string {
	if x != nil {
		return x.CssClass
	}
	return ""
}

func (x *UpdateDictDataRequest) GetListClass() string {
	if x != nil {
		return x.ListClass
	}
	return ""
}

func (x *UpdateDictDataRequest) GetIsDefault() string {
	if x != nil {
		return x.IsDefault
	}
	return ""
}

func (x *UpdateDictDataRequest) GetCreateBy() string {
	if x != nil {
		return x.CreateBy
	}
	return ""
}

func (x *UpdateDictDataRequest) GetUpdateBy() string {
	if x != nil {
		return x.UpdateBy
	}
	return ""
}

func (x *UpdateDictDataRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *UpdateDictDataRequest) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *UpdateDictDataRequest) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type UpdateDictDataReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictCode      int64                  `protobuf:"varint,1,opt,name=dictCode,proto3" json:"dictCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDictDataReply) Reset() {
	*x = UpdateDictDataReply{}
	mi := &file_dictdata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDictDataReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDictDataReply) ProtoMessage() {}

func (x *UpdateDictDataReply) ProtoReflect() protoreflect.Message {
	mi := &file_dictdata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDictDataReply.ProtoReflect.Descriptor instead.
func (*UpdateDictDataReply) Descriptor() ([]byte, []int) {
	return file_dictdata_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDictDataReply) GetDictCode() int64 {
	if x != nil {
		return x.DictCode
	}
	return 0
}

type DeleteDictDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictCode      int64                  `protobuf:"varint,1,opt,name=dictCode,proto3" json:"dictCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDictDataRequest) Reset() {
	*x = DeleteDictDataRequest{}
	mi := &file_dictdata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDictDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDictDataRequest) ProtoMessage() {}

func (x *DeleteDictDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dictdata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDictDataRequest.ProtoReflect.Descriptor instead.
func (*DeleteDictDataRequest) Descriptor() ([]byte, []int) {
	return file_dictdata_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteDictDataRequest) GetDictCode() int64 {
	if x != nil {
		return x.DictCode
	}
	return 0
}

type DeleteDictDataReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictCode      int64                  `protobuf:"varint,1,opt,name=dictCode,proto3" json:"dictCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDictDataReply) Reset() {
	*x = DeleteDictDataReply{}
	mi := &file_dictdata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDictDataReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDictDataReply) ProtoMessage() {}

func (x *DeleteDictDataReply) ProtoReflect() protoreflect.Message {
	mi := &file_dictdata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDictDataReply.ProtoReflect.Descriptor instead.
func (*DeleteDictDataReply) Descriptor() ([]byte, []int) {
	return file_dictdata_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDictDataReply) GetDictCode() int64 {
	if x != nil {
		return x.DictCode
	}
	return 0
}

type FindDictDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictCode      int64                  `protobuf:"varint,1,opt,name=dictCode,proto3" json:"dictCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindDictDataRequest) Reset() {
	*x = FindDictDataRequest{}
	mi := &file_dictdata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindDictDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindDictDataRequest) ProtoMessage() {}

func (x *FindDictDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dictdata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindDictDataRequest.ProtoReflect.Descriptor instead.
func (*FindDictDataRequest) Descriptor() ([]byte, []int) {
	return file_dictdata_proto_rawDescGZIP(), []int{6}
}

func (x *FindDictDataRequest) GetDictCode() int64 {
	if x != nil {
		return x.DictCode
	}
	return 0
}

type FindDictDataReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictCode      int64                  `protobuf:"varint,1,opt,name=dictCode,proto3" json:"dictCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindDictDataReply) Reset() {
	*x = FindDictDataReply{}
	mi := &file_dictdata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindDictDataReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindDictDataReply) ProtoMessage() {}

func (x *FindDictDataReply) ProtoReflect() protoreflect.Message {
	mi := &file_dictdata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindDictDataReply.ProtoReflect.Descriptor instead.
func (*FindDictDataReply) Descriptor() ([]byte, []int) {
	return file_dictdata_proto_rawDescGZIP(), []int{7}
}

func (x *FindDictDataReply) GetDictCode() int64 {
	if x != nil {
		return x.DictCode
	}
	return 0
}

type ListDictDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNum       int32                  `protobuf:"varint,1,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	DictType      string                 `protobuf:"bytes,4,opt,name=dictType,proto3" json:"dictType,omitempty"`
	DictLabel     string                 `protobuf:"bytes,5,opt,name=dictLabel,proto3" json:"dictLabel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDictDataRequest) Reset() {
	*x = ListDictDataRequest{}
	mi := &file_dictdata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDictDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictDataRequest) ProtoMessage() {}

func (x *ListDictDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dictdata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictDataRequest.ProtoReflect.Descriptor instead.
func (*ListDictDataRequest) Descriptor() ([]byte, []int) {
	return file_dictdata_proto_rawDescGZIP(), []int{8}
}

func (x *ListDictDataRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListDictDataRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDictDataRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListDictDataRequest) GetDictType() string {
	if x != nil {
		return x.DictType
	}
	return ""
}

func (x *ListDictDataRequest) GetDictLabel() string {
	if x != nil {
		return x.DictLabel
	}
	return ""
}

type ListDictDataReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	PageNum       int32                  `protobuf:"varint,2,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	List          []*DictDataContent     `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDictDataReply) Reset() {
	*x = ListDictDataReply{}
	mi := &file_dictdata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDictDataReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictDataReply) ProtoMessage() {}

func (x *ListDictDataReply) ProtoReflect() protoreflect.Message {
	mi := &file_dictdata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictDataReply.ProtoReflect.Descriptor instead.
func (*ListDictDataReply) Descriptor() ([]byte, []int) {
	return file_dictdata_proto_rawDescGZIP(), []int{9}
}

func (x *ListDictDataReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListDictDataReply) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListDictDataReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDictDataReply) GetList() []*DictDataContent {
	if x != nil {
		return x.List
	}
	return nil
}

type DictDataContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictCode      uint32                 `protobuf:"varint,1,opt,name=dictCode,proto3" json:"dictCode,omitempty"`
	DictSort      uint32                 `protobuf:"varint,2,opt,name=dictSort,proto3" json:"dictSort,omitempty"`
	DictLabel     string                 `protobuf:"bytes,3,opt,name=dictLabel,proto3" json:"dictLabel,omitempty"`
	DictValue     string                 `protobuf:"bytes,4,opt,name=dictValue,proto3" json:"dictValue,omitempty"`
	DictType      string                 `protobuf:"bytes,5,opt,name=dictType,proto3" json:"dictType,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	CssClass      string                 `protobuf:"bytes,7,opt,name=cssClass,proto3" json:"cssClass,omitempty"`
	ListClass     string                 `protobuf:"bytes,8,opt,name=listClass,proto3" json:"listClass,omitempty"`
	IsDefault     string                 `protobuf:"bytes,9,opt,name=isDefault,proto3" json:"isDefault,omitempty"`
	CreateBy      string                 `protobuf:"bytes,10,opt,name=createBy,proto3" json:"createBy,omitempty"`
	UpdateBy      string                 `protobuf:"bytes,11,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
	Remark        string                 `protobuf:"bytes,12,opt,name=remark,proto3" json:"remark,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictDataContent) Reset() {
	*x = DictDataContent{}
	mi := &file_dictdata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictDataContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictDataContent) ProtoMessage() {}

func (x *DictDataContent) ProtoReflect() protoreflect.Message {
	mi := &file_dictdata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictDataContent.ProtoReflect.Descriptor instead.
func (*DictDataContent) Descriptor() ([]byte, []int) {
	return file_dictdata_proto_rawDescGZIP(), []int{10}
}

func (x *DictDataContent) GetDictCode() uint32 {
	if x != nil {
		return x.DictCode
	}
	return 0
}

func (x *DictDataContent) GetDictSort() uint32 {
	if x != nil {
		return x.DictSort
	}
	return 0
}

func (x *DictDataContent) GetDictLabel() string {
	if x != nil {
		return x.DictLabel
	}
	return ""
}

func (x *DictDataContent) GetDictValue() string {
	if x != nil {
		return x.DictValue
	}
	return ""
}

func (x *DictDataContent) GetDictType() string {
	if x != nil {
		return x.DictType
	}
	return ""
}

func (x *DictDataContent) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DictDataContent) GetCssClass() string {
	if x != nil {
		return x.CssClass
	}
	return ""
}

func (x *DictDataContent) GetListClass() string {
	if x != nil {
		return x.ListClass
	}
	return ""
}

func (x *DictDataContent) GetIsDefault() string {
	if x != nil {
		return x.IsDefault
	}
	return ""
}

func (x *DictDataContent) GetCreateBy() string {
	if x != nil {
		return x.CreateBy
	}
	return ""
}

func (x *DictDataContent) GetUpdateBy() string {
	if x != nil {
		return x.UpdateBy
	}
	return ""
}

func (x *DictDataContent) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *DictDataContent) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *DictDataContent) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

var File_dictdata_proto protoreflect.FileDescriptor

const file_dictdata_proto_rawDesc = "" +
	"\n" +
	"\x0edictdata.proto\x12\fapi.admin.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x01\n" +
	"\x15CreateDictDataRequest\x12\x1a\n" +
	"\bdictType\x18\x01 \x01(\tR\bdictType\x12\x1c\n" +
	"\tdictLabel\x18\x02 \x01(\tR\tdictLabel\x12\x1c\n" +
	"\tdictValue\x18\x03 \x01(\tR\tdictValue\x12\x1a\n" +
	"\bdictSort\x18\x04 \x01(\rR\bdictSort\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x16\n" +
	"\x06remark\x18\x06 \x01(\tR\x06remark\"\x15\n" +
	"\x13CreateDictDataReply\"\xdf\x03\n" +
	"\x15UpdateDictDataRequest\x12\x1a\n" +
	"\bdictCode\x18\x01 \x01(\x03R\bdictCode\x12\x1a\n" +
	"\bdictSort\x18\x02 \x01(\x05R\bdictSort\x12\x1c\n" +
	"\tdictLabel\x18\x03 \x01(\tR\tdictLabel\x12\x1c\n" +
	"\tdictValue\x18\x04 \x01(\tR\tdictValue\x12\x1a\n" +
	"\bdictType\x18\x05 \x01(\tR\bdictType\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1a\n" +
	"\bcssClass\x18\a \x01(\tR\bcssClass\x12\x1c\n" +
	"\tlistClass\x18\b \x01(\tR\tlistClass\x12\x1c\n" +
	"\tisDefault\x18\t \x01(\tR\tisDefault\x12\x1a\n" +
	"\bcreateBy\x18\n" +
	" \x01(\tR\bcreateBy\x12\x1a\n" +
	"\bupdateBy\x18\v \x01(\tR\bupdateBy\x12\x16\n" +
	"\x06remark\x18\f \x01(\tR\x06remark\x12:\n" +
	"\n" +
	"createTime\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12:\n" +
	"\n" +
	"updateTime\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"1\n" +
	"\x13UpdateDictDataReply\x12\x1a\n" +
	"\bdictCode\x18\x01 \x01(\x03R\bdictCode\"3\n" +
	"\x15DeleteDictDataRequest\x12\x1a\n" +
	"\bdictCode\x18\x01 \x01(\x03R\bdictCode\"1\n" +
	"\x13DeleteDictDataReply\x12\x1a\n" +
	"\bdictCode\x18\x01 \x01(\x03R\bdictCode\"1\n" +
	"\x13FindDictDataRequest\x12\x1a\n" +
	"\bdictCode\x18\x01 \x01(\x03R\bdictCode\"/\n" +
	"\x11FindDictDataReply\x12\x1a\n" +
	"\bdictCode\x18\x01 \x01(\x03R\bdictCode\"\x9d\x01\n" +
	"\x13ListDictDataRequest\x12\x18\n" +
	"\apageNum\x18\x01 \x01(\x05R\apageNum\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1a\n" +
	"\bdictType\x18\x04 \x01(\tR\bdictType\x12\x1c\n" +
	"\tdictLabel\x18\x05 \x01(\tR\tdictLabel\"\x92\x01\n" +
	"\x11ListDictDataReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x18\n" +
	"\apageNum\x18\x02 \x01(\x05R\apageNum\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize\x121\n" +
	"\x04list\x18\x04 \x03(\v2\x1d.api.admin.v1.DictDataContentR\x04list\"\xd9\x03\n" +
	"\x0fDictDataContent\x12\x1a\n" +
	"\bdictCode\x18\x01 \x01(\rR\bdictCode\x12\x1a\n" +
	"\bdictSort\x18\x02 \x01(\rR\bdictSort\x12\x1c\n" +
	"\tdictLabel\x18\x03 \x01(\tR\tdictLabel\x12\x1c\n" +
	"\tdictValue\x18\x04 \x01(\tR\tdictValue\x12\x1a\n" +
	"\bdictType\x18\x05 \x01(\tR\bdictType\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1a\n" +
	"\bcssClass\x18\a \x01(\tR\bcssClass\x12\x1c\n" +
	"\tlistClass\x18\b \x01(\tR\tlistClass\x12\x1c\n" +
	"\tisDefault\x18\t \x01(\tR\tisDefault\x12\x1a\n" +
	"\bcreateBy\x18\n" +
	" \x01(\tR\bcreateBy\x12\x1a\n" +
	"\bupdateBy\x18\v \x01(\tR\bupdateBy\x12\x16\n" +
	"\x06remark\x18\f \x01(\tR\x06remark\x12:\n" +
	"\n" +
	"createTime\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12:\n" +
	"\n" +
	"updateTime\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime2\xed\x04\n" +
	"\bDictData\x12r\n" +
	"\fListDictData\x12!.api.admin.v1.ListDictDataRequest\x1a\x1f.api.admin.v1.ListDictDataReply\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/system/dict/data/type\x12v\n" +
	"\x0eCreateDictData\x12#.api.admin.v1.CreateDictDataRequest\x1a!.api.admin.v1.CreateDictDataReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/system/dict/data\x12v\n" +
	"\x0eUpdateDictData\x12#.api.admin.v1.UpdateDictDataRequest\x1a!.api.admin.v1.UpdateDictDataReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/system/dict/data\x12~\n" +
	"\x0eDeleteDictData\x12#.api.admin.v1.DeleteDictDataRequest\x1a!.api.admin.v1.DeleteDictDataReply\"$\x82\xd3\xe4\x93\x02\x1e*\x1c/system/dict/data/{dictCode}\x12}\n" +
	"\fFindDictData\x12!.api.admin.v1.FindDictDataRequest\x1a\x1f.api.admin.v1.FindDictDataReply\")\x82\xd3\xe4\x93\x02#\x12!/system/dict/data/info/{dictCode}B6Z4github.com/swordkee/kratos-vue-admin/api/admin/v1;v1b\x06proto3"

var (
	file_dictdata_proto_rawDescOnce sync.Once
	file_dictdata_proto_rawDescData []byte
)

func file_dictdata_proto_rawDescGZIP() []byte {
	file_dictdata_proto_rawDescOnce.Do(func() {
		file_dictdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dictdata_proto_rawDesc), len(file_dictdata_proto_rawDesc)))
	})
	return file_dictdata_proto_rawDescData
}

var file_dictdata_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_dictdata_proto_goTypes = []any{
	(*CreateDictDataRequest)(nil), // 0: api.admin.v1.CreateDictDataRequest
	(*CreateDictDataReply)(nil),   // 1: api.admin.v1.CreateDictDataReply
	(*UpdateDictDataRequest)(nil), // 2: api.admin.v1.UpdateDictDataRequest
	(*UpdateDictDataReply)(nil),   // 3: api.admin.v1.UpdateDictDataReply
	(*DeleteDictDataRequest)(nil), // 4: api.admin.v1.DeleteDictDataRequest
	(*DeleteDictDataReply)(nil),   // 5: api.admin.v1.DeleteDictDataReply
	(*FindDictDataRequest)(nil),   // 6: api.admin.v1.FindDictDataRequest
	(*FindDictDataReply)(nil),     // 7: api.admin.v1.FindDictDataReply
	(*ListDictDataRequest)(nil),   // 8: api.admin.v1.ListDictDataRequest
	(*ListDictDataReply)(nil),     // 9: api.admin.v1.ListDictDataReply
	(*DictDataContent)(nil),       // 10: api.admin.v1.DictDataContent
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_dictdata_proto_depIdxs = []int32{
	11, // 0: api.admin.v1.UpdateDictDataRequest.createTime:type_name -> google.protobuf.Timestamp
	11, // 1: api.admin.v1.UpdateDictDataRequest.updateTime:type_name -> google.protobuf.Timestamp
	10, // 2: api.admin.v1.ListDictDataReply.list:type_name -> api.admin.v1.DictDataContent
	11, // 3: api.admin.v1.DictDataContent.createTime:type_name -> google.protobuf.Timestamp
	11, // 4: api.admin.v1.DictDataContent.updateTime:type_name -> google.protobuf.Timestamp
	8,  // 5: api.admin.v1.DictData.ListDictData:input_type -> api.admin.v1.ListDictDataRequest
	0,  // 6: api.admin.v1.DictData.CreateDictData:input_type -> api.admin.v1.CreateDictDataRequest
	2,  // 7: api.admin.v1.DictData.UpdateDictData:input_type -> api.admin.v1.UpdateDictDataRequest
	4,  // 8: api.admin.v1.DictData.DeleteDictData:input_type -> api.admin.v1.DeleteDictDataRequest
	6,  // 9: api.admin.v1.DictData.FindDictData:input_type -> api.admin.v1.FindDictDataRequest
	9,  // 10: api.admin.v1.DictData.ListDictData:output_type -> api.admin.v1.ListDictDataReply
	1,  // 11: api.admin.v1.DictData.CreateDictData:output_type -> api.admin.v1.CreateDictDataReply
	3,  // 12: api.admin.v1.DictData.UpdateDictData:output_type -> api.admin.v1.UpdateDictDataReply
	5,  // 13: api.admin.v1.DictData.DeleteDictData:output_type -> api.admin.v1.DeleteDictDataReply
	7,  // 14: api.admin.v1.DictData.FindDictData:output_type -> api.admin.v1.FindDictDataReply
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_dictdata_proto_init() }
func file_dictdata_proto_init() {
	if File_dictdata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dictdata_proto_rawDesc), len(file_dictdata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dictdata_proto_goTypes,
		DependencyIndexes: file_dictdata_proto_depIdxs,
		MessageInfos:      file_dictdata_proto_msgTypes,
	}.Build()
	File_dictdata_proto = out.File
	file_dictdata_proto_goTypes = nil
	file_dictdata_proto_depIdxs = nil
}
