// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.14.0
// source: logs.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	LogsService_ListLogs_FullMethodName        = "/api.admin.v1.LogsService/ListLogs"
	LogsService_FindLogs_FullMethodName        = "/api.admin.v1.LogsService/FindLogs"
	LogsService_CleanLogs_FullMethodName       = "/api.admin.v1.LogsService/CleanLogs"
	LogsService_DeleteLogsByIds_FullMethodName = "/api.admin.v1.LogsService/DeleteLogsByIds"
)

// LogsServiceClient is the client API for LogsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogsServiceClient interface {
	ListLogs(ctx context.Context, in *ListLogsRequest, opts ...grpc.CallOption) (*ListLogsReply, error)
	FindLogs(ctx context.Context, in *FindLogsRequest, opts ...grpc.CallOption) (*FindLogsReply, error)
	CleanLogs(ctx context.Context, in *CleanLogsRequest, opts ...grpc.CallOption) (*CleanLogsReply, error)
	DeleteLogsByIds(ctx context.Context, in *DeleteLogsByIdsRequest, opts ...grpc.CallOption) (*DeleteLogsByIdsReply, error)
}

type logsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogsServiceClient(cc grpc.ClientConnInterface) LogsServiceClient {
	return &logsServiceClient{cc}
}

func (c *logsServiceClient) ListLogs(ctx context.Context, in *ListLogsRequest, opts ...grpc.CallOption) (*ListLogsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLogsReply)
	err := c.cc.Invoke(ctx, LogsService_ListLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logsServiceClient) FindLogs(ctx context.Context, in *FindLogsRequest, opts ...grpc.CallOption) (*FindLogsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindLogsReply)
	err := c.cc.Invoke(ctx, LogsService_FindLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logsServiceClient) CleanLogs(ctx context.Context, in *CleanLogsRequest, opts ...grpc.CallOption) (*CleanLogsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanLogsReply)
	err := c.cc.Invoke(ctx, LogsService_CleanLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logsServiceClient) DeleteLogsByIds(ctx context.Context, in *DeleteLogsByIdsRequest, opts ...grpc.CallOption) (*DeleteLogsByIdsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLogsByIdsReply)
	err := c.cc.Invoke(ctx, LogsService_DeleteLogsByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogsServiceServer is the server API for LogsService service.
// All implementations must embed UnimplementedLogsServiceServer
// for forward compatibility
type LogsServiceServer interface {
	ListLogs(context.Context, *ListLogsRequest) (*ListLogsReply, error)
	FindLogs(context.Context, *FindLogsRequest) (*FindLogsReply, error)
	CleanLogs(context.Context, *CleanLogsRequest) (*CleanLogsReply, error)
	DeleteLogsByIds(context.Context, *DeleteLogsByIdsRequest) (*DeleteLogsByIdsReply, error)
	mustEmbedUnimplementedLogsServiceServer()
}

// UnimplementedLogsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLogsServiceServer struct {
}

func (UnimplementedLogsServiceServer) ListLogs(context.Context, *ListLogsRequest) (*ListLogsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLogs not implemented")
}
func (UnimplementedLogsServiceServer) FindLogs(context.Context, *FindLogsRequest) (*FindLogsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindLogs not implemented")
}
func (UnimplementedLogsServiceServer) CleanLogs(context.Context, *CleanLogsRequest) (*CleanLogsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CleanLogs not implemented")
}
func (UnimplementedLogsServiceServer) DeleteLogsByIds(context.Context, *DeleteLogsByIdsRequest) (*DeleteLogsByIdsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLogsByIds not implemented")
}
func (UnimplementedLogsServiceServer) mustEmbedUnimplementedLogsServiceServer() {}

// UnsafeLogsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogsServiceServer will
// result in compilation errors.
type UnsafeLogsServiceServer interface {
	mustEmbedUnimplementedLogsServiceServer()
}

func RegisterLogsServiceServer(s grpc.ServiceRegistrar, srv LogsServiceServer) {
	s.RegisterService(&LogsService_ServiceDesc, srv)
}

func _LogsService_ListLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogsServiceServer).ListLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogsService_ListLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogsServiceServer).ListLogs(ctx, req.(*ListLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogsService_FindLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogsServiceServer).FindLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogsService_FindLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogsServiceServer).FindLogs(ctx, req.(*FindLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogsService_CleanLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogsServiceServer).CleanLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogsService_CleanLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogsServiceServer).CleanLogs(ctx, req.(*CleanLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogsService_DeleteLogsByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLogsByIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogsServiceServer).DeleteLogsByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogsService_DeleteLogsByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogsServiceServer).DeleteLogsByIds(ctx, req.(*DeleteLogsByIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogsService_ServiceDesc is the grpc.ServiceDesc for LogsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.admin.v1.LogsService",
	HandlerType: (*LogsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListLogs",
			Handler:    _LogsService_ListLogs_Handler,
		},
		{
			MethodName: "FindLogs",
			Handler:    _LogsService_FindLogs_Handler,
		},
		{
			MethodName: "CleanLogs",
			Handler:    _LogsService_CleanLogs_Handler,
		},
		{
			MethodName: "DeleteLogsByIds",
			Handler:    _LogsService_DeleteLogsByIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logs.proto",
}
