// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.14.0
// source: logs.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationLogsServiceCleanLogs = "/api.admin.v1.LogsService/CleanLogs"
const OperationLogsServiceDeleteLogsByIds = "/api.admin.v1.LogsService/DeleteLogsByIds"
const OperationLogsServiceGetLogs = "/api.admin.v1.LogsService/GetLogs"
const OperationLogsServiceListLogs = "/api.admin.v1.LogsService/ListLogs"

type LogsServiceHTTPServer interface {
	CleanLogs(context.Context, *CleanLogsRequest) (*CleanLogsReply, error)
	DeleteLogsByIds(context.Context, *DeleteLogsByIdsRequest) (*DeleteLogsByIdsReply, error)
	GetLogs(context.Context, *GetLogsRequest) (*GetLogsReply, error)
	ListLogs(context.Context, *ListLogsRequest) (*ListLogsReply, error)
}

func RegisterLogsServiceHTTPServer(s *http.Server, srv LogsServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/system/logs/list", _LogsService_ListLogs0_HTTP_Handler(srv))
	r.GET("/system/logs/{id}", _LogsService_GetLogs0_HTTP_Handler(srv))
	r.DELETE("/system/logs/clean", _LogsService_CleanLogs0_HTTP_Handler(srv))
	r.DELETE("/system/logs/deleteByIds", _LogsService_DeleteLogsByIds0_HTTP_Handler(srv))
}

func _LogsService_ListLogs0_HTTP_Handler(srv LogsServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListLogsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLogsServiceListLogs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListLogs(ctx, req.(*ListLogsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListLogsReply)
		return ctx.Result(200, reply)
	}
}

func _LogsService_GetLogs0_HTTP_Handler(srv LogsServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLogsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLogsServiceGetLogs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLogs(ctx, req.(*GetLogsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetLogsReply)
		return ctx.Result(200, reply)
	}
}

func _LogsService_CleanLogs0_HTTP_Handler(srv LogsServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CleanLogsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLogsServiceCleanLogs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CleanLogs(ctx, req.(*CleanLogsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CleanLogsReply)
		return ctx.Result(200, reply)
	}
}

func _LogsService_DeleteLogsByIds0_HTTP_Handler(srv LogsServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteLogsByIdsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLogsServiceDeleteLogsByIds)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteLogsByIds(ctx, req.(*DeleteLogsByIdsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteLogsByIdsReply)
		return ctx.Result(200, reply)
	}
}

type LogsServiceHTTPClient interface {
	CleanLogs(ctx context.Context, req *CleanLogsRequest, opts ...http.CallOption) (rsp *CleanLogsReply, err error)
	DeleteLogsByIds(ctx context.Context, req *DeleteLogsByIdsRequest, opts ...http.CallOption) (rsp *DeleteLogsByIdsReply, err error)
	GetLogs(ctx context.Context, req *GetLogsRequest, opts ...http.CallOption) (rsp *GetLogsReply, err error)
	ListLogs(ctx context.Context, req *ListLogsRequest, opts ...http.CallOption) (rsp *ListLogsReply, err error)
}

type LogsServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewLogsServiceHTTPClient(client *http.Client) LogsServiceHTTPClient {
	return &LogsServiceHTTPClientImpl{client}
}

func (c *LogsServiceHTTPClientImpl) CleanLogs(ctx context.Context, in *CleanLogsRequest, opts ...http.CallOption) (*CleanLogsReply, error) {
	var out CleanLogsReply
	pattern := "/system/logs/clean"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLogsServiceCleanLogs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LogsServiceHTTPClientImpl) DeleteLogsByIds(ctx context.Context, in *DeleteLogsByIdsRequest, opts ...http.CallOption) (*DeleteLogsByIdsReply, error) {
	var out DeleteLogsByIdsReply
	pattern := "/system/logs/deleteByIds"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLogsServiceDeleteLogsByIds))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LogsServiceHTTPClientImpl) GetLogs(ctx context.Context, in *GetLogsRequest, opts ...http.CallOption) (*GetLogsReply, error) {
	var out GetLogsReply
	pattern := "/system/logs/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLogsServiceGetLogs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LogsServiceHTTPClientImpl) ListLogs(ctx context.Context, in *ListLogsRequest, opts ...http.CallOption) (*ListLogsReply, error) {
	var out ListLogsReply
	pattern := "/system/logs/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLogsServiceListLogs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
