// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: message.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Message with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Message) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Message with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in MessageMultiError, or nil if none found.
func (m *Message) ValidateAll() error {
	return m.validate(true)
}

func (m *Message) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Uid

	// no validation rules for Type

	// no validation rules for Title

	// no validation rules for Content

	// no validation rules for Scene

	// no validation rules for Param

	// no validation rules for SenderId

	// no validation rules for SenderName

	// no validation rules for IsRead

	// no validation rules for ReadAt

	// no validation rules for DeletedAt

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return MessageMultiError(errors)
	}

	return nil
}

// MessageMultiError is an error wrapping multiple validation errors returned
// by Message.ValidateAll() if the designated constraints aren't met.
type MessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MessageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MessageMultiError) AllErrors() []error { return m }

// MessageValidationError is the validation error returned by Message.Validate
// if the designated constraints aren't met.
type MessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MessageValidationError) ErrorName() string { return "MessageValidationError" }

// Error satisfies the builtin error interface
func (e MessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MessageValidationError{}

// Validate checks the field values on SendMessageReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SendMessageReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendMessageReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SendMessageReqMultiError,
// or nil if none found.
func (m *SendMessageReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SendMessageReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Uid

	// no validation rules for Type

	if l := utf8.RuneCountInString(m.GetTitle()); l < 1 || l > 200 {
		err := SendMessageReqValidationError{
			field:  "Title",
			reason: "value length must be between 1 and 200 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Content

	// no validation rules for Scene

	// no validation rules for Param

	if len(errors) > 0 {
		return SendMessageReqMultiError(errors)
	}

	return nil
}

// SendMessageReqMultiError is an error wrapping multiple validation errors
// returned by SendMessageReq.ValidateAll() if the designated constraints
// aren't met.
type SendMessageReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendMessageReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendMessageReqMultiError) AllErrors() []error { return m }

// SendMessageReqValidationError is the validation error returned by
// SendMessageReq.Validate if the designated constraints aren't met.
type SendMessageReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendMessageReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendMessageReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendMessageReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendMessageReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendMessageReqValidationError) ErrorName() string { return "SendMessageReqValidationError" }

// Error satisfies the builtin error interface
func (e SendMessageReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendMessageReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendMessageReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendMessageReqValidationError{}

// Validate checks the field values on SendMessageRsp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SendMessageRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendMessageRsp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SendMessageRspMultiError,
// or nil if none found.
func (m *SendMessageRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *SendMessageRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Msg

	// no validation rules for Id

	if len(errors) > 0 {
		return SendMessageRspMultiError(errors)
	}

	return nil
}

// SendMessageRspMultiError is an error wrapping multiple validation errors
// returned by SendMessageRsp.ValidateAll() if the designated constraints
// aren't met.
type SendMessageRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendMessageRspMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendMessageRspMultiError) AllErrors() []error { return m }

// SendMessageRspValidationError is the validation error returned by
// SendMessageRsp.Validate if the designated constraints aren't met.
type SendMessageRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendMessageRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendMessageRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendMessageRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendMessageRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendMessageRspValidationError) ErrorName() string { return "SendMessageRspValidationError" }

// Error satisfies the builtin error interface
func (e SendMessageRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendMessageRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendMessageRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendMessageRspValidationError{}

// Validate checks the field values on ListMessagesReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListMessagesReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListMessagesReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListMessagesReqMultiError, or nil if none found.
func (m *ListMessagesReq) ValidateAll() error {
	return m.validate(true)
}

func (m *ListMessagesReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for PageSize

	// no validation rules for Uid

	if all {
		switch v := interface{}(m.GetType()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListMessagesReqValidationError{
					field:  "Type",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListMessagesReqValidationError{
					field:  "Type",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetType()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListMessagesReqValidationError{
				field:  "Type",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetIsRead()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListMessagesReqValidationError{
					field:  "IsRead",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListMessagesReqValidationError{
					field:  "IsRead",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetIsRead()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListMessagesReqValidationError{
				field:  "IsRead",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListMessagesReqMultiError(errors)
	}

	return nil
}

// ListMessagesReqMultiError is an error wrapping multiple validation errors
// returned by ListMessagesReq.ValidateAll() if the designated constraints
// aren't met.
type ListMessagesReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListMessagesReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListMessagesReqMultiError) AllErrors() []error { return m }

// ListMessagesReqValidationError is the validation error returned by
// ListMessagesReq.Validate if the designated constraints aren't met.
type ListMessagesReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListMessagesReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListMessagesReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListMessagesReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListMessagesReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListMessagesReqValidationError) ErrorName() string { return "ListMessagesReqValidationError" }

// Error satisfies the builtin error interface
func (e ListMessagesReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListMessagesReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListMessagesReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListMessagesReqValidationError{}

// Validate checks the field values on ListMessagesRsp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListMessagesRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListMessagesRsp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListMessagesRspMultiError, or nil if none found.
func (m *ListMessagesRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *ListMessagesRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Msg

	// no validation rules for Total

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListMessagesRspValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListMessagesRspValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListMessagesRspValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListMessagesRspMultiError(errors)
	}

	return nil
}

// ListMessagesRspMultiError is an error wrapping multiple validation errors
// returned by ListMessagesRsp.ValidateAll() if the designated constraints
// aren't met.
type ListMessagesRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListMessagesRspMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListMessagesRspMultiError) AllErrors() []error { return m }

// ListMessagesRspValidationError is the validation error returned by
// ListMessagesRsp.Validate if the designated constraints aren't met.
type ListMessagesRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListMessagesRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListMessagesRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListMessagesRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListMessagesRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListMessagesRspValidationError) ErrorName() string { return "ListMessagesRspValidationError" }

// Error satisfies the builtin error interface
func (e ListMessagesRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListMessagesRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListMessagesRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListMessagesRspValidationError{}

// Validate checks the field values on GetMessageReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetMessageReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMessageReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetMessageReqMultiError, or
// nil if none found.
func (m *GetMessageReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMessageReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetMessageReqMultiError(errors)
	}

	return nil
}

// GetMessageReqMultiError is an error wrapping multiple validation errors
// returned by GetMessageReq.ValidateAll() if the designated constraints
// aren't met.
type GetMessageReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMessageReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMessageReqMultiError) AllErrors() []error { return m }

// GetMessageReqValidationError is the validation error returned by
// GetMessageReq.Validate if the designated constraints aren't met.
type GetMessageReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMessageReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMessageReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMessageReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMessageReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMessageReqValidationError) ErrorName() string { return "GetMessageReqValidationError" }

// Error satisfies the builtin error interface
func (e GetMessageReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMessageReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMessageReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMessageReqValidationError{}

// Validate checks the field values on GetMessageRsp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetMessageRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMessageRsp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetMessageRspMultiError, or
// nil if none found.
func (m *GetMessageRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMessageRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Msg

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetMessageRspValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetMessageRspValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetMessageRspValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetMessageRspMultiError(errors)
	}

	return nil
}

// GetMessageRspMultiError is an error wrapping multiple validation errors
// returned by GetMessageRsp.ValidateAll() if the designated constraints
// aren't met.
type GetMessageRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMessageRspMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMessageRspMultiError) AllErrors() []error { return m }

// GetMessageRspValidationError is the validation error returned by
// GetMessageRsp.Validate if the designated constraints aren't met.
type GetMessageRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMessageRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMessageRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMessageRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMessageRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMessageRspValidationError) ErrorName() string { return "GetMessageRspValidationError" }

// Error satisfies the builtin error interface
func (e GetMessageRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMessageRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMessageRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMessageRspValidationError{}

// Validate checks the field values on MarkReadReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MarkReadReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MarkReadReq with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MarkReadReqMultiError, or
// nil if none found.
func (m *MarkReadReq) ValidateAll() error {
	return m.validate(true)
}

func (m *MarkReadReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return MarkReadReqMultiError(errors)
	}

	return nil
}

// MarkReadReqMultiError is an error wrapping multiple validation errors
// returned by MarkReadReq.ValidateAll() if the designated constraints aren't met.
type MarkReadReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MarkReadReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MarkReadReqMultiError) AllErrors() []error { return m }

// MarkReadReqValidationError is the validation error returned by
// MarkReadReq.Validate if the designated constraints aren't met.
type MarkReadReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MarkReadReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MarkReadReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MarkReadReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MarkReadReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MarkReadReqValidationError) ErrorName() string { return "MarkReadReqValidationError" }

// Error satisfies the builtin error interface
func (e MarkReadReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMarkReadReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MarkReadReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MarkReadReqValidationError{}

// Validate checks the field values on MarkReadRsp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MarkReadRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MarkReadRsp with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MarkReadRspMultiError, or
// nil if none found.
func (m *MarkReadRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *MarkReadRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Msg

	if len(errors) > 0 {
		return MarkReadRspMultiError(errors)
	}

	return nil
}

// MarkReadRspMultiError is an error wrapping multiple validation errors
// returned by MarkReadRsp.ValidateAll() if the designated constraints aren't met.
type MarkReadRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MarkReadRspMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MarkReadRspMultiError) AllErrors() []error { return m }

// MarkReadRspValidationError is the validation error returned by
// MarkReadRsp.Validate if the designated constraints aren't met.
type MarkReadRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MarkReadRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MarkReadRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MarkReadRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MarkReadRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MarkReadRspValidationError) ErrorName() string { return "MarkReadRspValidationError" }

// Error satisfies the builtin error interface
func (e MarkReadRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMarkReadRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MarkReadRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MarkReadRspValidationError{}

// Validate checks the field values on MarkAllReadReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MarkAllReadReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MarkAllReadReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MarkAllReadReqMultiError,
// or nil if none found.
func (m *MarkAllReadReq) ValidateAll() error {
	return m.validate(true)
}

func (m *MarkAllReadReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return MarkAllReadReqMultiError(errors)
	}

	return nil
}

// MarkAllReadReqMultiError is an error wrapping multiple validation errors
// returned by MarkAllReadReq.ValidateAll() if the designated constraints
// aren't met.
type MarkAllReadReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MarkAllReadReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MarkAllReadReqMultiError) AllErrors() []error { return m }

// MarkAllReadReqValidationError is the validation error returned by
// MarkAllReadReq.Validate if the designated constraints aren't met.
type MarkAllReadReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MarkAllReadReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MarkAllReadReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MarkAllReadReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MarkAllReadReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MarkAllReadReqValidationError) ErrorName() string { return "MarkAllReadReqValidationError" }

// Error satisfies the builtin error interface
func (e MarkAllReadReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMarkAllReadReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MarkAllReadReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MarkAllReadReqValidationError{}

// Validate checks the field values on MarkAllReadRsp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MarkAllReadRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MarkAllReadRsp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MarkAllReadRspMultiError,
// or nil if none found.
func (m *MarkAllReadRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *MarkAllReadRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Msg

	// no validation rules for Updated

	if len(errors) > 0 {
		return MarkAllReadRspMultiError(errors)
	}

	return nil
}

// MarkAllReadRspMultiError is an error wrapping multiple validation errors
// returned by MarkAllReadRsp.ValidateAll() if the designated constraints
// aren't met.
type MarkAllReadRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MarkAllReadRspMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MarkAllReadRspMultiError) AllErrors() []error { return m }

// MarkAllReadRspValidationError is the validation error returned by
// MarkAllReadRsp.Validate if the designated constraints aren't met.
type MarkAllReadRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MarkAllReadRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MarkAllReadRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MarkAllReadRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MarkAllReadRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MarkAllReadRspValidationError) ErrorName() string { return "MarkAllReadRspValidationError" }

// Error satisfies the builtin error interface
func (e MarkAllReadRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMarkAllReadRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MarkAllReadRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MarkAllReadRspValidationError{}

// Validate checks the field values on DeleteMessageReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeleteMessageReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteMessageReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteMessageReqMultiError, or nil if none found.
func (m *DeleteMessageReq) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteMessageReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteMessageReqMultiError(errors)
	}

	return nil
}

// DeleteMessageReqMultiError is an error wrapping multiple validation errors
// returned by DeleteMessageReq.ValidateAll() if the designated constraints
// aren't met.
type DeleteMessageReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteMessageReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteMessageReqMultiError) AllErrors() []error { return m }

// DeleteMessageReqValidationError is the validation error returned by
// DeleteMessageReq.Validate if the designated constraints aren't met.
type DeleteMessageReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteMessageReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteMessageReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteMessageReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteMessageReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteMessageReqValidationError) ErrorName() string { return "DeleteMessageReqValidationError" }

// Error satisfies the builtin error interface
func (e DeleteMessageReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteMessageReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteMessageReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteMessageReqValidationError{}

// Validate checks the field values on DeleteMessageRsp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeleteMessageRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteMessageRsp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteMessageRspMultiError, or nil if none found.
func (m *DeleteMessageRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteMessageRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Msg

	if len(errors) > 0 {
		return DeleteMessageRspMultiError(errors)
	}

	return nil
}

// DeleteMessageRspMultiError is an error wrapping multiple validation errors
// returned by DeleteMessageRsp.ValidateAll() if the designated constraints
// aren't met.
type DeleteMessageRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteMessageRspMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteMessageRspMultiError) AllErrors() []error { return m }

// DeleteMessageRspValidationError is the validation error returned by
// DeleteMessageRsp.Validate if the designated constraints aren't met.
type DeleteMessageRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteMessageRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteMessageRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteMessageRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteMessageRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteMessageRspValidationError) ErrorName() string { return "DeleteMessageRspValidationError" }

// Error satisfies the builtin error interface
func (e DeleteMessageRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteMessageRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteMessageRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteMessageRspValidationError{}

// Validate checks the field values on CountUnreadReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CountUnreadReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CountUnreadReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CountUnreadReqMultiError,
// or nil if none found.
func (m *CountUnreadReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CountUnreadReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CountUnreadReqMultiError(errors)
	}

	return nil
}

// CountUnreadReqMultiError is an error wrapping multiple validation errors
// returned by CountUnreadReq.ValidateAll() if the designated constraints
// aren't met.
type CountUnreadReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CountUnreadReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CountUnreadReqMultiError) AllErrors() []error { return m }

// CountUnreadReqValidationError is the validation error returned by
// CountUnreadReq.Validate if the designated constraints aren't met.
type CountUnreadReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CountUnreadReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CountUnreadReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CountUnreadReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CountUnreadReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CountUnreadReqValidationError) ErrorName() string { return "CountUnreadReqValidationError" }

// Error satisfies the builtin error interface
func (e CountUnreadReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCountUnreadReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CountUnreadReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CountUnreadReqValidationError{}

// Validate checks the field values on CountUnreadRsp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CountUnreadRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CountUnreadRsp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CountUnreadRspMultiError,
// or nil if none found.
func (m *CountUnreadRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *CountUnreadRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Msg

	// no validation rules for Count

	if len(errors) > 0 {
		return CountUnreadRspMultiError(errors)
	}

	return nil
}

// CountUnreadRspMultiError is an error wrapping multiple validation errors
// returned by CountUnreadRsp.ValidateAll() if the designated constraints
// aren't met.
type CountUnreadRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CountUnreadRspMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CountUnreadRspMultiError) AllErrors() []error { return m }

// CountUnreadRspValidationError is the validation error returned by
// CountUnreadRsp.Validate if the designated constraints aren't met.
type CountUnreadRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CountUnreadRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CountUnreadRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CountUnreadRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CountUnreadRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CountUnreadRspValidationError) ErrorName() string { return "CountUnreadRspValidationError" }

// Error satisfies the builtin error interface
func (e CountUnreadRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCountUnreadRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CountUnreadRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CountUnreadRspValidationError{}
