// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: sys_mfa.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SysMfa_Status_FullMethodName  = "/api.admin.v1.SysMfa/Status"
	SysMfa_Enroll_FullMethodName  = "/api.admin.v1.SysMfa/Enroll"
	SysMfa_Enable_FullMethodName  = "/api.admin.v1.SysMfa/Enable"
	SysMfa_Disable_FullMethodName = "/api.admin.v1.SysMfa/Disable"
	SysMfa_Reset_FullMethodName   = "/api.admin.v1.SysMfa/Reset"
	SysMfa_Verify_FullMethodName  = "/api.admin.v1.SysMfa/Verify"
)

// SysMfaClient is the client API for SysMfa service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MFA TOTP 双因素认证
// R26 接入（设计 docs/design/2026-09-12-mfa-totp-integration.md，参考 api-admin feature/mfa-totp）：
//   - 两段式登录：密码 → MfaPending 5min token → Verify 校验动态码/恢复码 → 正式 token
//   - 绑定/解绑/恢复码/管理员重置；默认不启用（auth.mfa.enabled=false）
type SysMfaClient interface {
	// 查询当前用户 TOTP 状态（available=总开关，enabled=本人是否已绑定）
	Status(ctx context.Context, in *MfaStatusReq, opts ...grpc.CallOption) (*MfaStatusRsp, error)
	// 生成 TOTP 密钥与 otpauth URI（待确认，5 分钟会话缓存）
	Enroll(ctx context.Context, in *MfaEnrollReq, opts ...grpc.CallOption) (*MfaEnrollRsp, error)
	// 校验动态码并启用（返回一次性恢复码）
	Enable(ctx context.Context, in *MfaCodeReq, opts ...grpc.CallOption) (*MfaEnableRsp, error)
	// 关闭（需动态码或恢复码二次确认）
	Disable(ctx context.Context, in *MfaCodeReq, opts ...grpc.CallOption) (*MfaRsp, error)
	// 管理员重置指定用户 TOTP
	Reset(ctx context.Context, in *MfaResetReq, opts ...grpc.CallOption) (*MfaRsp, error)
	// 两段式登录二次验证：MfaPending token + 动态码/恢复码 → 正式 token（公开，白名单）
	Verify(ctx context.Context, in *MfaVerifyReq, opts ...grpc.CallOption) (*MfaVerifyRsp, error)
}

type sysMfaClient struct {
	cc grpc.ClientConnInterface
}

func NewSysMfaClient(cc grpc.ClientConnInterface) SysMfaClient {
	return &sysMfaClient{cc}
}

func (c *sysMfaClient) Status(ctx context.Context, in *MfaStatusReq, opts ...grpc.CallOption) (*MfaStatusRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MfaStatusRsp)
	err := c.cc.Invoke(ctx, SysMfa_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysMfaClient) Enroll(ctx context.Context, in *MfaEnrollReq, opts ...grpc.CallOption) (*MfaEnrollRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MfaEnrollRsp)
	err := c.cc.Invoke(ctx, SysMfa_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysMfaClient) Enable(ctx context.Context, in *MfaCodeReq, opts ...grpc.CallOption) (*MfaEnableRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MfaEnableRsp)
	err := c.cc.Invoke(ctx, SysMfa_Enable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysMfaClient) Disable(ctx context.Context, in *MfaCodeReq, opts ...grpc.CallOption) (*MfaRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MfaRsp)
	err := c.cc.Invoke(ctx, SysMfa_Disable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysMfaClient) Reset(ctx context.Context, in *MfaResetReq, opts ...grpc.CallOption) (*MfaRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MfaRsp)
	err := c.cc.Invoke(ctx, SysMfa_Reset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysMfaClient) Verify(ctx context.Context, in *MfaVerifyReq, opts ...grpc.CallOption) (*MfaVerifyRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MfaVerifyRsp)
	err := c.cc.Invoke(ctx, SysMfa_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysMfaServer is the server API for SysMfa service.
// All implementations must embed UnimplementedSysMfaServer
// for forward compatibility.
//
// MFA TOTP 双因素认证
// R26 接入（设计 docs/design/2026-09-12-mfa-totp-integration.md，参考 api-admin feature/mfa-totp）：
//   - 两段式登录：密码 → MfaPending 5min token → Verify 校验动态码/恢复码 → 正式 token
//   - 绑定/解绑/恢复码/管理员重置；默认不启用（auth.mfa.enabled=false）
type SysMfaServer interface {
	// 查询当前用户 TOTP 状态（available=总开关，enabled=本人是否已绑定）
	Status(context.Context, *MfaStatusReq) (*MfaStatusRsp, error)
	// 生成 TOTP 密钥与 otpauth URI（待确认，5 分钟会话缓存）
	Enroll(context.Context, *MfaEnrollReq) (*MfaEnrollRsp, error)
	// 校验动态码并启用（返回一次性恢复码）
	Enable(context.Context, *MfaCodeReq) (*MfaEnableRsp, error)
	// 关闭（需动态码或恢复码二次确认）
	Disable(context.Context, *MfaCodeReq) (*MfaRsp, error)
	// 管理员重置指定用户 TOTP
	Reset(context.Context, *MfaResetReq) (*MfaRsp, error)
	// 两段式登录二次验证：MfaPending token + 动态码/恢复码 → 正式 token（公开，白名单）
	Verify(context.Context, *MfaVerifyReq) (*MfaVerifyRsp, error)
	mustEmbedUnimplementedSysMfaServer()
}

// UnimplementedSysMfaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSysMfaServer struct{}

func (UnimplementedSysMfaServer) Status(context.Context, *MfaStatusReq) (*MfaStatusRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedSysMfaServer) Enroll(context.Context, *MfaEnrollReq) (*MfaEnrollRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedSysMfaServer) Enable(context.Context, *MfaCodeReq) (*MfaEnableRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method Enable not implemented")
}
func (UnimplementedSysMfaServer) Disable(context.Context, *MfaCodeReq) (*MfaRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method Disable not implemented")
}
func (UnimplementedSysMfaServer) Reset(context.Context, *MfaResetReq) (*MfaRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedSysMfaServer) Verify(context.Context, *MfaVerifyReq) (*MfaVerifyRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedSysMfaServer) mustEmbedUnimplementedSysMfaServer() {}
func (UnimplementedSysMfaServer) testEmbeddedByValue()                {}

// UnsafeSysMfaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SysMfaServer will
// result in compilation errors.
type UnsafeSysMfaServer interface {
	mustEmbedUnimplementedSysMfaServer()
}

func RegisterSysMfaServer(s grpc.ServiceRegistrar, srv SysMfaServer) {
	// If the following call panics, it indicates UnimplementedSysMfaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SysMfa_ServiceDesc, srv)
}

func _SysMfa_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MfaStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysMfaServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysMfa_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysMfaServer).Status(ctx, req.(*MfaStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysMfa_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MfaEnrollReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysMfaServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysMfa_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysMfaServer).Enroll(ctx, req.(*MfaEnrollReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysMfa_Enable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MfaCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysMfaServer).Enable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysMfa_Enable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysMfaServer).Enable(ctx, req.(*MfaCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysMfa_Disable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MfaCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysMfaServer).Disable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysMfa_Disable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysMfaServer).Disable(ctx, req.(*MfaCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysMfa_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MfaResetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysMfaServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysMfa_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysMfaServer).Reset(ctx, req.(*MfaResetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysMfa_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MfaVerifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysMfaServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysMfa_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysMfaServer).Verify(ctx, req.(*MfaVerifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SysMfa_ServiceDesc is the grpc.ServiceDesc for SysMfa service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SysMfa_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.admin.v1.SysMfa",
	HandlerType: (*SysMfaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _SysMfa_Status_Handler,
		},
		{
			MethodName: "Enroll",
			Handler:    _SysMfa_Enroll_Handler,
		},
		{
			MethodName: "Enable",
			Handler:    _SysMfa_Enable_Handler,
		},
		{
			MethodName: "Disable",
			Handler:    _SysMfa_Disable_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _SysMfa_Reset_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _SysMfa_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sys_mfa.proto",
}
