// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v3/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 二因素认证未开启（总开关关闭，接口不可用）
func IsMfaDisabled(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == SysMfaErrorReason_MFA_DISABLED.String() && e.Code == 400
}

// 二因素认证未开启（总开关关闭，接口不可用）
func ErrorMfaDisabled(format string, args ...interface{}) *errors.Error {
	return errors.New(400, SysMfaErrorReason_MFA_DISABLED.String(), fmt.Sprintf(format, args...))
}

// 用户已开启二因素，重复绑定
func IsMfaAlreadyEnabled(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == SysMfaErrorReason_MFA_ALREADY_ENABLED.String() && e.Code == 400
}

// 用户已开启二因素，重复绑定
func ErrorMfaAlreadyEnabled(format string, args ...interface{}) *errors.Error {
	return errors.New(400, SysMfaErrorReason_MFA_ALREADY_ENABLED.String(), fmt.Sprintf(format, args...))
}

// 用户未开启二因素（关闭/解绑时）
func IsMfaNotEnabled(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == SysMfaErrorReason_MFA_NOT_ENABLED.String() && e.Code == 400
}

// 用户未开启二因素（关闭/解绑时）
func ErrorMfaNotEnabled(format string, args ...interface{}) *errors.Error {
	return errors.New(400, SysMfaErrorReason_MFA_NOT_ENABLED.String(), fmt.Sprintf(format, args...))
}

// 动态码或恢复码错误/已过期
func IsMfaVerifyFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == SysMfaErrorReason_MFA_VERIFY_FAILED.String() && e.Code == 400
}

// 动态码或恢复码错误/已过期
func ErrorMfaVerifyFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(400, SysMfaErrorReason_MFA_VERIFY_FAILED.String(), fmt.Sprintf(format, args...))
}

// 绑定会话过期（enroll 后 5 分钟内未完成 enable）
func IsMfaEnrollExpired(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == SysMfaErrorReason_MFA_ENROLL_EXPIRED.String() && e.Code == 400
}

// 绑定会话过期（enroll 后 5 分钟内未完成 enable）
func ErrorMfaEnrollExpired(format string, args ...interface{}) *errors.Error {
	return errors.New(400, SysMfaErrorReason_MFA_ENROLL_EXPIRED.String(), fmt.Sprintf(format, args...))
}

// 强制绑定：mfa.required=true 且用户未绑定，需先完成绑定（409 引导前端跳转）
func IsMfaRequired(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == SysMfaErrorReason_MFA_REQUIRED.String() && e.Code == 409
}

// 强制绑定：mfa.required=true 且用户未绑定，需先完成绑定（409 引导前端跳转）
func ErrorMfaRequired(format string, args ...interface{}) *errors.Error {
	return errors.New(409, SysMfaErrorReason_MFA_REQUIRED.String(), fmt.Sprintf(format, args...))
}

// 用户不存在（管理员重置目标不存在）
func IsMfaNoUser(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == SysMfaErrorReason_MFA_NO_USER.String() && e.Code == 404
}

// 用户不存在（管理员重置目标不存在）
func ErrorMfaNoUser(format string, args ...interface{}) *errors.Error {
	return errors.New(404, SysMfaErrorReason_MFA_NO_USER.String(), fmt.Sprintf(format, args...))
}
