// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: sys_mfa.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MfaStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MfaStatusReq) Reset() {
	*x = MfaStatusReq{}
	mi := &file_sys_mfa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MfaStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MfaStatusReq) ProtoMessage() {}

func (x *MfaStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_mfa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MfaStatusReq.ProtoReflect.Descriptor instead.
func (*MfaStatusReq) Descriptor() ([]byte, []int) {
	return file_sys_mfa_proto_rawDescGZIP(), []int{0}
}

type MfaStatusRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"` // 功能总开关（auth.mfa.enabled）
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`     // 本人是否已绑定 TOTP
	BoundAt       int64                  `protobuf:"varint,3,opt,name=boundAt,proto3" json:"boundAt,omitempty"`     // 绑定时间（毫秒时间戳，未绑定为 0）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MfaStatusRsp) Reset() {
	*x = MfaStatusRsp{}
	mi := &file_sys_mfa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MfaStatusRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MfaStatusRsp) ProtoMessage() {}

func (x *MfaStatusRsp) ProtoReflect() protoreflect.Message {
	mi := &file_sys_mfa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MfaStatusRsp.ProtoReflect.Descriptor instead.
func (*MfaStatusRsp) Descriptor() ([]byte, []int) {
	return file_sys_mfa_proto_rawDescGZIP(), []int{1}
}

func (x *MfaStatusRsp) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *MfaStatusRsp) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *MfaStatusRsp) GetBoundAt() int64 {
	if x != nil {
		return x.BoundAt
	}
	return 0
}

type MfaEnrollReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // otpauth AccountName（一般传登录用户名）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MfaEnrollReq) Reset() {
	*x = MfaEnrollReq{}
	mi := &file_sys_mfa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MfaEnrollReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MfaEnrollReq) ProtoMessage() {}

func (x *MfaEnrollReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_mfa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MfaEnrollReq.ProtoReflect.Descriptor instead.
func (*MfaEnrollReq) Descriptor() ([]byte, []int) {
	return file_sys_mfa_proto_rawDescGZIP(), []int{2}
}

func (x *MfaEnrollReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type MfaEnrollRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"` // TOTP secret（仅本次返回，用于扫码/手工输入）
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`       // otpauth://totp/ URI（二维码内容）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MfaEnrollRsp) Reset() {
	*x = MfaEnrollRsp{}
	mi := &file_sys_mfa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MfaEnrollRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MfaEnrollRsp) ProtoMessage() {}

func (x *MfaEnrollRsp) ProtoReflect() protoreflect.Message {
	mi := &file_sys_mfa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MfaEnrollRsp.ProtoReflect.Descriptor instead.
func (*MfaEnrollRsp) Descriptor() ([]byte, []int) {
	return file_sys_mfa_proto_rawDescGZIP(), []int{3}
}

func (x *MfaEnrollRsp) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *MfaEnrollRsp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type MfaCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // 动态码或恢复码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MfaCodeReq) Reset() {
	*x = MfaCodeReq{}
	mi := &file_sys_mfa_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MfaCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MfaCodeReq) ProtoMessage() {}

func (x *MfaCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_mfa_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MfaCodeReq.ProtoReflect.Descriptor instead.
func (*MfaCodeReq) Descriptor() ([]byte, []int) {
	return file_sys_mfa_proto_rawDescGZIP(), []int{4}
}

func (x *MfaCodeReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type MfaEnableRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecoveryCodes []string               `protobuf:"bytes,1,rep,name=recoveryCodes,proto3" json:"recoveryCodes,omitempty"` // 恢复码（仅本次返回，请妥善保存）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MfaEnableRsp) Reset() {
	*x = MfaEnableRsp{}
	mi := &file_sys_mfa_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MfaEnableRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MfaEnableRsp) ProtoMessage() {}

func (x *MfaEnableRsp) ProtoReflect() protoreflect.Message {
	mi := &file_sys_mfa_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MfaEnableRsp.ProtoReflect.Descriptor instead.
func (*MfaEnableRsp) Descriptor() ([]byte, []int) {
	return file_sys_mfa_proto_rawDescGZIP(), []int{5}
}

func (x *MfaEnableRsp) GetRecoveryCodes() []string {
	if x != nil {
		return x.RecoveryCodes
	}
	return nil
}

type MfaRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MfaRsp) Reset() {
	*x = MfaRsp{}
	mi := &file_sys_mfa_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MfaRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MfaRsp) ProtoMessage() {}

func (x *MfaRsp) ProtoReflect() protoreflect.Message {
	mi := &file_sys_mfa_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MfaRsp.ProtoReflect.Descriptor instead.
func (*MfaRsp) Descriptor() ([]byte, []int) {
	return file_sys_mfa_proto_rawDescGZIP(), []int{6}
}

type MfaResetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"` // 目标用户 ID（管理员操作）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MfaResetReq) Reset() {
	*x = MfaResetReq{}
	mi := &file_sys_mfa_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MfaResetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MfaResetReq) ProtoMessage() {}

func (x *MfaResetReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_mfa_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MfaResetReq.ProtoReflect.Descriptor instead.
func (*MfaResetReq) Descriptor() ([]byte, []int) {
	return file_sys_mfa_proto_rawDescGZIP(), []int{7}
}

func (x *MfaResetReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type MfaVerifyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MfaToken      string                 `protobuf:"bytes,1,opt,name=mfaToken,proto3" json:"mfaToken,omitempty"` // 两段式登录第 1 步的 MfaPending token
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`         // 动态码或恢复码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MfaVerifyReq) Reset() {
	*x = MfaVerifyReq{}
	mi := &file_sys_mfa_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MfaVerifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MfaVerifyReq) ProtoMessage() {}

func (x *MfaVerifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_mfa_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MfaVerifyReq.ProtoReflect.Descriptor instead.
func (*MfaVerifyReq) Descriptor() ([]byte, []int) {
	return file_sys_mfa_proto_rawDescGZIP(), []int{8}
}

func (x *MfaVerifyReq) GetMfaToken() string {
	if x != nil {
		return x.MfaToken
	}
	return ""
}

func (x *MfaVerifyReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type MfaVerifyRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`    // 正式登录 token
	Expire        int64                  `protobuf:"varint,2,opt,name=expire,proto3" json:"expire,omitempty"` // 过期时间（毫秒时间戳）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MfaVerifyRsp) Reset() {
	*x = MfaVerifyRsp{}
	mi := &file_sys_mfa_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MfaVerifyRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MfaVerifyRsp) ProtoMessage() {}

func (x *MfaVerifyRsp) ProtoReflect() protoreflect.Message {
	mi := &file_sys_mfa_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MfaVerifyRsp.ProtoReflect.Descriptor instead.
func (*MfaVerifyRsp) Descriptor() ([]byte, []int) {
	return file_sys_mfa_proto_rawDescGZIP(), []int{9}
}

func (x *MfaVerifyRsp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MfaVerifyRsp) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

var File_sys_mfa_proto protoreflect.FileDescriptor

const file_sys_mfa_proto_rawDesc = "" +
	"\n" +
	"\rsys_mfa.proto\x12\fapi.admin.v1\x1a\x1cgoogle/api/annotations.proto\"\x0e\n" +
	"\fMfaStatusReq\"`\n" +
	"\fMfaStatusRsp\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12\x18\n" +
	"\aboundAt\x18\x03 \x01(\x03R\aboundAt\"*\n" +
	"\fMfaEnrollReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"8\n" +
	"\fMfaEnrollRsp\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\" \n" +
	"\n" +
	"MfaCodeReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"4\n" +
	"\fMfaEnableRsp\x12$\n" +
	"\rrecoveryCodes\x18\x01 \x03(\tR\rrecoveryCodes\"\b\n" +
	"\x06MfaRsp\"%\n" +
	"\vMfaResetReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\">\n" +
	"\fMfaVerifyReq\x12\x1a\n" +
	"\bmfaToken\x18\x01 \x01(\tR\bmfaToken\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"<\n" +
	"\fMfaVerifyRsp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06expire\x18\x02 \x01(\x03R\x06expire2\x90\x04\n" +
	"\x06SysMfa\x12U\n" +
	"\x06Status\x12\x1a.api.admin.v1.MfaStatusReq\x1a\x1a.api.admin.v1.MfaStatusRsp\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/mfa/status\x12X\n" +
	"\x06Enroll\x12\x1a.api.admin.v1.MfaEnrollReq\x1a\x1a.api.admin.v1.MfaEnrollRsp\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/mfa/enroll\x12V\n" +
	"\x06Enable\x12\x18.api.admin.v1.MfaCodeReq\x1a\x1a.api.admin.v1.MfaEnableRsp\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/mfa/enable\x12R\n" +
	"\aDisable\x12\x18.api.admin.v1.MfaCodeReq\x1a\x14.api.admin.v1.MfaRsp\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/mfa/disable\x12O\n" +
	"\x05Reset\x12\x19.api.admin.v1.MfaResetReq\x1a\x14.api.admin.v1.MfaRsp\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/mfa/reset\x12X\n" +
	"\x06Verify\x12\x1a.api.admin.v1.MfaVerifyReq\x1a\x1a.api.admin.v1.MfaVerifyRsp\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/mfa/verifyB6Z4github.com/swordkee/kratos-vue-admin/api/admin/v1;v1b\x06proto3"

var (
	file_sys_mfa_proto_rawDescOnce sync.Once
	file_sys_mfa_proto_rawDescData []byte
)

func file_sys_mfa_proto_rawDescGZIP() []byte {
	file_sys_mfa_proto_rawDescOnce.Do(func() {
		file_sys_mfa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sys_mfa_proto_rawDesc), len(file_sys_mfa_proto_rawDesc)))
	})
	return file_sys_mfa_proto_rawDescData
}

var file_sys_mfa_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_sys_mfa_proto_goTypes = []any{
	(*MfaStatusReq)(nil), // 0: api.admin.v1.MfaStatusReq
	(*MfaStatusRsp)(nil), // 1: api.admin.v1.MfaStatusRsp
	(*MfaEnrollReq)(nil), // 2: api.admin.v1.MfaEnrollReq
	(*MfaEnrollRsp)(nil), // 3: api.admin.v1.MfaEnrollRsp
	(*MfaCodeReq)(nil),   // 4: api.admin.v1.MfaCodeReq
	(*MfaEnableRsp)(nil), // 5: api.admin.v1.MfaEnableRsp
	(*MfaRsp)(nil),       // 6: api.admin.v1.MfaRsp
	(*MfaResetReq)(nil),  // 7: api.admin.v1.MfaResetReq
	(*MfaVerifyReq)(nil), // 8: api.admin.v1.MfaVerifyReq
	(*MfaVerifyRsp)(nil), // 9: api.admin.v1.MfaVerifyRsp
}
var file_sys_mfa_proto_depIdxs = []int32{
	0, // 0: api.admin.v1.SysMfa.Status:input_type -> api.admin.v1.MfaStatusReq
	2, // 1: api.admin.v1.SysMfa.Enroll:input_type -> api.admin.v1.MfaEnrollReq
	4, // 2: api.admin.v1.SysMfa.Enable:input_type -> api.admin.v1.MfaCodeReq
	4, // 3: api.admin.v1.SysMfa.Disable:input_type -> api.admin.v1.MfaCodeReq
	7, // 4: api.admin.v1.SysMfa.Reset:input_type -> api.admin.v1.MfaResetReq
	8, // 5: api.admin.v1.SysMfa.Verify:input_type -> api.admin.v1.MfaVerifyReq
	1, // 6: api.admin.v1.SysMfa.Status:output_type -> api.admin.v1.MfaStatusRsp
	3, // 7: api.admin.v1.SysMfa.Enroll:output_type -> api.admin.v1.MfaEnrollRsp
	5, // 8: api.admin.v1.SysMfa.Enable:output_type -> api.admin.v1.MfaEnableRsp
	6, // 9: api.admin.v1.SysMfa.Disable:output_type -> api.admin.v1.MfaRsp
	6, // 10: api.admin.v1.SysMfa.Reset:output_type -> api.admin.v1.MfaRsp
	9, // 11: api.admin.v1.SysMfa.Verify:output_type -> api.admin.v1.MfaVerifyRsp
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sys_mfa_proto_init() }
func file_sys_mfa_proto_init() {
	if File_sys_mfa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sys_mfa_proto_rawDesc), len(file_sys_mfa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sys_mfa_proto_goTypes,
		DependencyIndexes: file_sys_mfa_proto_depIdxs,
		MessageInfos:      file_sys_mfa_proto_msgTypes,
	}.Build()
	File_sys_mfa_proto = out.File
	file_sys_mfa_proto_goTypes = nil
	file_sys_mfa_proto_depIdxs = nil
}
