// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: sys_mfa_error.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v3/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TOTP 双因素认证错误码（R26 接入，设计 docs/design/2026-09-12-mfa-totp-integration.md）
type SysMfaErrorReason int32

const (
	// 二因素认证未开启（总开关关闭，接口不可用）
	SysMfaErrorReason_MFA_DISABLED SysMfaErrorReason = 0
	// 用户已开启二因素，重复绑定
	SysMfaErrorReason_MFA_ALREADY_ENABLED SysMfaErrorReason = 1
	// 用户未开启二因素（关闭/解绑时）
	SysMfaErrorReason_MFA_NOT_ENABLED SysMfaErrorReason = 2
	// 动态码或恢复码错误/已过期
	SysMfaErrorReason_MFA_VERIFY_FAILED SysMfaErrorReason = 3
	// 绑定会话过期（enroll 后 5 分钟内未完成 enable）
	SysMfaErrorReason_MFA_ENROLL_EXPIRED SysMfaErrorReason = 4
	// 强制绑定：mfa.required=true 且用户未绑定，需先完成绑定（409 引导前端跳转）
	SysMfaErrorReason_MFA_REQUIRED SysMfaErrorReason = 5
	// 用户不存在（管理员重置目标不存在）
	SysMfaErrorReason_MFA_NO_USER SysMfaErrorReason = 6
)

// Enum value maps for SysMfaErrorReason.
var (
	SysMfaErrorReason_name = map[int32]string{
		0: "MFA_DISABLED",
		1: "MFA_ALREADY_ENABLED",
		2: "MFA_NOT_ENABLED",
		3: "MFA_VERIFY_FAILED",
		4: "MFA_ENROLL_EXPIRED",
		5: "MFA_REQUIRED",
		6: "MFA_NO_USER",
	}
	SysMfaErrorReason_value = map[string]int32{
		"MFA_DISABLED":        0,
		"MFA_ALREADY_ENABLED": 1,
		"MFA_NOT_ENABLED":     2,
		"MFA_VERIFY_FAILED":   3,
		"MFA_ENROLL_EXPIRED":  4,
		"MFA_REQUIRED":        5,
		"MFA_NO_USER":         6,
	}
)

func (x SysMfaErrorReason) Enum() *SysMfaErrorReason {
	p := new(SysMfaErrorReason)
	*p = x
	return p
}

func (x SysMfaErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SysMfaErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_sys_mfa_error_proto_enumTypes[0].Descriptor()
}

func (SysMfaErrorReason) Type() protoreflect.EnumType {
	return &file_sys_mfa_error_proto_enumTypes[0]
}

func (x SysMfaErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SysMfaErrorReason.Descriptor instead.
func (SysMfaErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_sys_mfa_error_proto_rawDescGZIP(), []int{0}
}

var File_sys_mfa_error_proto protoreflect.FileDescriptor

const file_sys_mfa_error_proto_rawDesc = "" +
	"\n" +
	"\x13sys_mfa_error.proto\x12\fapi.admin.v1\x1a\x13errors/errors.proto*\xd5\x01\n" +
	"\x11SysMfaErrorReason\x12\x16\n" +
	"\fMFA_DISABLED\x10\x00\x1a\x04\xa8E\x90\x03\x12\x1d\n" +
	"\x13MFA_ALREADY_ENABLED\x10\x01\x1a\x04\xa8E\x90\x03\x12\x19\n" +
	"\x0fMFA_NOT_ENABLED\x10\x02\x1a\x04\xa8E\x90\x03\x12\x1b\n" +
	"\x11MFA_VERIFY_FAILED\x10\x03\x1a\x04\xa8E\x90\x03\x12\x1c\n" +
	"\x12MFA_ENROLL_EXPIRED\x10\x04\x1a\x04\xa8E\x90\x03\x12\x16\n" +
	"\fMFA_REQUIRED\x10\x05\x1a\x04\xa8E\x99\x03\x12\x15\n" +
	"\vMFA_NO_USER\x10\x06\x1a\x04\xa8E\x94\x03\x1a\x04\xa0E\x90\x03B6Z4github.com/swordkee/kratos-vue-admin/api/admin/v1;v1b\x06proto3"

var (
	file_sys_mfa_error_proto_rawDescOnce sync.Once
	file_sys_mfa_error_proto_rawDescData []byte
)

func file_sys_mfa_error_proto_rawDescGZIP() []byte {
	file_sys_mfa_error_proto_rawDescOnce.Do(func() {
		file_sys_mfa_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sys_mfa_error_proto_rawDesc), len(file_sys_mfa_error_proto_rawDesc)))
	})
	return file_sys_mfa_error_proto_rawDescData
}

var file_sys_mfa_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sys_mfa_error_proto_goTypes = []any{
	(SysMfaErrorReason)(0), // 0: api.admin.v1.SysMfaErrorReason
}
var file_sys_mfa_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sys_mfa_error_proto_init() }
func file_sys_mfa_error_proto_init() {
	if File_sys_mfa_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sys_mfa_error_proto_rawDesc), len(file_sys_mfa_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sys_mfa_error_proto_goTypes,
		DependencyIndexes: file_sys_mfa_error_proto_depIdxs,
		EnumInfos:         file_sys_mfa_error_proto_enumTypes,
	}.Build()
	File_sys_mfa_error_proto = out.File
	file_sys_mfa_error_proto_goTypes = nil
	file_sys_mfa_error_proto_depIdxs = nil
}
