// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.14.0
// source: sysuser_error.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SysUserErrorReason int32

const (
	// 为某个枚举单独设置错误码
	SysUserErrorReason_USER_NOT_FOUND    SysUserErrorReason = 0
	SysUserErrorReason_CONTENT_MISSING   SysUserErrorReason = 1
	SysUserErrorReason_LOGIN_FAIL        SysUserErrorReason = 2
	SysUserErrorReason_CAPTCHA_INVALID   SysUserErrorReason = 3
	SysUserErrorReason_INTERNAL_ERR      SysUserErrorReason = 4
	SysUserErrorReason_CODE_NOT_MATCH    SysUserErrorReason = 5
	SysUserErrorReason_DATABASE_ERR      SysUserErrorReason = 6
	SysUserErrorReason_TENTCENT_API      SysUserErrorReason = 7
	SysUserErrorReason_BizError_API      SysUserErrorReason = 8
	SysUserErrorReason_ACCOUNT_FORBIDDEN SysUserErrorReason = 9
	SysUserErrorReason_ROLE_BIND_ACCOUNT SysUserErrorReason = 10
	SysUserErrorReason_ACCOUNT_EXISTED   SysUserErrorReason = 11
)

// Enum value maps for SysUserErrorReason.
var (
	SysUserErrorReason_name = map[int32]string{
		0:  "USER_NOT_FOUND",
		1:  "CONTENT_MISSING",
		2:  "LOGIN_FAIL",
		3:  "CAPTCHA_INVALID",
		4:  "INTERNAL_ERR",
		5:  "CODE_NOT_MATCH",
		6:  "DATABASE_ERR",
		7:  "TENTCENT_API",
		8:  "BizError_API",
		9:  "ACCOUNT_FORBIDDEN",
		10: "ROLE_BIND_ACCOUNT",
		11: "ACCOUNT_EXISTED",
	}
	SysUserErrorReason_value = map[string]int32{
		"USER_NOT_FOUND":    0,
		"CONTENT_MISSING":   1,
		"LOGIN_FAIL":        2,
		"CAPTCHA_INVALID":   3,
		"INTERNAL_ERR":      4,
		"CODE_NOT_MATCH":    5,
		"DATABASE_ERR":      6,
		"TENTCENT_API":      7,
		"BizError_API":      8,
		"ACCOUNT_FORBIDDEN": 9,
		"ROLE_BIND_ACCOUNT": 10,
		"ACCOUNT_EXISTED":   11,
	}
)

func (x SysUserErrorReason) Enum() *SysUserErrorReason {
	p := new(SysUserErrorReason)
	*p = x
	return p
}

func (x SysUserErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SysUserErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_sysuser_error_proto_enumTypes[0].Descriptor()
}

func (SysUserErrorReason) Type() protoreflect.EnumType {
	return &file_sysuser_error_proto_enumTypes[0]
}

func (x SysUserErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SysUserErrorReason.Descriptor instead.
func (SysUserErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_sysuser_error_proto_rawDescGZIP(), []int{0}
}

var File_sysuser_error_proto protoreflect.FileDescriptor

const file_sysuser_error_proto_rawDesc = "" +
	"\n" +
	"\x13sysuser_error.proto\x12\fapi.admin.v1\x1a\x13errors/errors.proto*\xcf\x02\n" +
	"\x12SysUserErrorReason\x12\x18\n" +
	"\x0eUSER_NOT_FOUND\x10\x00\x1a\x04\xa8E\x94\x03\x12\x19\n" +
	"\x0fCONTENT_MISSING\x10\x01\x1a\x04\xa8E\x90\x03\x12\x14\n" +
	"\n" +
	"LOGIN_FAIL\x10\x02\x1a\x04\xa8E\x90\x03\x12\x19\n" +
	"\x0fCAPTCHA_INVALID\x10\x03\x1a\x04\xa8E\x90\x03\x12\x16\n" +
	"\fINTERNAL_ERR\x10\x04\x1a\x04\xa8E\xf4\x03\x12\x18\n" +
	"\x0eCODE_NOT_MATCH\x10\x05\x1a\x04\xa8E\x90\x03\x12\x16\n" +
	"\fDATABASE_ERR\x10\x06\x1a\x04\xa8E\xf4\x03\x12\x16\n" +
	"\fTENTCENT_API\x10\a\x1a\x04\xa8E\xc8\x01\x12\x16\n" +
	"\fBizError_API\x10\b\x1a\x04\xa8E\xcc\x01\x12\x1b\n" +
	"\x11ACCOUNT_FORBIDDEN\x10\t\x1a\x04\xa8E\xc8\x01\x12\x1b\n" +
	"\x11ROLE_BIND_ACCOUNT\x10\n" +
	"\x1a\x04\xa8E\xc8\x01\x12\x19\n" +
	"\x0fACCOUNT_EXISTED\x10\v\x1a\x04\xa8E\xc8\x01\x1a\x04\xa0E\xf4\x03B6Z4github.com/swordkee/kratos-vue-admin/api/admin/v1;v1b\x06proto3"

var (
	file_sysuser_error_proto_rawDescOnce sync.Once
	file_sysuser_error_proto_rawDescData []byte
)

func file_sysuser_error_proto_rawDescGZIP() []byte {
	file_sysuser_error_proto_rawDescOnce.Do(func() {
		file_sysuser_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sysuser_error_proto_rawDesc), len(file_sysuser_error_proto_rawDesc)))
	})
	return file_sysuser_error_proto_rawDescData
}

var file_sysuser_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sysuser_error_proto_goTypes = []any{
	(SysUserErrorReason)(0), // 0: api.admin.v1.SysUserErrorReason
}
var file_sysuser_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sysuser_error_proto_init() }
func file_sysuser_error_proto_init() {
	if File_sysuser_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sysuser_error_proto_rawDesc), len(file_sysuser_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sysuser_error_proto_goTypes,
		DependencyIndexes: file_sysuser_error_proto_depIdxs,
		EnumInfos:         file_sysuser_error_proto_enumTypes,
	}.Build()
	File_sysuser_error_proto = out.File
	file_sysuser_error_proto_goTypes = nil
	file_sysuser_error_proto_depIdxs = nil
}
