// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.14.0
// source: sysuser.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSysuserAuth = "/api.admin.v1.Sysuser/Auth"
const OperationSysuserChangeStatus = "/api.admin.v1.Sysuser/ChangeStatus"
const OperationSysuserCreateSysuser = "/api.admin.v1.Sysuser/CreateSysuser"
const OperationSysuserDeleteSysuser = "/api.admin.v1.Sysuser/DeleteSysuser"
const OperationSysuserFindCaptcha = "/api.admin.v1.Sysuser/FindCaptcha"
const OperationSysuserFindPostInit = "/api.admin.v1.Sysuser/FindPostInit"
const OperationSysuserFindSysuser = "/api.admin.v1.Sysuser/FindSysuser"
const OperationSysuserFindUserGoogleSecret = "/api.admin.v1.Sysuser/FindUserGoogleSecret"
const OperationSysuserFindUserRolePost = "/api.admin.v1.Sysuser/FindUserRolePost"
const OperationSysuserListSysuser = "/api.admin.v1.Sysuser/ListSysuser"
const OperationSysuserLogin = "/api.admin.v1.Sysuser/Login"
const OperationSysuserLogout = "/api.admin.v1.Sysuser/Logout"
const OperationSysuserUpdatePassword = "/api.admin.v1.Sysuser/UpdatePassword"
const OperationSysuserUpdateSysuser = "/api.admin.v1.Sysuser/UpdateSysuser"

type SysuserHTTPServer interface {
	// Auth 获取用户权限
	Auth(context.Context, *AuthRequest) (*AuthReply, error)
	// ChangeStatus 更新用户状态
	ChangeStatus(context.Context, *ChangeStatusRequest) (*ChangeStatusReply, error)
	// CreateSysuser 创建用户
	CreateSysuser(context.Context, *CreateSysuserRequest) (*CreateSysuserReply, error)
	// DeleteSysuser 删除用户
	DeleteSysuser(context.Context, *DeleteSysuserRequest) (*DeleteSysuserReply, error)
	// FindCaptcha 获取验证码
	FindCaptcha(context.Context, *FindCaptchaRequest) (*FindCaptchaReply, error)
	// FindPostInit 获取岗位
	FindPostInit(context.Context, *FindPostInitRequest) (*FindPostInitReply, error)
	// FindSysuser 获取用户
	FindSysuser(context.Context, *FindSysuserRequest) (*FindSysuserReply, error)
	// FindUserGoogleSecret 生成密钥和二维码
	FindUserGoogleSecret(context.Context, *FindUserGoogleSecretRequest) (*FindUserGoogleSecretReply, error)
	// FindUserRolePost 获取RoPo
	FindUserRolePost(context.Context, *FindUserRolePostRequest) (*FindUserRolePostReply, error)
	// ListSysuser 用户列表
	ListSysuser(context.Context, *ListSysuserRequest) (*ListSysuserReply, error)
	// Login 登入
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	// Logout 登出
	Logout(context.Context, *LogoutRequest) (*LogoutReply, error)
	// UpdatePassword 更新密码
	UpdatePassword(context.Context, *UpdatePasswordRequest) (*UpdatePasswordReply, error)
	// UpdateSysuser 更新用户
	UpdateSysuser(context.Context, *UpdateSysuserRequest) (*UpdateSysuserReply, error)
}

func RegisterSysuserHTTPServer(s *http.Server, srv SysuserHTTPServer) {
	r := s.Route("/")
	r.POST("/system/user", _Sysuser_CreateSysuser0_HTTP_Handler(srv))
	r.PUT("/system/user", _Sysuser_UpdateSysuser0_HTTP_Handler(srv))
	r.DELETE("/system/user/{id}", _Sysuser_DeleteSysuser0_HTTP_Handler(srv))
	r.GET("/system/user/getById/{id}", _Sysuser_FindSysuser0_HTTP_Handler(srv))
	r.GET("/system/user/list", _Sysuser_ListSysuser0_HTTP_Handler(srv))
	r.GET("/system/user/getCaptcha", _Sysuser_FindCaptcha0_HTTP_Handler(srv))
	r.POST("/system/user/login", _Sysuser_Login0_HTTP_Handler(srv))
	r.POST("/system/user/logout", _Sysuser_Logout0_HTTP_Handler(srv))
	r.GET("/system/user/auth", _Sysuser_Auth0_HTTP_Handler(srv))
	r.PUT("/system/user/changeStatus", _Sysuser_ChangeStatus0_HTTP_Handler(srv))
	r.PUT("/system/user/pwd", _Sysuser_UpdatePassword0_HTTP_Handler(srv))
	r.GET("/system/user/getInit", _Sysuser_FindPostInit0_HTTP_Handler(srv))
	r.GET("/system/user/getRoPo", _Sysuser_FindUserRolePost0_HTTP_Handler(srv))
	r.GET("/system/user/secret", _Sysuser_FindUserGoogleSecret0_HTTP_Handler(srv))
}

func _Sysuser_CreateSysuser0_HTTP_Handler(srv SysuserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSysuserRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysuserCreateSysuser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSysuser(ctx, req.(*CreateSysuserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateSysuserReply)
		return ctx.Result(200, reply)
	}
}

func _Sysuser_UpdateSysuser0_HTTP_Handler(srv SysuserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSysuserRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysuserUpdateSysuser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateSysuser(ctx, req.(*UpdateSysuserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateSysuserReply)
		return ctx.Result(200, reply)
	}
}

func _Sysuser_DeleteSysuser0_HTTP_Handler(srv SysuserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteSysuserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysuserDeleteSysuser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteSysuser(ctx, req.(*DeleteSysuserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteSysuserReply)
		return ctx.Result(200, reply)
	}
}

func _Sysuser_FindSysuser0_HTTP_Handler(srv SysuserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FindSysuserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysuserFindSysuser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FindSysuser(ctx, req.(*FindSysuserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FindSysuserReply)
		return ctx.Result(200, reply)
	}
}

func _Sysuser_ListSysuser0_HTTP_Handler(srv SysuserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSysuserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysuserListSysuser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSysuser(ctx, req.(*ListSysuserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSysuserReply)
		return ctx.Result(200, reply)
	}
}

func _Sysuser_FindCaptcha0_HTTP_Handler(srv SysuserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FindCaptchaRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysuserFindCaptcha)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FindCaptcha(ctx, req.(*FindCaptchaRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FindCaptchaReply)
		return ctx.Result(200, reply)
	}
}

func _Sysuser_Login0_HTTP_Handler(srv SysuserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysuserLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Login(ctx, req.(*LoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoginReply)
		return ctx.Result(200, reply)
	}
}

func _Sysuser_Logout0_HTTP_Handler(srv SysuserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LogoutRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysuserLogout)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Logout(ctx, req.(*LogoutRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LogoutReply)
		return ctx.Result(200, reply)
	}
}

func _Sysuser_Auth0_HTTP_Handler(srv SysuserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AuthRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysuserAuth)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Auth(ctx, req.(*AuthRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AuthReply)
		return ctx.Result(200, reply)
	}
}

func _Sysuser_ChangeStatus0_HTTP_Handler(srv SysuserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ChangeStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysuserChangeStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ChangeStatus(ctx, req.(*ChangeStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChangeStatusReply)
		return ctx.Result(200, reply)
	}
}

func _Sysuser_UpdatePassword0_HTTP_Handler(srv SysuserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePasswordRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysuserUpdatePassword)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdatePassword(ctx, req.(*UpdatePasswordRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdatePasswordReply)
		return ctx.Result(200, reply)
	}
}

func _Sysuser_FindPostInit0_HTTP_Handler(srv SysuserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FindPostInitRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysuserFindPostInit)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FindPostInit(ctx, req.(*FindPostInitRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FindPostInitReply)
		return ctx.Result(200, reply)
	}
}

func _Sysuser_FindUserRolePost0_HTTP_Handler(srv SysuserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FindUserRolePostRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysuserFindUserRolePost)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FindUserRolePost(ctx, req.(*FindUserRolePostRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FindUserRolePostReply)
		return ctx.Result(200, reply)
	}
}

func _Sysuser_FindUserGoogleSecret0_HTTP_Handler(srv SysuserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FindUserGoogleSecretRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysuserFindUserGoogleSecret)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FindUserGoogleSecret(ctx, req.(*FindUserGoogleSecretRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FindUserGoogleSecretReply)
		return ctx.Result(200, reply)
	}
}

type SysuserHTTPClient interface {
	// Auth 获取用户权限
	Auth(ctx context.Context, req *AuthRequest, opts ...http.CallOption) (rsp *AuthReply, err error)
	// ChangeStatus 更新用户状态
	ChangeStatus(ctx context.Context, req *ChangeStatusRequest, opts ...http.CallOption) (rsp *ChangeStatusReply, err error)
	// CreateSysuser 创建用户
	CreateSysuser(ctx context.Context, req *CreateSysuserRequest, opts ...http.CallOption) (rsp *CreateSysuserReply, err error)
	// DeleteSysuser 删除用户
	DeleteSysuser(ctx context.Context, req *DeleteSysuserRequest, opts ...http.CallOption) (rsp *DeleteSysuserReply, err error)
	// FindCaptcha 获取验证码
	FindCaptcha(ctx context.Context, req *FindCaptchaRequest, opts ...http.CallOption) (rsp *FindCaptchaReply, err error)
	// FindPostInit 获取岗位
	FindPostInit(ctx context.Context, req *FindPostInitRequest, opts ...http.CallOption) (rsp *FindPostInitReply, err error)
	// FindSysuser 获取用户
	FindSysuser(ctx context.Context, req *FindSysuserRequest, opts ...http.CallOption) (rsp *FindSysuserReply, err error)
	// FindUserGoogleSecret 生成密钥和二维码
	FindUserGoogleSecret(ctx context.Context, req *FindUserGoogleSecretRequest, opts ...http.CallOption) (rsp *FindUserGoogleSecretReply, err error)
	// FindUserRolePost 获取RoPo
	FindUserRolePost(ctx context.Context, req *FindUserRolePostRequest, opts ...http.CallOption) (rsp *FindUserRolePostReply, err error)
	// ListSysuser 用户列表
	ListSysuser(ctx context.Context, req *ListSysuserRequest, opts ...http.CallOption) (rsp *ListSysuserReply, err error)
	// Login 登入
	Login(ctx context.Context, req *LoginRequest, opts ...http.CallOption) (rsp *LoginReply, err error)
	// Logout 登出
	Logout(ctx context.Context, req *LogoutRequest, opts ...http.CallOption) (rsp *LogoutReply, err error)
	// UpdatePassword 更新密码
	UpdatePassword(ctx context.Context, req *UpdatePasswordRequest, opts ...http.CallOption) (rsp *UpdatePasswordReply, err error)
	// UpdateSysuser 更新用户
	UpdateSysuser(ctx context.Context, req *UpdateSysuserRequest, opts ...http.CallOption) (rsp *UpdateSysuserReply, err error)
}

type SysuserHTTPClientImpl struct {
	cc *http.Client
}

func NewSysuserHTTPClient(client *http.Client) SysuserHTTPClient {
	return &SysuserHTTPClientImpl{client}
}

// Auth 获取用户权限
func (c *SysuserHTTPClientImpl) Auth(ctx context.Context, in *AuthRequest, opts ...http.CallOption) (*AuthReply, error) {
	var out AuthReply
	pattern := "/system/user/auth"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSysuserAuth))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ChangeStatus 更新用户状态
func (c *SysuserHTTPClientImpl) ChangeStatus(ctx context.Context, in *ChangeStatusRequest, opts ...http.CallOption) (*ChangeStatusReply, error) {
	var out ChangeStatusReply
	pattern := "/system/user/changeStatus"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSysuserChangeStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateSysuser 创建用户
func (c *SysuserHTTPClientImpl) CreateSysuser(ctx context.Context, in *CreateSysuserRequest, opts ...http.CallOption) (*CreateSysuserReply, error) {
	var out CreateSysuserReply
	pattern := "/system/user"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSysuserCreateSysuser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteSysuser 删除用户
func (c *SysuserHTTPClientImpl) DeleteSysuser(ctx context.Context, in *DeleteSysuserRequest, opts ...http.CallOption) (*DeleteSysuserReply, error) {
	var out DeleteSysuserReply
	pattern := "/system/user/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSysuserDeleteSysuser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// FindCaptcha 获取验证码
func (c *SysuserHTTPClientImpl) FindCaptcha(ctx context.Context, in *FindCaptchaRequest, opts ...http.CallOption) (*FindCaptchaReply, error) {
	var out FindCaptchaReply
	pattern := "/system/user/getCaptcha"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSysuserFindCaptcha))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// FindPostInit 获取岗位
func (c *SysuserHTTPClientImpl) FindPostInit(ctx context.Context, in *FindPostInitRequest, opts ...http.CallOption) (*FindPostInitReply, error) {
	var out FindPostInitReply
	pattern := "/system/user/getInit"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSysuserFindPostInit))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// FindSysuser 获取用户
func (c *SysuserHTTPClientImpl) FindSysuser(ctx context.Context, in *FindSysuserRequest, opts ...http.CallOption) (*FindSysuserReply, error) {
	var out FindSysuserReply
	pattern := "/system/user/getById/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSysuserFindSysuser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// FindUserGoogleSecret 生成密钥和二维码
func (c *SysuserHTTPClientImpl) FindUserGoogleSecret(ctx context.Context, in *FindUserGoogleSecretRequest, opts ...http.CallOption) (*FindUserGoogleSecretReply, error) {
	var out FindUserGoogleSecretReply
	pattern := "/system/user/secret"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSysuserFindUserGoogleSecret))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// FindUserRolePost 获取RoPo
func (c *SysuserHTTPClientImpl) FindUserRolePost(ctx context.Context, in *FindUserRolePostRequest, opts ...http.CallOption) (*FindUserRolePostReply, error) {
	var out FindUserRolePostReply
	pattern := "/system/user/getRoPo"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSysuserFindUserRolePost))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSysuser 用户列表
func (c *SysuserHTTPClientImpl) ListSysuser(ctx context.Context, in *ListSysuserRequest, opts ...http.CallOption) (*ListSysuserReply, error) {
	var out ListSysuserReply
	pattern := "/system/user/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSysuserListSysuser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Login 登入
func (c *SysuserHTTPClientImpl) Login(ctx context.Context, in *LoginRequest, opts ...http.CallOption) (*LoginReply, error) {
	var out LoginReply
	pattern := "/system/user/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSysuserLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Logout 登出
func (c *SysuserHTTPClientImpl) Logout(ctx context.Context, in *LogoutRequest, opts ...http.CallOption) (*LogoutReply, error) {
	var out LogoutReply
	pattern := "/system/user/logout"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSysuserLogout))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdatePassword 更新密码
func (c *SysuserHTTPClientImpl) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...http.CallOption) (*UpdatePasswordReply, error) {
	var out UpdatePasswordReply
	pattern := "/system/user/pwd"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSysuserUpdatePassword))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateSysuser 更新用户
func (c *SysuserHTTPClientImpl) UpdateSysuser(ctx context.Context, in *UpdateSysuserRequest, opts ...http.CallOption) (*UpdateSysuserReply, error) {
	var out UpdateSysuserReply
	pattern := "/system/user"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSysuserUpdateSysuser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
