// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.14.0
// source: sysuser.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSysUserAuth = "/api.admin.v1.SysUser/Auth"
const OperationSysUserChangeStatus = "/api.admin.v1.SysUser/ChangeStatus"
const OperationSysUserCreateSysUser = "/api.admin.v1.SysUser/CreateSysUser"
const OperationSysUserDeleteSysUser = "/api.admin.v1.SysUser/DeleteSysUser"
const OperationSysUserFindCaptcha = "/api.admin.v1.SysUser/FindCaptcha"
const OperationSysUserFindPostInit = "/api.admin.v1.SysUser/FindPostInit"
const OperationSysUserFindSysUser = "/api.admin.v1.SysUser/FindSysUser"
const OperationSysUserFindUserGoogleSecret = "/api.admin.v1.SysUser/FindUserGoogleSecret"
const OperationSysUserFindUserRolePost = "/api.admin.v1.SysUser/FindUserRolePost"
const OperationSysUserListSysUser = "/api.admin.v1.SysUser/ListSysUser"
const OperationSysUserLogin = "/api.admin.v1.SysUser/Login"
const OperationSysUserLogout = "/api.admin.v1.SysUser/Logout"
const OperationSysUserUpdatePassword = "/api.admin.v1.SysUser/UpdatePassword"
const OperationSysUserUpdateSysUser = "/api.admin.v1.SysUser/UpdateSysUser"

type SysUserHTTPServer interface {
	// Auth 获取用户权限
	Auth(context.Context, *AuthRequest) (*AuthReply, error)
	// ChangeStatus 更新用户状态
	ChangeStatus(context.Context, *ChangeStatusRequest) (*ChangeStatusReply, error)
	// CreateSysUser 创建用户
	CreateSysUser(context.Context, *CreateSysUserRequest) (*CreateSysUserReply, error)
	// DeleteSysUser 删除用户
	DeleteSysUser(context.Context, *DeleteSysUserRequest) (*DeleteSysUserReply, error)
	// FindCaptcha 获取验证码
	FindCaptcha(context.Context, *FindCaptchaRequest) (*FindCaptchaReply, error)
	// FindPostInit 获取岗位
	FindPostInit(context.Context, *FindPostInitRequest) (*FindPostInitReply, error)
	// FindSysUser 获取用户
	FindSysUser(context.Context, *FindSysUserRequest) (*FindSysUserReply, error)
	// FindUserGoogleSecret 生成密钥和二维码
	FindUserGoogleSecret(context.Context, *FindUserGoogleSecretRequest) (*FindUserGoogleSecretReply, error)
	// FindUserRolePost 获取RoPo
	FindUserRolePost(context.Context, *FindUserRolePostRequest) (*FindUserRolePostReply, error)
	// ListSysUser 用户列表
	ListSysUser(context.Context, *ListSysUserRequest) (*ListSysUserReply, error)
	// Login 登入
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	// Logout 登出
	Logout(context.Context, *LogoutRequest) (*LogoutReply, error)
	// UpdatePassword 更新密码
	UpdatePassword(context.Context, *UpdatePasswordRequest) (*UpdatePasswordReply, error)
	// UpdateSysUser 更新用户
	UpdateSysUser(context.Context, *UpdateSysUserRequest) (*UpdateSysUserReply, error)
}

func RegisterSysUserHTTPServer(s *http.Server, srv SysUserHTTPServer) {
	r := s.Route("/")
	r.POST("/system/user", _SysUser_CreateSysUser0_HTTP_Handler(srv))
	r.PUT("/system/user", _SysUser_UpdateSysUser0_HTTP_Handler(srv))
	r.DELETE("/system/user/{id}", _SysUser_DeleteSysUser0_HTTP_Handler(srv))
	r.GET("/system/user/getById/{id}", _SysUser_FindSysUser0_HTTP_Handler(srv))
	r.GET("/system/user/list", _SysUser_ListSysUser0_HTTP_Handler(srv))
	r.GET("/system/user/getCaptcha", _SysUser_FindCaptcha0_HTTP_Handler(srv))
	r.POST("/system/user/login", _SysUser_Login0_HTTP_Handler(srv))
	r.POST("/system/user/logout", _SysUser_Logout0_HTTP_Handler(srv))
	r.GET("/system/user/auth", _SysUser_Auth0_HTTP_Handler(srv))
	r.PUT("/system/user/changeStatus", _SysUser_ChangeStatus0_HTTP_Handler(srv))
	r.PUT("/system/user/pwd", _SysUser_UpdatePassword0_HTTP_Handler(srv))
	r.GET("/system/user/getInit", _SysUser_FindPostInit0_HTTP_Handler(srv))
	r.GET("/system/user/getRoPo", _SysUser_FindUserRolePost0_HTTP_Handler(srv))
	r.GET("/system/user/secret", _SysUser_FindUserGoogleSecret0_HTTP_Handler(srv))
}

func _SysUser_CreateSysUser0_HTTP_Handler(srv SysUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSysUserRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysUserCreateSysUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSysUser(ctx, req.(*CreateSysUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateSysUserReply)
		return ctx.Result(200, reply)
	}
}

func _SysUser_UpdateSysUser0_HTTP_Handler(srv SysUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSysUserRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysUserUpdateSysUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateSysUser(ctx, req.(*UpdateSysUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateSysUserReply)
		return ctx.Result(200, reply)
	}
}

func _SysUser_DeleteSysUser0_HTTP_Handler(srv SysUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteSysUserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysUserDeleteSysUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteSysUser(ctx, req.(*DeleteSysUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteSysUserReply)
		return ctx.Result(200, reply)
	}
}

func _SysUser_FindSysUser0_HTTP_Handler(srv SysUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FindSysUserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysUserFindSysUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FindSysUser(ctx, req.(*FindSysUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FindSysUserReply)
		return ctx.Result(200, reply)
	}
}

func _SysUser_ListSysUser0_HTTP_Handler(srv SysUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSysUserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysUserListSysUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSysUser(ctx, req.(*ListSysUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSysUserReply)
		return ctx.Result(200, reply)
	}
}

func _SysUser_FindCaptcha0_HTTP_Handler(srv SysUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FindCaptchaRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysUserFindCaptcha)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FindCaptcha(ctx, req.(*FindCaptchaRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FindCaptchaReply)
		return ctx.Result(200, reply)
	}
}

func _SysUser_Login0_HTTP_Handler(srv SysUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysUserLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Login(ctx, req.(*LoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoginReply)
		return ctx.Result(200, reply)
	}
}

func _SysUser_Logout0_HTTP_Handler(srv SysUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LogoutRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysUserLogout)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Logout(ctx, req.(*LogoutRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LogoutReply)
		return ctx.Result(200, reply)
	}
}

func _SysUser_Auth0_HTTP_Handler(srv SysUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AuthRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysUserAuth)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Auth(ctx, req.(*AuthRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AuthReply)
		return ctx.Result(200, reply)
	}
}

func _SysUser_ChangeStatus0_HTTP_Handler(srv SysUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ChangeStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysUserChangeStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ChangeStatus(ctx, req.(*ChangeStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChangeStatusReply)
		return ctx.Result(200, reply)
	}
}

func _SysUser_UpdatePassword0_HTTP_Handler(srv SysUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePasswordRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysUserUpdatePassword)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdatePassword(ctx, req.(*UpdatePasswordRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdatePasswordReply)
		return ctx.Result(200, reply)
	}
}

func _SysUser_FindPostInit0_HTTP_Handler(srv SysUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FindPostInitRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysUserFindPostInit)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FindPostInit(ctx, req.(*FindPostInitRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FindPostInitReply)
		return ctx.Result(200, reply)
	}
}

func _SysUser_FindUserRolePost0_HTTP_Handler(srv SysUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FindUserRolePostRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysUserFindUserRolePost)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FindUserRolePost(ctx, req.(*FindUserRolePostRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FindUserRolePostReply)
		return ctx.Result(200, reply)
	}
}

func _SysUser_FindUserGoogleSecret0_HTTP_Handler(srv SysUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FindUserGoogleSecretRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSysUserFindUserGoogleSecret)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FindUserGoogleSecret(ctx, req.(*FindUserGoogleSecretRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FindUserGoogleSecretReply)
		return ctx.Result(200, reply)
	}
}

type SysUserHTTPClient interface {
	// Auth 获取用户权限
	Auth(ctx context.Context, req *AuthRequest, opts ...http.CallOption) (rsp *AuthReply, err error)
	// ChangeStatus 更新用户状态
	ChangeStatus(ctx context.Context, req *ChangeStatusRequest, opts ...http.CallOption) (rsp *ChangeStatusReply, err error)
	// CreateSysUser 创建用户
	CreateSysUser(ctx context.Context, req *CreateSysUserRequest, opts ...http.CallOption) (rsp *CreateSysUserReply, err error)
	// DeleteSysUser 删除用户
	DeleteSysUser(ctx context.Context, req *DeleteSysUserRequest, opts ...http.CallOption) (rsp *DeleteSysUserReply, err error)
	// FindCaptcha 获取验证码
	FindCaptcha(ctx context.Context, req *FindCaptchaRequest, opts ...http.CallOption) (rsp *FindCaptchaReply, err error)
	// FindPostInit 获取岗位
	FindPostInit(ctx context.Context, req *FindPostInitRequest, opts ...http.CallOption) (rsp *FindPostInitReply, err error)
	// FindSysUser 获取用户
	FindSysUser(ctx context.Context, req *FindSysUserRequest, opts ...http.CallOption) (rsp *FindSysUserReply, err error)
	// FindUserGoogleSecret 生成密钥和二维码
	FindUserGoogleSecret(ctx context.Context, req *FindUserGoogleSecretRequest, opts ...http.CallOption) (rsp *FindUserGoogleSecretReply, err error)
	// FindUserRolePost 获取RoPo
	FindUserRolePost(ctx context.Context, req *FindUserRolePostRequest, opts ...http.CallOption) (rsp *FindUserRolePostReply, err error)
	// ListSysUser 用户列表
	ListSysUser(ctx context.Context, req *ListSysUserRequest, opts ...http.CallOption) (rsp *ListSysUserReply, err error)
	// Login 登入
	Login(ctx context.Context, req *LoginRequest, opts ...http.CallOption) (rsp *LoginReply, err error)
	// Logout 登出
	Logout(ctx context.Context, req *LogoutRequest, opts ...http.CallOption) (rsp *LogoutReply, err error)
	// UpdatePassword 更新密码
	UpdatePassword(ctx context.Context, req *UpdatePasswordRequest, opts ...http.CallOption) (rsp *UpdatePasswordReply, err error)
	// UpdateSysUser 更新用户
	UpdateSysUser(ctx context.Context, req *UpdateSysUserRequest, opts ...http.CallOption) (rsp *UpdateSysUserReply, err error)
}

type SysUserHTTPClientImpl struct {
	cc *http.Client
}

func NewSysUserHTTPClient(client *http.Client) SysUserHTTPClient {
	return &SysUserHTTPClientImpl{client}
}

// Auth 获取用户权限
func (c *SysUserHTTPClientImpl) Auth(ctx context.Context, in *AuthRequest, opts ...http.CallOption) (*AuthReply, error) {
	var out AuthReply
	pattern := "/system/user/auth"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSysUserAuth))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ChangeStatus 更新用户状态
func (c *SysUserHTTPClientImpl) ChangeStatus(ctx context.Context, in *ChangeStatusRequest, opts ...http.CallOption) (*ChangeStatusReply, error) {
	var out ChangeStatusReply
	pattern := "/system/user/changeStatus"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSysUserChangeStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateSysUser 创建用户
func (c *SysUserHTTPClientImpl) CreateSysUser(ctx context.Context, in *CreateSysUserRequest, opts ...http.CallOption) (*CreateSysUserReply, error) {
	var out CreateSysUserReply
	pattern := "/system/user"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSysUserCreateSysUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteSysUser 删除用户
func (c *SysUserHTTPClientImpl) DeleteSysUser(ctx context.Context, in *DeleteSysUserRequest, opts ...http.CallOption) (*DeleteSysUserReply, error) {
	var out DeleteSysUserReply
	pattern := "/system/user/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSysUserDeleteSysUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// FindCaptcha 获取验证码
func (c *SysUserHTTPClientImpl) FindCaptcha(ctx context.Context, in *FindCaptchaRequest, opts ...http.CallOption) (*FindCaptchaReply, error) {
	var out FindCaptchaReply
	pattern := "/system/user/getCaptcha"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSysUserFindCaptcha))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// FindPostInit 获取岗位
func (c *SysUserHTTPClientImpl) FindPostInit(ctx context.Context, in *FindPostInitRequest, opts ...http.CallOption) (*FindPostInitReply, error) {
	var out FindPostInitReply
	pattern := "/system/user/getInit"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSysUserFindPostInit))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// FindSysUser 获取用户
func (c *SysUserHTTPClientImpl) FindSysUser(ctx context.Context, in *FindSysUserRequest, opts ...http.CallOption) (*FindSysUserReply, error) {
	var out FindSysUserReply
	pattern := "/system/user/getById/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSysUserFindSysUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// FindUserGoogleSecret 生成密钥和二维码
func (c *SysUserHTTPClientImpl) FindUserGoogleSecret(ctx context.Context, in *FindUserGoogleSecretRequest, opts ...http.CallOption) (*FindUserGoogleSecretReply, error) {
	var out FindUserGoogleSecretReply
	pattern := "/system/user/secret"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSysUserFindUserGoogleSecret))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// FindUserRolePost 获取RoPo
func (c *SysUserHTTPClientImpl) FindUserRolePost(ctx context.Context, in *FindUserRolePostRequest, opts ...http.CallOption) (*FindUserRolePostReply, error) {
	var out FindUserRolePostReply
	pattern := "/system/user/getRoPo"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSysUserFindUserRolePost))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSysUser 用户列表
func (c *SysUserHTTPClientImpl) ListSysUser(ctx context.Context, in *ListSysUserRequest, opts ...http.CallOption) (*ListSysUserReply, error) {
	var out ListSysUserReply
	pattern := "/system/user/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSysUserListSysUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Login 登入
func (c *SysUserHTTPClientImpl) Login(ctx context.Context, in *LoginRequest, opts ...http.CallOption) (*LoginReply, error) {
	var out LoginReply
	pattern := "/system/user/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSysUserLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Logout 登出
func (c *SysUserHTTPClientImpl) Logout(ctx context.Context, in *LogoutRequest, opts ...http.CallOption) (*LogoutReply, error) {
	var out LogoutReply
	pattern := "/system/user/logout"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSysUserLogout))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdatePassword 更新密码
func (c *SysUserHTTPClientImpl) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...http.CallOption) (*UpdatePasswordReply, error) {
	var out UpdatePasswordReply
	pattern := "/system/user/pwd"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSysUserUpdatePassword))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateSysUser 更新用户
func (c *SysUserHTTPClientImpl) UpdateSysUser(ctx context.Context, in *UpdateSysUserRequest, opts ...http.CallOption) (*UpdateSysUserReply, error) {
	var out UpdateSysUserReply
	pattern := "/system/user"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSysUserUpdateSysUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
