// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	admin2 "github.com/swordkee/kratos-vue-admin/app/admin/internal/biz/admin"
	"github.com/swordkee/kratos-vue-admin/app/admin/internal/conf"
	"github.com/swordkee/kratos-vue-admin/app/admin/internal/data"
	"github.com/swordkee/kratos-vue-admin/app/admin/internal/data/admin"
	"github.com/swordkee/kratos-vue-admin/app/admin/internal/pkg/oss"
	"github.com/swordkee/kratos-vue-admin/app/admin/internal/server"
	admin3 "github.com/swordkee/kratos-vue-admin/app/admin/internal/service/admin"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, casbin *conf.Casbin, confOss *conf.Oss, logger log.Logger, data_Redis *conf.Data_Redis) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	casbinRuleRepo := admin.NewCasbinRuleRepo(db, logger)
	universalClient := data.NewRedis(confData)
	dataData, cleanup, err := data.NewData(db, logger, universalClient)
	if err != nil {
		return nil, nil, err
	}
	query := data.NewQuery(dataData)
	sysUserRepo := admin.NewSysUserRepo(query, db, logger)
	ossRepo := oss.NewOssRepo(confOss, logger)
	sysUserUseCase := admin2.NewSysUserUseCase(sysUserRepo, ossRepo, confServer, logger)
	sysRoleRepo := admin.NewSysRoleRepo(query, logger)
	authUseCase := admin2.NewAuthUseCase(auth, sysUserRepo, sysRoleRepo, logger)
	sysRoleMenuRepo := admin.NewSysRoleMenuRepo(query, logger)
	sysRoleMenuUseCase := admin2.NewSysRoleMenuUseCase(sysRoleMenuRepo, logger)
	casbinRuleUseCase := admin2.NewCasbinRuleUseCase(casbinRuleRepo, logger)
	transaction := data.NewTransaction(dataData)
	sysMenuRepo := admin.NewSysMenuRepo(query, logger)
	sysRoleUseCase := admin2.NewSysRoleUseCase(sysRoleRepo, logger, sysRoleMenuUseCase, casbinRuleUseCase, sysUserUseCase, transaction, sysMenuRepo)
	sysPostRepo := admin.NewSysPostRepo(query, logger)
	sysPostUseCase := admin2.NewSysPostUseCase(sysPostRepo, logger, sysUserUseCase)
	sysDeptRepo := admin.NewSysDeptRepo(query, logger)
	sysDeptUseCase := admin2.NewSysDeptUseCase(sysDeptRepo, logger)
	sysUserService := admin3.NewSysUserService(confServer, sysUserUseCase, authUseCase, sysRoleUseCase, sysRoleMenuUseCase, sysPostUseCase, sysDeptUseCase, logger)
	sysApiRepo := admin.NewSysApiRepo(query, logger)
	v := admin2.NewSysApiUseCase(sysApiRepo, casbinRuleRepo, logger)
	apiService := admin3.NewApiService(v, logger, casbinRuleUseCase)
	deptService := admin3.NewDeptService(sysDeptUseCase, logger)
	sysLogsRepo := admin.NewSysLogsRepo(query, logger)
	v2 := admin2.NewSysLogsUseCase(sysLogsRepo, logger)
	sysLogsService := admin3.NewSysLogsService(v2, logger)
	v3 := admin2.NewSysMenusUseCase(sysMenuRepo, logger)
	menusService := admin3.NewMenusService(v3, sysRoleMenuUseCase, logger)
	postService := admin3.NewPostService(sysPostUseCase, logger)
	sysDictTypeRepo := admin.NewSysDictTypeRepo(query, logger)
	v4 := admin2.NewSysDictTypeUseCase(sysDictTypeRepo, logger)
	dictTypeService := admin3.NewDictTypeService(v4, logger)
	sysDictDataRepo := admin.NewSysDictDataRepo(query, logger)
	v5 := admin2.NewSysDictDatumUseCase(sysDictDataRepo, logger)
	dictDataService := admin3.NewDictDataService(v5, logger)
	rolesService := admin3.NewRolesService(sysRoleUseCase, logger, casbinRuleUseCase)
	httpServer := server.NewHTTPServer(confServer, auth, casbinRuleRepo, sysUserRepo, logger, sysUserService, apiService, deptService, v2, sysLogsService, menusService, postService, dictTypeService, dictDataService, rolesService)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
