// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	biz "github.com/swordkee/kratos-vue-admin/app/admin/internal/biz/admin"
	"github.com/swordkee/kratos-vue-admin/app/admin/internal/conf"
	"github.com/swordkee/kratos-vue-admin/app/admin/internal/data"
	"github.com/swordkee/kratos-vue-admin/app/admin/internal/data/admin"
	"github.com/swordkee/kratos-vue-admin/app/admin/internal/data/gen/dao"
	"github.com/swordkee/kratos-vue-admin/app/admin/internal/pkg/oss"
	"github.com/swordkee/kratos-vue-admin/app/admin/internal/server"
	"github.com/swordkee/kratos-vue-admin/app/admin/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, casbin *conf.Casbin, confOss *conf.Oss, logger log.Logger, data_Redis *conf.Data_Redis) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	universalClient := data.NewRedis(confData)
	dataData, cleanup, err := data.NewData(db, logger, universalClient)
	if err != nil {
		return nil, nil, err
	}
	query := dao.Use(db)
	casbinRuleRepo := admin.NewCasbinRuleRepo(db, logger)
	sysUserRepo := admin.NewSysUserRepo(query, logger)
	ossRepo := oss.NewOssRepo(confOss, logger)
	sysUserUseCase := biz.NewSysUserUseCase(sysUserRepo, ossRepo, confServer, logger)
	sysRoleRepo := admin.NewSysRoleRepo(query, logger)
	authUseCase := biz.NewAuthUseCase(auth, sysUserRepo, sysRoleRepo, logger)
	sysRoleMenuRepo := admin.NewSysRoleMenuRepo(query, logger)
	sysRoleMenuUseCase := biz.NewSysRoleMenuUseCase(sysRoleMenuRepo, logger)
	casbinRuleUseCase := biz.NewCasbinRuleUseCase(casbinRuleRepo, logger)
	transaction := data.NewTransaction(dataData)
	sysMenuRepo := admin.NewSysMenuRepo(query, logger)
	sysRoleUseCase := biz.NewSysRoleUseCase(sysRoleRepo, logger, sysRoleMenuUseCase, casbinRuleUseCase, sysUserUseCase, transaction, sysMenuRepo)
	sysPostRepo := admin.NewSysPostRepo(query, logger)
	sysPostUseCase := biz.NewSysPostUseCase(sysPostRepo, logger, sysUserUseCase)
	sysDeptRepo := admin.NewSysDeptRepo(query, logger)
	sysDeptUseCase := biz.NewSysDeptUseCase(sysDeptRepo, logger)
	sysuserService := service.NewSysuserService(confServer, sysUserUseCase, authUseCase, sysRoleUseCase, sysRoleMenuUseCase, sysPostUseCase, sysDeptUseCase, logger)
	sysApiRepo := admin.NewSysApiRepo(query, logger)
	sysApiUseCase := biz.NewSysApiUseCase(sysApiRepo, casbinRuleRepo, logger)
	apiService := service.NewApiService(sysApiUseCase, logger, casbinRuleUseCase)
	deptService := service.NewDeptService(sysDeptUseCase, logger)
	sysMenuUseCase := biz.NewSysMenusUseCase(sysMenuRepo, logger)
	menusService := service.NewMenusService(sysMenuUseCase, sysRoleMenuUseCase, logger)
	sysLogsRepo := admin.NewSysLogsRepo(query, logger)
	sysLogsUseCase := biz.NewSysLogsUseCase(sysLogsRepo, logger)
	sysLogsService := service.NewSysLogsService(sysLogsUseCase, logger)
	postService := service.NewPostService(sysPostUseCase, logger)
	sysDictTypeRepo := admin.NewSysDictTypeRepo(query, logger)
	sysDictTypeUseCase := biz.NewSysDictTypeUseCase(sysDictTypeRepo, logger)
	dictTypeService := service.NewDictTypeService(sysDictTypeUseCase, logger)
	sysDictDatumRepo := admin.NewSysDictDataRepo(query, logger)
	sysDictDatumUseCase := biz.NewSysDictDatumUseCase(sysDictDatumRepo, logger)
	dictDataService := service.NewDictDataService(sysDictDatumUseCase, logger)
	rolesService := service.NewRolesService(sysRoleUseCase, logger, casbinRuleUseCase)
	httpServer := server.NewHTTPServer(confServer, auth, casbinRuleRepo, logger, sysuserService, apiService, deptService, sysLogsUseCase, sysLogsService, menusService, postService, dictTypeService, dictDataService, rolesService)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
