// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Env int32

const (
	Env_dev  Env = 0 // 开发环境
	Env_test Env = 1 // 测试环境
	Env_pro  Env = 2 // 正式环境
)

// Enum value maps for Env.
var (
	Env_name = map[int32]string{
		0: "dev",
		1: "test",
		2: "pro",
	}
	Env_value = map[string]int32{
		"dev":  0,
		"test": 1,
		"pro":  2,
	}
)

func (x Env) Enum() *Env {
	p := new(Env)
	*p = x
	return p
}

func (x Env) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Env) Descriptor() protoreflect.EnumDescriptor {
	return file_conf_conf_proto_enumTypes[0].Descriptor()
}

func (Env) Type() protoreflect.EnumType {
	return &file_conf_conf_proto_enumTypes[0]
}

func (x Env) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Env.Descriptor instead.
func (Env) EnumDescriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

type OssUseMode int32

const (
	OssUseMode_aliyun OssUseMode = 0
	OssUseMode_local  OssUseMode = 1
)

// Enum value maps for OssUseMode.
var (
	OssUseMode_name = map[int32]string{
		0: "aliyun",
		1: "local",
	}
	OssUseMode_value = map[string]int32{
		"aliyun": 0,
		"local":  1,
	}
)

func (x OssUseMode) Enum() *OssUseMode {
	p := new(OssUseMode)
	*p = x
	return p
}

func (x OssUseMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OssUseMode) Descriptor() protoreflect.EnumDescriptor {
	return file_conf_conf_proto_enumTypes[1].Descriptor()
}

func (OssUseMode) Type() protoreflect.EnumType {
	return &file_conf_conf_proto_enumTypes[1]
}

func (x OssUseMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OssUseMode.Descriptor instead.
func (OssUseMode) EnumDescriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

type GormLogLevel int32

const (
	GormLogLevel_warn   GormLogLevel = 0
	GormLogLevel_info   GormLogLevel = 1
	GormLogLevel_silent GormLogLevel = 2
	GormLogLevel_error  GormLogLevel = 3
)

// Enum value maps for GormLogLevel.
var (
	GormLogLevel_name = map[int32]string{
		0: "warn",
		1: "info",
		2: "silent",
		3: "error",
	}
	GormLogLevel_value = map[string]int32{
		"warn":   0,
		"info":   1,
		"silent": 2,
		"error":  3,
	}
)

func (x GormLogLevel) Enum() *GormLogLevel {
	p := new(GormLogLevel)
	*p = x
	return p
}

func (x GormLogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GormLogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_conf_conf_proto_enumTypes[2].Descriptor()
}

func (GormLogLevel) Type() protoreflect.EnumType {
	return &file_conf_conf_proto_enumTypes[2]
}

func (x GormLogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GormLogLevel.Descriptor instead.
func (GormLogLevel) EnumDescriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Auth          *Auth                  `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	Casbin        *Casbin                `protobuf:"bytes,4,opt,name=casbin,proto3" json:"casbin,omitempty"`
	Oss           *Oss                   `protobuf:"bytes,5,opt,name=oss,proto3" json:"oss,omitempty"`
	Log           *LogConfig             `protobuf:"bytes,6,opt,name=log,proto3" json:"log,omitempty"` // 日志配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Bootstrap) GetCasbin() *Casbin {
	if x != nil {
		return x.Casbin
	}
	return nil
}

func (x *Bootstrap) GetOss() *Oss {
	if x != nil {
		return x.Oss
	}
	return nil
}

func (x *Bootstrap) GetLog() *LogConfig {
	if x != nil {
		return x.Log
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	Env           Env                    `protobuf:"varint,3,opt,name=env,proto3,enum=kratos.api.Env" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Server) GetEnv() Env {
	if x != nil {
		return x.Env
	}
	return Env_dev
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Data_Database         `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *Data_Redis            `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

type Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwtKey        string                 `protobuf:"bytes,1,opt,name=jwtKey,proto3" json:"jwtKey,omitempty"`
	Expires       *durationpb.Duration   `protobuf:"bytes,2,opt,name=expires,proto3" json:"expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Auth) GetJwtKey() string {
	if x != nil {
		return x.JwtKey
	}
	return ""
}

func (x *Auth) GetExpires() *durationpb.Duration {
	if x != nil {
		return x.Expires
	}
	return nil
}

type Casbin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Casbin) Reset() {
	*x = Casbin{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Casbin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Casbin) ProtoMessage() {}

func (x *Casbin) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Casbin.ProtoReflect.Descriptor instead.
func (*Casbin) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Casbin) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type OssConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	AccessKey     string                 `protobuf:"bytes,2,opt,name=accessKey,proto3" json:"accessKey,omitempty"`
	AccessSecret  string                 `protobuf:"bytes,3,opt,name=accessSecret,proto3" json:"accessSecret,omitempty"`
	BucketName    string                 `protobuf:"bytes,4,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	BucketURL     string                 `protobuf:"bytes,5,opt,name=bucketURL,proto3" json:"bucketURL,omitempty"`
	ImgDomain     string                 `protobuf:"bytes,6,opt,name=imgDomain,proto3" json:"imgDomain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OssConfig) Reset() {
	*x = OssConfig{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OssConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OssConfig) ProtoMessage() {}

func (x *OssConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OssConfig.ProtoReflect.Descriptor instead.
func (*OssConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *OssConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *OssConfig) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *OssConfig) GetAccessSecret() string {
	if x != nil {
		return x.AccessSecret
	}
	return ""
}

func (x *OssConfig) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *OssConfig) GetBucketURL() string {
	if x != nil {
		return x.BucketURL
	}
	return ""
}

func (x *OssConfig) GetImgDomain() string {
	if x != nil {
		return x.ImgDomain
	}
	return ""
}

type OssLocalConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           string                 `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OssLocalConfig) Reset() {
	*x = OssLocalConfig{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OssLocalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OssLocalConfig) ProtoMessage() {}

func (x *OssLocalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OssLocalConfig.ProtoReflect.Descriptor instead.
func (*OssLocalConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{6}
}

func (x *OssLocalConfig) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

type Oss struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Use           OssUseMode             `protobuf:"varint,1,opt,name=use,proto3,enum=kratos.api.OssUseMode" json:"use,omitempty"`
	Aliyun        *OssConfig             `protobuf:"bytes,2,opt,name=aliyun,proto3" json:"aliyun,omitempty"`
	Local         *OssLocalConfig        `protobuf:"bytes,3,opt,name=local,proto3" json:"local,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Oss) Reset() {
	*x = Oss{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Oss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oss) ProtoMessage() {}

func (x *Oss) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oss.ProtoReflect.Descriptor instead.
func (*Oss) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{7}
}

func (x *Oss) GetUse() OssUseMode {
	if x != nil {
		return x.Use
	}
	return OssUseMode_aliyun
}

func (x *Oss) GetAliyun() *OssConfig {
	if x != nil {
		return x.Aliyun
	}
	return nil
}

func (x *Oss) GetLocal() *OssLocalConfig {
	if x != nil {
		return x.Local
	}
	return nil
}

// 操作日志配置
type LogConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EnableReadLog  bool                   `protobuf:"varint,1,opt,name=enableReadLog,proto3" json:"enableReadLog,omitempty"`   // 是否记录读操作(GET/HEAD/OPTIONS)，默认false
	EnableWriteLog bool                   `protobuf:"varint,2,opt,name=enableWriteLog,proto3" json:"enableWriteLog,omitempty"` // 是否记录写操作(POST/PUT/DELETE/PATCH)，默认true
	MaxBodyLength  int32                  `protobuf:"varint,3,opt,name=maxBodyLength,proto3" json:"maxBodyLength,omitempty"`   // 请求/响应体最大长度，默认4096
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogConfig) Reset() {
	*x = LogConfig{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogConfig) ProtoMessage() {}

func (x *LogConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogConfig.ProtoReflect.Descriptor instead.
func (*LogConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{8}
}

func (x *LogConfig) GetEnableReadLog() bool {
	if x != nil {
		return x.EnableReadLog
	}
	return false
}

func (x *LogConfig) GetEnableWriteLog() bool {
	if x != nil {
		return x.EnableWriteLog
	}
	return false
}

func (x *LogConfig) GetMaxBodyLength() int32 {
	if x != nil {
		return x.MaxBodyLength
	}
	return 0
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	MaxIdleConns  int64                  `protobuf:"varint,3,opt,name=maxIdleConns,proto3" json:"maxIdleConns,omitempty"`
	MaxOpenConns  int64                  `protobuf:"varint,4,opt,name=maxOpenConns,proto3" json:"maxOpenConns,omitempty"`
	LogLevel      GormLogLevel           `protobuf:"varint,5,opt,name=logLevel,proto3,enum=kratos.api.GormLogLevel" json:"logLevel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Data_Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Data_Database) GetMaxIdleConns() int64 {
	if x != nil {
		return x.MaxIdleConns
	}
	return 0
}

func (x *Data_Database) GetMaxOpenConns() int64 {
	if x != nil {
		return x.MaxOpenConns
	}
	return 0
}

func (x *Data_Database) GetLogLevel() GormLogLevel {
	if x != nil {
		return x.LogLevel
	}
	return GormLogLevel_warn
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,3,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,4,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Database      int32                  `protobuf:"varint,7,opt,name=database,proto3" json:"database,omitempty"`
	EnableCluster bool                   `protobuf:"varint,8,opt,name=enable_cluster,json=enableCluster,proto3" json:"enable_cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_Redis) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

func (x *Data_Redis) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Data_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_Redis) GetDatabase() int32 {
	if x != nil {
		return x.Database
	}
	return 0
}

func (x *Data_Redis) GetEnableCluster() bool {
	if x != nil {
		return x.EnableCluster
	}
	return false
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"\xfb\x01\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\x12$\n" +
	"\x04auth\x18\x03 \x01(\v2\x10.kratos.api.AuthR\x04auth\x12*\n" +
	"\x06casbin\x18\x04 \x01(\v2\x12.kratos.api.CasbinR\x06casbin\x12!\n" +
	"\x03oss\x18\x05 \x01(\v2\x0f.kratos.api.OssR\x03oss\x12'\n" +
	"\x03log\x18\x06 \x01(\v2\x15.kratos.api.LogConfigR\x03log\"\xdb\x02\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x12!\n" +
	"\x03env\x18\x03 \x01(\x0e2\x0f.kratos.api.EnvR\x03env\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xd7\x04\n" +
	"\x04Data\x125\n" +
	"\bdatabase\x18\x01 \x01(\v2\x19.kratos.api.Data.DatabaseR\bdatabase\x12,\n" +
	"\x05redis\x18\x02 \x01(\v2\x16.kratos.api.Data.RedisR\x05redis\x1a\xb8\x01\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\"\n" +
	"\fmaxIdleConns\x18\x03 \x01(\x03R\fmaxIdleConns\x12\"\n" +
	"\fmaxOpenConns\x18\x04 \x01(\x03R\fmaxOpenConns\x124\n" +
	"\blogLevel\x18\x05 \x01(\x0e2\x18.kratos.api.GormLogLevelR\blogLevel\x1a\xae\x02\n" +
	"\x05Redis\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12<\n" +
	"\fread_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12\x1a\n" +
	"\bdatabase\x18\a \x01(\x05R\bdatabase\x12%\n" +
	"\x0eenable_cluster\x18\b \x01(\bR\renableCluster\"S\n" +
	"\x04Auth\x12\x16\n" +
	"\x06jwtKey\x18\x01 \x01(\tR\x06jwtKey\x123\n" +
	"\aexpires\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\aexpires\"\x1c\n" +
	"\x06Casbin\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xc5\x01\n" +
	"\tOssConfig\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x1c\n" +
	"\taccessKey\x18\x02 \x01(\tR\taccessKey\x12\"\n" +
	"\faccessSecret\x18\x03 \x01(\tR\faccessSecret\x12\x1e\n" +
	"\n" +
	"bucketName\x18\x04 \x01(\tR\n" +
	"bucketName\x12\x1c\n" +
	"\tbucketURL\x18\x05 \x01(\tR\tbucketURL\x12\x1c\n" +
	"\timgDomain\x18\x06 \x01(\tR\timgDomain\"\"\n" +
	"\x0eOssLocalConfig\x12\x10\n" +
	"\x03dir\x18\x01 \x01(\tR\x03dir\"\x90\x01\n" +
	"\x03Oss\x12(\n" +
	"\x03use\x18\x01 \x01(\x0e2\x16.kratos.api.OssUseModeR\x03use\x12-\n" +
	"\x06aliyun\x18\x02 \x01(\v2\x15.kratos.api.OssConfigR\x06aliyun\x120\n" +
	"\x05local\x18\x03 \x01(\v2\x1a.kratos.api.OssLocalConfigR\x05local\"\x7f\n" +
	"\tLogConfig\x12$\n" +
	"\renableReadLog\x18\x01 \x01(\bR\renableReadLog\x12&\n" +
	"\x0eenableWriteLog\x18\x02 \x01(\bR\x0eenableWriteLog\x12$\n" +
	"\rmaxBodyLength\x18\x03 \x01(\x05R\rmaxBodyLength*!\n" +
	"\x03Env\x12\a\n" +
	"\x03dev\x10\x00\x12\b\n" +
	"\x04test\x10\x01\x12\a\n" +
	"\x03pro\x10\x02*#\n" +
	"\n" +
	"OssUseMode\x12\n" +
	"\n" +
	"\x06aliyun\x10\x00\x12\t\n" +
	"\x05local\x10\x01*9\n" +
	"\fGormLogLevel\x12\b\n" +
	"\x04warn\x10\x00\x12\b\n" +
	"\x04info\x10\x01\x12\n" +
	"\n" +
	"\x06silent\x10\x02\x12\t\n" +
	"\x05error\x10\x03B'Z%fengyin/app/server/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_conf_conf_proto_goTypes = []any{
	(Env)(0),                    // 0: kratos.api.Env
	(OssUseMode)(0),             // 1: kratos.api.OssUseMode
	(GormLogLevel)(0),           // 2: kratos.api.GormLogLevel
	(*Bootstrap)(nil),           // 3: kratos.api.Bootstrap
	(*Server)(nil),              // 4: kratos.api.Server
	(*Data)(nil),                // 5: kratos.api.Data
	(*Auth)(nil),                // 6: kratos.api.Auth
	(*Casbin)(nil),              // 7: kratos.api.Casbin
	(*OssConfig)(nil),           // 8: kratos.api.OssConfig
	(*OssLocalConfig)(nil),      // 9: kratos.api.OssLocalConfig
	(*Oss)(nil),                 // 10: kratos.api.Oss
	(*LogConfig)(nil),           // 11: kratos.api.LogConfig
	(*Server_HTTP)(nil),         // 12: kratos.api.Server.HTTP
	(*Server_GRPC)(nil),         // 13: kratos.api.Server.GRPC
	(*Data_Database)(nil),       // 14: kratos.api.Data.Database
	(*Data_Redis)(nil),          // 15: kratos.api.Data.Redis
	(*durationpb.Duration)(nil), // 16: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	4,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	5,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	6,  // 2: kratos.api.Bootstrap.auth:type_name -> kratos.api.Auth
	7,  // 3: kratos.api.Bootstrap.casbin:type_name -> kratos.api.Casbin
	10, // 4: kratos.api.Bootstrap.oss:type_name -> kratos.api.Oss
	11, // 5: kratos.api.Bootstrap.log:type_name -> kratos.api.LogConfig
	12, // 6: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	13, // 7: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	0,  // 8: kratos.api.Server.env:type_name -> kratos.api.Env
	14, // 9: kratos.api.Data.database:type_name -> kratos.api.Data.Database
	15, // 10: kratos.api.Data.redis:type_name -> kratos.api.Data.Redis
	16, // 11: kratos.api.Auth.expires:type_name -> google.protobuf.Duration
	1,  // 12: kratos.api.Oss.use:type_name -> kratos.api.OssUseMode
	8,  // 13: kratos.api.Oss.aliyun:type_name -> kratos.api.OssConfig
	9,  // 14: kratos.api.Oss.local:type_name -> kratos.api.OssLocalConfig
	16, // 15: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	16, // 16: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	2,  // 17: kratos.api.Data.Database.logLevel:type_name -> kratos.api.GormLogLevel
	16, // 18: kratos.api.Data.Redis.read_timeout:type_name -> google.protobuf.Duration
	16, // 19: kratos.api.Data.Redis.write_timeout:type_name -> google.protobuf.Duration
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		EnumInfos:         file_conf_conf_proto_enumTypes,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
