// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Env int32

const (
	Env_dev  Env = 0 // 开发环境
	Env_test Env = 1 // 测试环境
	Env_pro  Env = 2 // 正式环境
)

// Enum value maps for Env.
var (
	Env_name = map[int32]string{
		0: "dev",
		1: "test",
		2: "pro",
	}
	Env_value = map[string]int32{
		"dev":  0,
		"test": 1,
		"pro":  2,
	}
)

func (x Env) Enum() *Env {
	p := new(Env)
	*p = x
	return p
}

func (x Env) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Env) Descriptor() protoreflect.EnumDescriptor {
	return file_conf_conf_proto_enumTypes[0].Descriptor()
}

func (Env) Type() protoreflect.EnumType {
	return &file_conf_conf_proto_enumTypes[0]
}

func (x Env) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Env.Descriptor instead.
func (Env) EnumDescriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

type OssUseMode int32

const (
	OssUseMode_aliyun OssUseMode = 0
	OssUseMode_local  OssUseMode = 1
)

// Enum value maps for OssUseMode.
var (
	OssUseMode_name = map[int32]string{
		0: "aliyun",
		1: "local",
	}
	OssUseMode_value = map[string]int32{
		"aliyun": 0,
		"local":  1,
	}
)

func (x OssUseMode) Enum() *OssUseMode {
	p := new(OssUseMode)
	*p = x
	return p
}

func (x OssUseMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OssUseMode) Descriptor() protoreflect.EnumDescriptor {
	return file_conf_conf_proto_enumTypes[1].Descriptor()
}

func (OssUseMode) Type() protoreflect.EnumType {
	return &file_conf_conf_proto_enumTypes[1]
}

func (x OssUseMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OssUseMode.Descriptor instead.
func (OssUseMode) EnumDescriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

type GormLogLevel int32

const (
	GormLogLevel_warn   GormLogLevel = 0
	GormLogLevel_info   GormLogLevel = 1
	GormLogLevel_silent GormLogLevel = 2
	GormLogLevel_error  GormLogLevel = 3
)

// Enum value maps for GormLogLevel.
var (
	GormLogLevel_name = map[int32]string{
		0: "warn",
		1: "info",
		2: "silent",
		3: "error",
	}
	GormLogLevel_value = map[string]int32{
		"warn":   0,
		"info":   1,
		"silent": 2,
		"error":  3,
	}
)

func (x GormLogLevel) Enum() *GormLogLevel {
	p := new(GormLogLevel)
	*p = x
	return p
}

func (x GormLogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GormLogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_conf_conf_proto_enumTypes[2].Descriptor()
}

func (GormLogLevel) Type() protoreflect.EnumType {
	return &file_conf_conf_proto_enumTypes[2]
}

func (x GormLogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GormLogLevel.Descriptor instead.
func (GormLogLevel) EnumDescriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Auth          *Auth                  `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	Casbin        *Casbin                `protobuf:"bytes,4,opt,name=casbin,proto3" json:"casbin,omitempty"`
	Oss           *Oss                   `protobuf:"bytes,5,opt,name=oss,proto3" json:"oss,omitempty"`
	Log           *LogConfig             `protobuf:"bytes,6,opt,name=log,proto3" json:"log,omitempty"`         // 日志配置
	Message       *Message               `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"` // 消息/短信验证码域配置（与 go-exAdmin、go-payAdmin 三端统一）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Bootstrap) GetCasbin() *Casbin {
	if x != nil {
		return x.Casbin
	}
	return nil
}

func (x *Bootstrap) GetOss() *Oss {
	if x != nil {
		return x.Oss
	}
	return nil
}

func (x *Bootstrap) GetLog() *LogConfig {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *Bootstrap) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type Server struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Http  *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc  *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	Env   Env                    `protobuf:"varint,3,opt,name=env,proto3,enum=kratos.api.Env" json:"env,omitempty"`
	// CORS 跨域白名单：缺省/留空 = 禁用跨域（仅同源）；需要跨域时显式列出来源（含 scheme）。
	// 凭据（AllowCredentials）仅与显式白名单搭配，禁止通配源 * + 凭据的矛盾组合。
	Cors          *Cors `protobuf:"bytes,4,opt,name=cors,proto3" json:"cors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Server) GetEnv() Env {
	if x != nil {
		return x.Env
	}
	return Env_dev
}

func (x *Server) GetCors() *Cors {
	if x != nil {
		return x.Cors
	}
	return nil
}

// Cors 跨域配置（PA-P2-03 收紧形态）
type Cors struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllowOrigins  []string               `protobuf:"bytes,1,rep,name=allowOrigins,proto3" json:"allowOrigins,omitempty"` // 允许来源（含 scheme，如 https://admin.example.com）
	MaxAge        int32                  `protobuf:"varint,2,opt,name=maxAge,proto3" json:"maxAge,omitempty"`            // 预检缓存秒数，缺省 86400
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cors) Reset() {
	*x = Cors{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cors) ProtoMessage() {}

func (x *Cors) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cors.ProtoReflect.Descriptor instead.
func (*Cors) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Cors) GetAllowOrigins() []string {
	if x != nil {
		return x.AllowOrigins
	}
	return nil
}

func (x *Cors) GetMaxAge() int32 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Data_Database         `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *Data_Redis            `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

// Auth 认证配置。
// JWT 采用 ECDSA P-384 (ES384) 非对称签名：ecdsa_private_key（签发侧 SEC1/PKCS8 PEM）、
// ecdsa_public_key（验证侧 PKIX PEM）。部署时各实例使用同一密钥对。
type Auth struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EcdsaPrivateKey string                 `protobuf:"bytes,1,opt,name=ecdsa_private_key,json=ecdsaPrivateKey,proto3" json:"ecdsa_private_key,omitempty"` // ECDSA P-384 私钥 PEM（签发侧）
	EcdsaPublicKey  string                 `protobuf:"bytes,2,opt,name=ecdsa_public_key,json=ecdsaPublicKey,proto3" json:"ecdsa_public_key,omitempty"`    // ECDSA P-384 公钥 PEM（验证侧）
	Expires         *durationpb.Duration   `protobuf:"bytes,3,opt,name=expires,proto3" json:"expires,omitempty"`
	Mfa             *Mfa                   `protobuf:"bytes,5,opt,name=mfa,proto3" json:"mfa,omitempty"` // TOTP 双因素认证配置（默认不启用）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Auth) GetEcdsaPrivateKey() string {
	if x != nil {
		return x.EcdsaPrivateKey
	}
	return ""
}

func (x *Auth) GetEcdsaPublicKey() string {
	if x != nil {
		return x.EcdsaPublicKey
	}
	return ""
}

func (x *Auth) GetExpires() *durationpb.Duration {
	if x != nil {
		return x.Expires
	}
	return nil
}

func (x *Auth) GetMfa() *Mfa {
	if x != nil {
		return x.Mfa
	}
	return nil
}

// Mfa TOTP 双因素认证配置。
// 默认不启用（enabled=false），零行为影响；enabled=true 时必须配置 32 字节
// encryption_key（启动校验拒绝占位密钥），且先行执行 DDL（sys_users mfa 三列 +
// sys_mfa_recovery_code 表）。
type Mfa struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`                                 // 总开关，默认 false
	Required      bool                   `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`                               // 强制全员绑定（enabled=true 前提下）
	EncryptionKey string                 `protobuf:"bytes,3,opt,name=encryption_key,json=encryptionKey,proto3" json:"encryption_key,omitempty"` // AES-256-GCM 主密钥（32 字节，enabled=true 时必填）
	Issuer        string                 `protobuf:"bytes,4,opt,name=issuer,proto3" json:"issuer,omitempty"`                                    // TOTP 发行者名称（验证器 App 显示，缺省 BMALL）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mfa) Reset() {
	*x = Mfa{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mfa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mfa) ProtoMessage() {}

func (x *Mfa) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mfa.ProtoReflect.Descriptor instead.
func (*Mfa) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Mfa) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Mfa) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Mfa) GetEncryptionKey() string {
	if x != nil {
		return x.EncryptionKey
	}
	return ""
}

func (x *Mfa) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

type Casbin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Casbin) Reset() {
	*x = Casbin{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Casbin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Casbin) ProtoMessage() {}

func (x *Casbin) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Casbin.ProtoReflect.Descriptor instead.
func (*Casbin) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{6}
}

func (x *Casbin) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type OssConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	AccessKey     string                 `protobuf:"bytes,2,opt,name=accessKey,proto3" json:"accessKey,omitempty"`
	AccessSecret  string                 `protobuf:"bytes,3,opt,name=accessSecret,proto3" json:"accessSecret,omitempty"`
	BucketName    string                 `protobuf:"bytes,4,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	BucketURL     string                 `protobuf:"bytes,5,opt,name=bucketURL,proto3" json:"bucketURL,omitempty"`
	ImgDomain     string                 `protobuf:"bytes,6,opt,name=imgDomain,proto3" json:"imgDomain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OssConfig) Reset() {
	*x = OssConfig{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OssConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OssConfig) ProtoMessage() {}

func (x *OssConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OssConfig.ProtoReflect.Descriptor instead.
func (*OssConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{7}
}

func (x *OssConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *OssConfig) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *OssConfig) GetAccessSecret() string {
	if x != nil {
		return x.AccessSecret
	}
	return ""
}

func (x *OssConfig) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *OssConfig) GetBucketURL() string {
	if x != nil {
		return x.BucketURL
	}
	return ""
}

func (x *OssConfig) GetImgDomain() string {
	if x != nil {
		return x.ImgDomain
	}
	return ""
}

type OssLocalConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           string                 `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OssLocalConfig) Reset() {
	*x = OssLocalConfig{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OssLocalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OssLocalConfig) ProtoMessage() {}

func (x *OssLocalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OssLocalConfig.ProtoReflect.Descriptor instead.
func (*OssLocalConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{8}
}

func (x *OssLocalConfig) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

type Oss struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Use           OssUseMode             `protobuf:"varint,1,opt,name=use,proto3,enum=kratos.api.OssUseMode" json:"use,omitempty"`
	Aliyun        *OssConfig             `protobuf:"bytes,2,opt,name=aliyun,proto3" json:"aliyun,omitempty"`
	Local         *OssLocalConfig        `protobuf:"bytes,3,opt,name=local,proto3" json:"local,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Oss) Reset() {
	*x = Oss{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Oss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oss) ProtoMessage() {}

func (x *Oss) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oss.ProtoReflect.Descriptor instead.
func (*Oss) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{9}
}

func (x *Oss) GetUse() OssUseMode {
	if x != nil {
		return x.Use
	}
	return OssUseMode_aliyun
}

func (x *Oss) GetAliyun() *OssConfig {
	if x != nil {
		return x.Aliyun
	}
	return nil
}

func (x *Oss) GetLocal() *OssLocalConfig {
	if x != nil {
		return x.Local
	}
	return nil
}

// 操作日志配置
type LogConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EnableReadLog  bool                   `protobuf:"varint,1,opt,name=enableReadLog,proto3" json:"enableReadLog,omitempty"`   // 是否记录读操作(GET/HEAD/OPTIONS)，默认false
	EnableWriteLog bool                   `protobuf:"varint,2,opt,name=enableWriteLog,proto3" json:"enableWriteLog,omitempty"` // 是否记录写操作(POST/PUT/DELETE/PATCH)，默认true
	MaxBodyLength  int32                  `protobuf:"varint,3,opt,name=maxBodyLength,proto3" json:"maxBodyLength,omitempty"`   // 请求/响应体最大长度，默认4096
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogConfig) Reset() {
	*x = LogConfig{}
	mi := &file_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogConfig) ProtoMessage() {}

func (x *LogConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogConfig.ProtoReflect.Descriptor instead.
func (*LogConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{10}
}

func (x *LogConfig) GetEnableReadLog() bool {
	if x != nil {
		return x.EnableReadLog
	}
	return false
}

func (x *LogConfig) GetEnableWriteLog() bool {
	if x != nil {
		return x.EnableWriteLog
	}
	return false
}

func (x *LogConfig) GetMaxBodyLength() int32 {
	if x != nil {
		return x.MaxBodyLength
	}
	return 0
}

// Message 消息/短信验证码域配置（三端统一，YAML 段名 message）。
// 注意：配置名不使用 SMS——其语义覆盖图形登录验证码与手机验证码登录，
// 短信网关真实凭据以 sys_sms_gateway 表为准，providers 仅作 YAML 兜底。
type Message struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	Enabled         bool                        `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`                                                                              // 消息域总开关
	DefaultProvider string                      `protobuf:"bytes,2,opt,name=default_provider,json=defaultProvider,proto3" json:"default_provider,omitempty"`                                        // 默认提供商（仅日志记录）
	LoginCaptcha    *LoginCaptcha               `protobuf:"bytes,3,opt,name=login_captcha,json=loginCaptcha,proto3" json:"login_captcha,omitempty"`                                                 // 登录图形验证码
	PhoneLogin      *PhoneLogin                 `protobuf:"bytes,4,opt,name=phone_login,json=phoneLogin,proto3" json:"phone_login,omitempty"`                                                       // 手机验证码登录
	Providers       map[string]*MessageProvider `protobuf:"bytes,5,rep,name=providers,proto3" json:"providers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // YAML 提供商兜底（表配置优先）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{11}
}

func (x *Message) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Message) GetDefaultProvider() string {
	if x != nil {
		return x.DefaultProvider
	}
	return ""
}

func (x *Message) GetLoginCaptcha() *LoginCaptcha {
	if x != nil {
		return x.LoginCaptcha
	}
	return nil
}

func (x *Message) GetPhoneLogin() *PhoneLogin {
	if x != nil {
		return x.PhoneLogin
	}
	return nil
}

func (x *Message) GetProviders() map[string]*MessageProvider {
	if x != nil {
		return x.Providers
	}
	return nil
}

// LoginCaptcha 登录图形验证码
type LoginCaptcha struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`                                  // 是否启用
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                                         // 验证码类型: simple=字符, numeric=数字
	Length        int32                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`                                    // 长度
	ExpireMinutes int32                  `protobuf:"varint,4,opt,name=expire_minutes,json=expireMinutes,proto3" json:"expire_minutes,omitempty"` // 过期时间（分钟）
	CachePrefix   string                 `protobuf:"bytes,5,opt,name=cache_prefix,json=cachePrefix,proto3" json:"cache_prefix,omitempty"`        // 缓存 key 前缀
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginCaptcha) Reset() {
	*x = LoginCaptcha{}
	mi := &file_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginCaptcha) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginCaptcha) ProtoMessage() {}

func (x *LoginCaptcha) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginCaptcha.ProtoReflect.Descriptor instead.
func (*LoginCaptcha) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{12}
}

func (x *LoginCaptcha) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *LoginCaptcha) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LoginCaptcha) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *LoginCaptcha) GetExpireMinutes() int32 {
	if x != nil {
		return x.ExpireMinutes
	}
	return 0
}

func (x *LoginCaptcha) GetCachePrefix() string {
	if x != nil {
		return x.CachePrefix
	}
	return ""
}

// PhoneLogin 手机验证码登录
type PhoneLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`                                  // 是否启用
	CodeLength    int32                  `protobuf:"varint,2,opt,name=code_length,json=codeLength,proto3" json:"code_length,omitempty"`          // 验证码长度
	ExpireMinutes int32                  `protobuf:"varint,3,opt,name=expire_minutes,json=expireMinutes,proto3" json:"expire_minutes,omitempty"` // 过期时间（分钟）
	CachePrefix   string                 `protobuf:"bytes,4,opt,name=cache_prefix,json=cachePrefix,proto3" json:"cache_prefix,omitempty"`        // 缓存 key 前缀
	DailyLimit    int32                  `protobuf:"varint,5,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`          // 每日发送限制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneLogin) Reset() {
	*x = PhoneLogin{}
	mi := &file_conf_conf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneLogin) ProtoMessage() {}

func (x *PhoneLogin) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneLogin.ProtoReflect.Descriptor instead.
func (*PhoneLogin) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{13}
}

func (x *PhoneLogin) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PhoneLogin) GetCodeLength() int32 {
	if x != nil {
		return x.CodeLength
	}
	return 0
}

func (x *PhoneLogin) GetExpireMinutes() int32 {
	if x != nil {
		return x.ExpireMinutes
	}
	return 0
}

func (x *PhoneLogin) GetCachePrefix() string {
	if x != nil {
		return x.CachePrefix
	}
	return ""
}

func (x *PhoneLogin) GetDailyLimit() int32 {
	if x != nil {
		return x.DailyLimit
	}
	return 0
}

// MessageProvider 消息提供商（HTTP 短信网关）
type MessageProvider struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GatewayUrl      string                 `protobuf:"bytes,2,opt,name=gateway_url,json=gatewayUrl,proto3" json:"gateway_url,omitempty"`
	AccessKeyId     string                 `protobuf:"bytes,3,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	AccessKeySecret string                 `protobuf:"bytes,4,opt,name=access_key_secret,json=accessKeySecret,proto3" json:"access_key_secret,omitempty"`
	SignName        string                 `protobuf:"bytes,5,opt,name=sign_name,json=signName,proto3" json:"sign_name,omitempty"`
	TemplateCode    string                 `protobuf:"bytes,6,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`
	Extra           map[string]string      `protobuf:"bytes,7,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageProvider) Reset() {
	*x = MessageProvider{}
	mi := &file_conf_conf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageProvider) ProtoMessage() {}

func (x *MessageProvider) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageProvider.ProtoReflect.Descriptor instead.
func (*MessageProvider) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{14}
}

func (x *MessageProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MessageProvider) GetGatewayUrl() string {
	if x != nil {
		return x.GatewayUrl
	}
	return ""
}

func (x *MessageProvider) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *MessageProvider) GetAccessKeySecret() string {
	if x != nil {
		return x.AccessKeySecret
	}
	return ""
}

func (x *MessageProvider) GetSignName() string {
	if x != nil {
		return x.SignName
	}
	return ""
}

func (x *MessageProvider) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *MessageProvider) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	MaxIdleConns  int64                  `protobuf:"varint,3,opt,name=maxIdleConns,proto3" json:"maxIdleConns,omitempty"`
	MaxOpenConns  int64                  `protobuf:"varint,4,opt,name=maxOpenConns,proto3" json:"maxOpenConns,omitempty"`
	LogLevel      GormLogLevel           `protobuf:"varint,5,opt,name=logLevel,proto3,enum=kratos.api.GormLogLevel" json:"logLevel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_conf_conf_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Data_Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Data_Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Data_Database) GetMaxIdleConns() int64 {
	if x != nil {
		return x.MaxIdleConns
	}
	return 0
}

func (x *Data_Database) GetMaxOpenConns() int64 {
	if x != nil {
		return x.MaxOpenConns
	}
	return 0
}

func (x *Data_Database) GetLogLevel() GormLogLevel {
	if x != nil {
		return x.LogLevel
	}
	return GormLogLevel_warn
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,3,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,4,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Database      int32                  `protobuf:"varint,7,opt,name=database,proto3" json:"database,omitempty"`
	EnableCluster bool                   `protobuf:"varint,8,opt,name=enable_cluster,json=enableCluster,proto3" json:"enable_cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_conf_conf_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Data_Redis) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

func (x *Data_Redis) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Data_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_Redis) GetDatabase() int32 {
	if x != nil {
		return x.Database
	}
	return 0
}

func (x *Data_Redis) GetEnableCluster() bool {
	if x != nil {
		return x.EnableCluster
	}
	return false
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"\xaa\x02\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\x12$\n" +
	"\x04auth\x18\x03 \x01(\v2\x10.kratos.api.AuthR\x04auth\x12*\n" +
	"\x06casbin\x18\x04 \x01(\v2\x12.kratos.api.CasbinR\x06casbin\x12!\n" +
	"\x03oss\x18\x05 \x01(\v2\x0f.kratos.api.OssR\x03oss\x12'\n" +
	"\x03log\x18\x06 \x01(\v2\x15.kratos.api.LogConfigR\x03log\x12-\n" +
	"\amessage\x18\a \x01(\v2\x13.kratos.api.MessageR\amessage\"\x81\x03\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x12!\n" +
	"\x03env\x18\x03 \x01(\x0e2\x0f.kratos.api.EnvR\x03env\x12$\n" +
	"\x04cors\x18\x04 \x01(\v2\x10.kratos.api.CorsR\x04cors\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"B\n" +
	"\x04Cors\x12\"\n" +
	"\fallowOrigins\x18\x01 \x03(\tR\fallowOrigins\x12\x16\n" +
	"\x06maxAge\x18\x02 \x01(\x05R\x06maxAge\"\xd7\x04\n" +
	"\x04Data\x125\n" +
	"\bdatabase\x18\x01 \x01(\v2\x19.kratos.api.Data.DatabaseR\bdatabase\x12,\n" +
	"\x05redis\x18\x02 \x01(\v2\x16.kratos.api.Data.RedisR\x05redis\x1a\xb8\x01\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\"\n" +
	"\fmaxIdleConns\x18\x03 \x01(\x03R\fmaxIdleConns\x12\"\n" +
	"\fmaxOpenConns\x18\x04 \x01(\x03R\fmaxOpenConns\x124\n" +
	"\blogLevel\x18\x05 \x01(\x0e2\x18.kratos.api.GormLogLevelR\blogLevel\x1a\xae\x02\n" +
	"\x05Redis\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12<\n" +
	"\fread_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12\x1a\n" +
	"\bdatabase\x18\a \x01(\x05R\bdatabase\x12%\n" +
	"\x0eenable_cluster\x18\b \x01(\bR\renableCluster\"\xb4\x01\n" +
	"\x04Auth\x12*\n" +
	"\x11ecdsa_private_key\x18\x01 \x01(\tR\x0fecdsaPrivateKey\x12(\n" +
	"\x10ecdsa_public_key\x18\x02 \x01(\tR\x0eecdsaPublicKey\x123\n" +
	"\aexpires\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\aexpires\x12!\n" +
	"\x03mfa\x18\x05 \x01(\v2\x0f.kratos.api.MfaR\x03mfa\"z\n" +
	"\x03Mfa\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1a\n" +
	"\brequired\x18\x02 \x01(\bR\brequired\x12%\n" +
	"\x0eencryption_key\x18\x03 \x01(\tR\rencryptionKey\x12\x16\n" +
	"\x06issuer\x18\x04 \x01(\tR\x06issuer\"\x1c\n" +
	"\x06Casbin\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xc5\x01\n" +
	"\tOssConfig\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x1c\n" +
	"\taccessKey\x18\x02 \x01(\tR\taccessKey\x12\"\n" +
	"\faccessSecret\x18\x03 \x01(\tR\faccessSecret\x12\x1e\n" +
	"\n" +
	"bucketName\x18\x04 \x01(\tR\n" +
	"bucketName\x12\x1c\n" +
	"\tbucketURL\x18\x05 \x01(\tR\tbucketURL\x12\x1c\n" +
	"\timgDomain\x18\x06 \x01(\tR\timgDomain\"\"\n" +
	"\x0eOssLocalConfig\x12\x10\n" +
	"\x03dir\x18\x01 \x01(\tR\x03dir\"\x90\x01\n" +
	"\x03Oss\x12(\n" +
	"\x03use\x18\x01 \x01(\x0e2\x16.kratos.api.OssUseModeR\x03use\x12-\n" +
	"\x06aliyun\x18\x02 \x01(\v2\x15.kratos.api.OssConfigR\x06aliyun\x120\n" +
	"\x05local\x18\x03 \x01(\v2\x1a.kratos.api.OssLocalConfigR\x05local\"\x7f\n" +
	"\tLogConfig\x12$\n" +
	"\renableReadLog\x18\x01 \x01(\bR\renableReadLog\x12&\n" +
	"\x0eenableWriteLog\x18\x02 \x01(\bR\x0eenableWriteLog\x12$\n" +
	"\rmaxBodyLength\x18\x03 \x01(\x05R\rmaxBodyLength\"\xe3\x02\n" +
	"\aMessage\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12)\n" +
	"\x10default_provider\x18\x02 \x01(\tR\x0fdefaultProvider\x12=\n" +
	"\rlogin_captcha\x18\x03 \x01(\v2\x18.kratos.api.LoginCaptchaR\floginCaptcha\x127\n" +
	"\vphone_login\x18\x04 \x01(\v2\x16.kratos.api.PhoneLoginR\n" +
	"phoneLogin\x12@\n" +
	"\tproviders\x18\x05 \x03(\v2\".kratos.api.Message.ProvidersEntryR\tproviders\x1aY\n" +
	"\x0eProvidersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.kratos.api.MessageProviderR\x05value:\x028\x01\"\x9e\x01\n" +
	"\fLoginCaptcha\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x05R\x06length\x12%\n" +
	"\x0eexpire_minutes\x18\x04 \x01(\x05R\rexpireMinutes\x12!\n" +
	"\fcache_prefix\x18\x05 \x01(\tR\vcachePrefix\"\xb2\x01\n" +
	"\n" +
	"PhoneLogin\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vcode_length\x18\x02 \x01(\x05R\n" +
	"codeLength\x12%\n" +
	"\x0eexpire_minutes\x18\x03 \x01(\x05R\rexpireMinutes\x12!\n" +
	"\fcache_prefix\x18\x04 \x01(\tR\vcachePrefix\x12\x1f\n" +
	"\vdaily_limit\x18\x05 \x01(\x05R\n" +
	"dailyLimit\"\xd0\x02\n" +
	"\x0fMessageProvider\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vgateway_url\x18\x02 \x01(\tR\n" +
	"gatewayUrl\x12\"\n" +
	"\raccess_key_id\x18\x03 \x01(\tR\vaccessKeyId\x12*\n" +
	"\x11access_key_secret\x18\x04 \x01(\tR\x0faccessKeySecret\x12\x1b\n" +
	"\tsign_name\x18\x05 \x01(\tR\bsignName\x12#\n" +
	"\rtemplate_code\x18\x06 \x01(\tR\ftemplateCode\x12<\n" +
	"\x05extra\x18\a \x03(\v2&.kratos.api.MessageProvider.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*!\n" +
	"\x03Env\x12\a\n" +
	"\x03dev\x10\x00\x12\b\n" +
	"\x04test\x10\x01\x12\a\n" +
	"\x03pro\x10\x02*#\n" +
	"\n" +
	"OssUseMode\x12\n" +
	"\n" +
	"\x06aliyun\x10\x00\x12\t\n" +
	"\x05local\x10\x01*9\n" +
	"\fGormLogLevel\x12\b\n" +
	"\x04warn\x10\x00\x12\b\n" +
	"\x04info\x10\x01\x12\n" +
	"\n" +
	"\x06silent\x10\x02\x12\t\n" +
	"\x05error\x10\x03B'Z%fengyin/app/server/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_conf_conf_proto_goTypes = []any{
	(Env)(0),                    // 0: kratos.api.Env
	(OssUseMode)(0),             // 1: kratos.api.OssUseMode
	(GormLogLevel)(0),           // 2: kratos.api.GormLogLevel
	(*Bootstrap)(nil),           // 3: kratos.api.Bootstrap
	(*Server)(nil),              // 4: kratos.api.Server
	(*Cors)(nil),                // 5: kratos.api.Cors
	(*Data)(nil),                // 6: kratos.api.Data
	(*Auth)(nil),                // 7: kratos.api.Auth
	(*Mfa)(nil),                 // 8: kratos.api.Mfa
	(*Casbin)(nil),              // 9: kratos.api.Casbin
	(*OssConfig)(nil),           // 10: kratos.api.OssConfig
	(*OssLocalConfig)(nil),      // 11: kratos.api.OssLocalConfig
	(*Oss)(nil),                 // 12: kratos.api.Oss
	(*LogConfig)(nil),           // 13: kratos.api.LogConfig
	(*Message)(nil),             // 14: kratos.api.Message
	(*LoginCaptcha)(nil),        // 15: kratos.api.LoginCaptcha
	(*PhoneLogin)(nil),          // 16: kratos.api.PhoneLogin
	(*MessageProvider)(nil),     // 17: kratos.api.MessageProvider
	(*Server_HTTP)(nil),         // 18: kratos.api.Server.HTTP
	(*Server_GRPC)(nil),         // 19: kratos.api.Server.GRPC
	(*Data_Database)(nil),       // 20: kratos.api.Data.Database
	(*Data_Redis)(nil),          // 21: kratos.api.Data.Redis
	nil,                         // 22: kratos.api.Message.ProvidersEntry
	nil,                         // 23: kratos.api.MessageProvider.ExtraEntry
	(*durationpb.Duration)(nil), // 24: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	4,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	6,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	7,  // 2: kratos.api.Bootstrap.auth:type_name -> kratos.api.Auth
	9,  // 3: kratos.api.Bootstrap.casbin:type_name -> kratos.api.Casbin
	12, // 4: kratos.api.Bootstrap.oss:type_name -> kratos.api.Oss
	13, // 5: kratos.api.Bootstrap.log:type_name -> kratos.api.LogConfig
	14, // 6: kratos.api.Bootstrap.message:type_name -> kratos.api.Message
	18, // 7: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	19, // 8: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	0,  // 9: kratos.api.Server.env:type_name -> kratos.api.Env
	5,  // 10: kratos.api.Server.cors:type_name -> kratos.api.Cors
	20, // 11: kratos.api.Data.database:type_name -> kratos.api.Data.Database
	21, // 12: kratos.api.Data.redis:type_name -> kratos.api.Data.Redis
	24, // 13: kratos.api.Auth.expires:type_name -> google.protobuf.Duration
	8,  // 14: kratos.api.Auth.mfa:type_name -> kratos.api.Mfa
	1,  // 15: kratos.api.Oss.use:type_name -> kratos.api.OssUseMode
	10, // 16: kratos.api.Oss.aliyun:type_name -> kratos.api.OssConfig
	11, // 17: kratos.api.Oss.local:type_name -> kratos.api.OssLocalConfig
	15, // 18: kratos.api.Message.login_captcha:type_name -> kratos.api.LoginCaptcha
	16, // 19: kratos.api.Message.phone_login:type_name -> kratos.api.PhoneLogin
	22, // 20: kratos.api.Message.providers:type_name -> kratos.api.Message.ProvidersEntry
	23, // 21: kratos.api.MessageProvider.extra:type_name -> kratos.api.MessageProvider.ExtraEntry
	24, // 22: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	24, // 23: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	2,  // 24: kratos.api.Data.Database.logLevel:type_name -> kratos.api.GormLogLevel
	24, // 25: kratos.api.Data.Redis.read_timeout:type_name -> google.protobuf.Duration
	24, // 26: kratos.api.Data.Redis.write_timeout:type_name -> google.protobuf.Duration
	17, // 27: kratos.api.Message.ProvidersEntry.value:type_name -> kratos.api.MessageProvider
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		EnumInfos:         file_conf_conf_proto_enumTypes,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
